### ISSUE TITLE
Using API with directive

### ISSUE THREAD

**Issue by leondroidgeeks** [vlio20/angular-datepicker#101]
I implemented the date picker using the directive:
`<input class="form-control" formControlName="birthday" id="birthday" #birthday placeholder="Birthday" [dpDayPicker]="config" aria-describedby="basic-addon1">`

When I want to call the open() on this object, I get this Error: 

> undefined is not an object

`  @ViewChild('dpDayPicker') datePicker: DatePickerComponent;`
 `open() {
    this.datePicker.api.open();
  }
`

Do you know any solution?

**Comment by vlio20** [comment]
Thanks. I will take a look

**Comment by vlio20** [comment]
@leondroidgeeks, seems like is is working in the demo :/ 
Can you post some planker or upload a demo repo?

**Comment by vlio20** [comment]
Are you getting any error? or it just not working?

**Comment by leondroidgeeks** [comment]
The application is working. But as soon as I click on the calendar button of the input group and call the open() function I am getting this two errors:

> [Error] ERROR
TypeError: undefined is not an object (evaluating 'this.datePicker.api.open')
open — app.component.ts:20
(anonyme Funktion)
callWithDebugContext — core.es5.js:13535
(anonyme Funktion) — core.es5.js:9299
(anonyme Funktion) — platform-browser.es5.js:2668
onInvokeTask — core.es5.js:3924
runTask — zone.js:191
invoke — zone.js:486
	error
	View_AppComponent_0 (AppComponent.ngfactory.js:62)
	logError (vendor.bundle.js:18401)
	(anonyme Funktion)
	handleError (vendor.bundle.js:6006)
	(anonyme Funktion) (vendor.bundle.js:14229)
	(anonyme Funktion) (vendor.bundle.js:31293)
	onInvokeTask (vendor.bundle.js:8850)
	runTask (polyfills.bundle.js:2780)
	invoke (polyfills.bundle.js:3075)

> [Error] ERROR CONTEXT
DebugContext_
elDef: {index: 16, parent: Object, renderParent: Object, bindingIndex: 10, outputIndex: 8, …}
elView: {def: Object, parent: Object, viewContainerParent: null, parentNodeDef: Object, context: AppComponent, …}
nodeDef: {index: 16, parent: Object, renderParent: Object, bindingIndex: 10, outputIndex: 8, …}
nodeIndex: 16
view: {def: Object, parent: Object, viewContainerParent: null, parentNodeDef: Object, context: AppComponent, …}
DebugContext_ Prototyp
	error
	View_AppComponent_0 (AppComponent.ngfactory.js:62)
	logError (vendor.bundle.js:18401)
	(anonyme Funktion)
	handleError (vendor.bundle.js:6011)
	(anonyme Funktion) (vendor.bundle.js:14229)
	(anonyme Funktion) (vendor.bundle.js:31293)
	onInvokeTask (vendor.bundle.js:8850)
	runTask (polyfills.bundle.js:2780)
	invoke (polyfills.bundle.js:3075)

**Comment by vlio20** [comment]
When debugging the code, what exactly is undefined?

**Comment by leondroidgeeks** [comment]
It does know the object 'datepicker' in my example but when calling the function 'this.datepicker.api.open()' it doesn't know the object 'datepicker.api'. So the attribute 'api' is undefined.

**Comment by vlio20** [comment]
ok, I will check...

**Comment by vlio20** [comment]
I took a look at your code, seems like there is an error on startup of your demo app. I think it is related to the way you are giving reference to the component, please take a look at the component demo:  
```
        <form [formGroup]="formGroup">
          <input [dpDayPicker]="config"
                name="datePicker"
                #dateDirectivePicker="dpDayPicker"
                [theme]="material ? 'dp-material' : ''"
                formControlName="datePicker"
                [placeholder]="placeholder"
                (ngModelChange)="date = $event; log($event)"
                [required]="required"
                />
          <div class="dp-validations">
            <div id="reactiveRequiredValidation" *ngIf="formGroup.get('datePicker').hasError('required') && formGroup.get('datePicker').touched">required</div>
            <div id="reactiveMinDateValidation" *ngIf="formGroup.get('datePicker').hasError('minDate') && formGroup.get('datePicker').touched">minDate invalid</div>
            <div id="reactiveMaxDateValidation" *ngIf="formGroup.get('datePicker').hasError('maxDate') && formGroup.get('datePicker').touched">maxDate invalid</div>
          </div>
        </form>
```

**Comment by leondroidgeeks** [comment]
Thanks! I changed my directive of the input from `#birthdate`
to `#dateDirectivePicker="dpDayPicker"` and it works!

**Comment by vlio20** [comment]
@leondroidgeeks, you ⭐️  would be much appreciated :)
