### ISSUE TITLE
No Year Picker - Feature Request

### ISSUE THREAD

**Issue by C-F-4** [vlio20/angular-datepicker#102]
When you select the month model, on clicking of year could go to year selector than back to the date picker.

**Comment by vlio20** [comment]
There is no year selector currently. Unfortunately I don't think I have the capacity to add this feature in the near time. PR would be great!

**Comment by C-F-4** [comment]
I'm trying to look into it. Trying to understand how the calender-nav label value is working in that template, and on EventEmitter using @Output decorator, and when it's switching back to date-picker component. I think the dropdown for the year can be introduced at that place instead of it being used as a button to switch back to date-picker component.
![screenshot-dp](https://user-images.githubusercontent.com/9998053/27333059-26933536-55e2-11e7-983a-8692fd9dce99.jpg)

**Comment by vlio20** [comment]
It should work the same as the day calendar is switched to month calendar. Note that this option should be configurable .

**Comment by vlio20** [comment]
Interesting. How could I switch back to day picker?

**Comment by C-F-4** [comment]
By selecting the right month for the selected Year.

**Comment by vlio20** [comment]
Not sure this is the correct ux. It is not consistent with the current implementation. 

Maybe some icon next to the year button? When clicking it the select dropdown will open.

**Comment by C-F-4** [comment]
Well the CSS can be modified easily based on the theme. No issues there.

**Comment by vlio20** [comment]
I am not talking about the Css. I don't want to change the year button, I would prefer to put an icon next to the year button which will open the year selector (dropdown) when clicking it. So clicking on the year button will switch back to the day picker.

**Comment by C-F-4** [comment]
So what do you think?

**Comment by C-F-4** [comment]
Ah well I think that can be done

**Comment by vlio20** [comment]
Gr8! Would it be hard to implement some custom select? The default one sucks. 

Regarding configuration, it should expect start and end year. Agree?

**Comment by C-F-4** [comment]
Regarding Start and End year it can be integrated just as min and max are working (like can be used as Attribute as well as configurable variable).
Custom Select can be created just by modifying the css for the select box, if I'm understanding your need right.
Also would it be like a button with arrow on its right used to open a dropdown?

**Comment by vlio20** [comment]
Sounds good. But what would be the start and end date if none provided?

**Comment by C-F-4** [comment]
We can set a default like 1900-currentYear.

**Comment by vlio20** [comment]
This is the default. But maybe it should be also configurable even if min and max not provided

**Comment by C-F-4** [comment]
That's what I said. Default can be on like a 100 year timeline from current. Else configurable using minYear, maxYear in configurable object variable.

**Comment by vlio20** [comment]
Ok

**Comment by C-F-4** [comment]
What about these?
Custom Select can be created just by modifying the css for the select box, if I'm understanding your need right.
Also would it be like a button with arrow on its right used to open a dropdown? On selecting which it'll modify the {{label}} value in the button.

**Comment by vlio20** [comment]
Can you sketch some mock? I don't think I fully understand you.

**Comment by C-F-4** [comment]
Well hold on then.

**Comment by C-F-4** [comment]
Well something like this:
![2017-06-21-15-28-codepen io](https://user-images.githubusercontent.com/9998053/27378701-4c9577a8-5696-11e7-9b9e-3b0eeff34eff.png)
The year part is a button and fa-icon(arrow) is another button
When you click year it'll toggleCalender() { // how it is working now }
But when you click on Arrow, it will toggle the dropdown.

**Comment by vlio20** [comment]
yea looks good, probably more simple icon though... Let's use the one we have for the navigation which is a simple character `>`

**Comment by C-F-4** [comment]
Cool.

**Comment by vlio20** [comment]
sorry for the late response. yes! you can use the one that being used within the date picker now. on master branch

**Comment by vlio20** [comment]
@C-F-4, did you made any progress? I would like starting implement it myself if you didn't start yet.

**Comment by vlio20** [comment]
will close this for now

**Comment by MatthieuBarthel** [comment]
Hello vlio20,

Did you start working on it ? If no, I am interested in this feature, I could try to work on it.

Thank you for your great work !

**Comment by vlio20** [comment]
No, didn't start yet. It would be great if you could contribute. 
Let's discuss first how will it work, look and what configurations could it have.

What do you have in mind?

**Comment by MatthieuBarthel** [comment]
Thanks for your answer, my need is to be able to select a date like fifty years ago without having to click fifty times on the arrow.

The idea developed above is nice, but I think select control is not very easy to customize by CSS. I have two others proposals :

1. Simpler solution: adding buttons to go 10 years further/back 
![ui-1](https://user-images.githubusercontent.com/435534/28618952-9ec73a8a-7206-11e7-8519-2a4615411e0d.png)

2. More complicated but probably nicer: adding a third selection level, when you click on the year button you arrive on this third screen :
![ui-2](https://user-images.githubusercontent.com/435534/28618995-ca6c1228-7206-11e7-986e-cdabe9cf1ed1.png)

What do you think ?

**Comment by vlio20** [comment]
I have to say that I like the first option (and I think it would be easier to implement) is **very nice**!!!
Few points before you start:
1. The step should be configurable (it can be 10, 20 [years] --- etc) 
2. The whole feature should be configurable in terms of enabled/disabled 
3. The fast forward year buttons should behave as the simple buttons in terms of min/max dates.
4. Please don't forget demo, unit, e2e and documentation.

Let me know if I can help somehow.

**Comment by MatthieuBarthel** [comment]
Ok great, I will work on option 1 soon and I come back to you.

Thank you :-)

**Comment by vlio20** [comment]
awesome!!! reopening!

**Comment by vlio20** [comment]
@MatthieuBarthel, thank you for the awesome job. This is a very nice feature!!!

**Comment by MatthieuBarthel** [comment]
Great, many thanks to you @vlio20 for your very nice work.
