### ISSUE TITLE
Datepicker should open on selected date instead of on current month

### ISSUE THREAD

**Issue by trobinpl** [vlio20/angular-datepicker#103]
I really like this plugin - it's easy for use and does exactly what it supposed to. Thank you for great work!
I have one little suggestion though - right now, no matter what date is selected, every time you open datepicker popup it shows current month. If I wanted to select for example 1990-05-15, but selected 1990-05-16 instead I have to click trough all the years back to 1990 and select correct date once more.

It's not implemented this way or am I missing some configuration option?

**Comment by vlio20** [comment]
Can you put some step by guide? 
In the demo, the component remembers the last position. So I am not sure I understand your case.

**Comment by trobinpl** [comment]
I didn't previously realized, that it actually works this way on the demo page! All I did was attaching datepicker in directive mode and configuring format and week names - nothing fancy. When I get back to work on Monday I'll try to investigate further and see what is different in my case compared to demo page.

**Comment by trobinpl** [comment]
I found some strange behaviour. I've tried to change all configuration settings, because I thought maybe different locale settings were causing the problems. Then I double checked on demo page and in directive mode it works exactly the same! Just switch "Mode" from "Day Picker" to "Day Directive", select any day not in current month and then reopen picker. It should open on current month by default.

**Comment by vlio20** [comment]
Checking....

**Comment by vlio20** [comment]
Yup, I was able to reproduce. Will take a look as soon as I can. Or do you want to PR?

**Comment by trobinpl** [comment]
I will take a look today at work - I'm not sure if I will be able to fix this though, because of my very limited experience with Angular development :-)

**Comment by vlio20** [comment]
Cool! I will be able to work on it in my evening (after work) - in about 9 hours.

**Comment by trobinpl** [comment]
Unfortunately I was not able to diagnose the problem in code, but I noticed, that displayDate property is not set properly when selecting date
![datepicker](https://user-images.githubusercontent.com/3727358/27323030-680fcc14-55a0-11e7-9f2d-57475b1ed596.PNG)
I hope this will help you somehow in finding error more quickly. Sorry for being more helpful though.

**Comment by vlio20** [comment]
ok, I will take a look

**Comment by isaiev** [comment]
Some problem is here, condition is always true.
https://github.com/vlio20/angular-datepicker/blob/master/src/app/date-picker/date-picker.directive.ts#L126

**Comment by vlio20** [comment]
@isaiev, do you want to PR a fix?

**Comment by isaiev** [comment]
@vlio20 I'll try :)

**Comment by trobinpl** [comment]
@vlio20 @isaiev I was able to play around with this problem a little bit and managed to correct the issue :-). I created pull request: https://github.com/vlio20/angular-datepicker/pull/110.
