### ISSUE TITLE
No theme option

### ISSUE THREAD

**Issue by bradjenn** [vlio20/angular-datepicker#104]
Hi, is there a way to have no css applied to the component

I'm trying to override css but because there is already some included the class names change. 

thanks

**Comment by vlio20** [comment]
hi @bradjenn, by default there is no theme. What you see it the default styling of buttons and other html elements.

**Comment by bradjenn** [comment]
@vlio20 thats odd, how i am getting css specific for classes like `.dp-calendar-nav-container[_ngcontent-c6]` ?
