### ISSUE TITLE
Building with rollup

### ISSUE THREAD

**Issue by weslley39** [vlio20/angular-datepicker#106]
When i try to build with AOT and Rollup, this error happen:

```
  Error: 'DpDatePickerModule' is not exported by node_modules/ng2-date-picker/index.js

  ...

  code: 'MISSING_EXPORT',
  url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
  pos: 1322,
```

when I'm importing the module I'm using:

`import { DpDatePickerModule } from 'ng2-date-picker/index'`

but I already tried to put in SystemJS like:

```
      {
        name:'ng2-date-picker',
        path:'node_modules/ng2-date-picker',
        packageMeta:{
          main: 'index.js',
          defaultExtension: 'js'
        }
      },
```

But nothing is working :(

**Comment by vlio20** [comment]
Never tried to use Rollup, but I think there is also an issue with your import.
`import { DpDatePickerModule } from 'ng2-date-picker/index'`

it should be:
`import { DpDatePickerModule } from 'ng2-date-picker'`

**Comment by weslley39** [comment]
Solved with:
`import { DpDatePickerModule } from 'ng2-date-picker/date-picker.module';`

**Comment by vlio20** [comment]
this is very odd... didn't `import { DpDatePickerModule } from 'ng2-date-picker'` work?

**Comment by weslley39** [comment]
with rollup, no :(

this was the one way that I figured out to get working with rollup

**Comment by vlio20** [comment]
Can you explain why?
