### ISSUE TITLE
can this datepicker change language?

### ISSUE THREAD

**Issue by ZzzzzZXxxxxX** [vlio20/angular-datepicker#108]
if can, how do i do? 3q  :）

**Comment by vlio20** [comment]
there are many formatters + you can use moment locate. Let me know what exactly you want to change

**Comment by ZzzzzZXxxxxX** [comment]
i use the month picker, and i want the month'language show like chinese. how did i set the config?

**Comment by vlio20** [comment]
Please check checkout the month formatter. You will find it in the docs.

**Comment by ZzzzzZXxxxxX** [comment]
e.. set the monthFormat or monthFormatter?

**Comment by vlio20** [comment]
`monthFormatter`

**Comment by ZzzzzZXxxxxX** [comment]
can you give me an Example of how to use monthFormatter...thank you!

**Comment by ZzzzzZXxxxxX** [comment]
`monthFormatter:(moment)=>'一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月',`this is right?

**Comment by vlio20** [comment]
nope :).
```
monthFormatter: (date: Moment)=> {
  switch(date.month()) {
    case 0:
      return 一月;  // I guess it is January 
    case 1:
      return 二月; // I guess it is February  
  }
....
}

```

**Comment by ZzzzzZXxxxxX** [comment]
.....soga!thank you so much!

**Comment by ZzzzzZXxxxxX** [comment]
`Exception: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context. at Function.remoteFunction (<anonymous>:2:26)` it report errors! i need import moment?

**Comment by vlio20** [comment]
can you tell to what code this error relates, you don't need to include moment if you are not using it in your app.

**Comment by ZzzzzZXxxxxX** [comment]
`this.datePickerConfig = {
      format: 'YYYY-MM',
      disableKeypress: true,
      monthFormatter: (date: Moment)=>{
        switch(date.month()) {
            case 0:
                return '一月';  //it is January 
            case 1:
                return '二月'; // it is February  
           }
      },
      max: '2017-08-01'
    };`  this is my config! I want show the month language of chinese! but the `Moment` i don't import.And this is not work!

**Comment by ZzzzzZXxxxxX** [comment]
can i set the monthFormatter like set the weekdayNames use Obj?

**Comment by vlio20** [comment]
If you want to use `Moment` types you will have to add moment as a dependency. You also can remove `Moment` from `monthFormatter: (date: Moment)`.
