### ISSUE TITLE
Latest Commits are not publish in NPM, can you please publish them?

### ISSUE THREAD

**Issue by naharyd** [vlio20/angular-datepicker#120]
Latest Commits are not publish in NPM (for example, commit: bba6b070f74ceda9bb1b429af3506ef19d453302),

Can you please publish them?

**Comment by vlio20** [comment]
@naharyd, please checkout 2.1.1

**Comment by naharyd** [comment]
Thank you!
You are doing great job!

**Comment by vlio20** [comment]
your ⭐️  would be much appreciated

**Comment by naharyd** [comment]
You have my  :star: :smiley:
