### ISSUE TITLE
Help needed SystemJS integration

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [vlio20/angular-datepicker#122]
Hi,
Please share the steps to integrate with (Angular4-SystemJS)

**Comment by vlio20** [comment]
does this helps you:
https://github.com/vlio20/angular-datepicker/issues/84

**Comment by aditya-padhi-kbl** [comment]
@vlio20 
Thank-you.  I will implement the same & share my findings.  Thank-you once again :)

**Comment by vlio20** [comment]
Great! will close for now
