### ISSUE TITLE
Need information on callback function like onSelect for angular-datepicker

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [vlio20/angular-datepicker#123]
Hi,
May be I am missing something.  But is there any callback function when the user selects a date.
Like onSelect="callbackFunction($event)" something like that.

**Comment by vlio20** [comment]
please checkout https://github.com/vlio20/angular-datepicker/issues/77, let me know if it helps.

**Comment by aditya-padhi-kbl** [comment]
@vlio20 
This issue is resolved.  I am closing it.
