### ISSUE TITLE
Demo url not working in IE 11

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [vlio20/angular-datepicker#124]
Hi @vlio20 ,
The demo url shared i.e. "https://vlio20.github.io/angular-datepicker/" works in Chrome but doesn't load in IE11.  Just wanted to know if this component is supported in IE11?

**Comment by vlio20** [comment]
Not, sure. I am on  a mac. Can you please share a screenshot?

**Comment by aditya-padhi-kbl** [comment]
<img width="525" alt="ieissues" src="https://user-images.githubusercontent.com/28565587/28027559-19b7a894-65b7-11e7-8aba-0c0556ff02ae.PNG">

**Comment by vlio20** [comment]
Is it possible of you to fork the repo and see if it works in dev mode? It is hard to understand what's going on here.

**Comment by aditya-padhi-kbl** [comment]
Hi,
I forked the repo downloaded the node_modules.
Started the application by **npm start**
In the vendor.bundle.js
`function combine(options) {
    return ((Object)).assign.apply(((Object)), [{}].concat(options));
}`

runs fine in Chrome. but fails in IE. 
By looking at the browser call stack it is difficult to identify if it is the issue with vendor (library) or the component.  Can you share the steps to run the application without minifying.

**Comment by vlio20** [comment]
`npm start` is using the `ng serve` command so it shouldn't serve the minified files.
Are you sure you are using 4200 port and the you are on the webpack dev server (angular cli dev mode)?

**Comment by aditya-padhi-kbl** [comment]
Hi, yes I am using port 4200.  I separated the component, used it in a sample application & it is working in IE11.  It seems the demo page is not working in IE 11.  Could be an issue with the bundling process.

**Comment by vlio20** [comment]
Awesome news! I will investigate the issue with the demo page. Closing this issue for now!
