### ISSUE TITLE
To know the actual date selected by the user

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [vlio20/angular-datepicker#125]
Hi @vlio20 ,

Suppose the date format is 'DD-MM-YY'.  User selects '20-01-2017'.  The output we get is '20-01-17'.
If I want to change this output again to Date object then it is not possible.  So is there any parameter to know what the actual selection is (actual selection is 20-01-2017), even though the displayed value is '20-01-17'.  A complete date object of the selection will be great considering the backend apis expecting date in some format say 'DD-MM-YYYY'

**Comment by vlio20** [comment]
mmmm... I think that you shouldn't allow the user to put a date in a different format. 
If you will check the form validation I think you will see that the form is invalid (if the format is 'DD-MM-YY' and the input is '20-01-2017'.  

Let me know if this is correct.

**Comment by aditya-padhi-kbl** [comment]
Hi,
Yes before passing to dp-date-picker I am formatting my date as per the config.  That is working fine.

However while sending the selected date back to api, I have to format it back to some specific format as expected by backend service.  If I could get the selected date (date selected through date picker), then I would be able to format it using moment before sending it to the api.  So, it will be nice if we could know what the actual year the user has selected. So, in UI I am showing **"20.01.89"** but to the backend I will pass **"20-01-1989"** . In order to know the century of the selected date i need the year. As it could be 1989/ 2089

**Comment by vlio20** [comment]
I think I understand your needs, but I also think that you shouldn't allow the user pass a date in a format you are not supporting - i.e. passing a date not in the 'DD-MM-YY' format.

**Comment by aditya-padhi-kbl** [comment]
Hi,
Yes I am not allowing the user to pass in a different format.  After selecting the date I am sending that specific date to a REST api.  It expects to be in UTC format.  However,  the format I have set 'DD-MM-YY' is not as per UTC.  So I have written a separate service which will re-format it back to UTC.  So from the datepicker if the user select, day as 20, month as 02, year as 2017.  The ng-model has 20.01.17.  If through some selector if I get the actual date object or the selected parameters then I can convert to utc and pass it to rest api

**Comment by vlio20** [comment]
You mean that you want to get the Moment object of the selected date?

**Comment by aditya-padhi-kbl** [comment]
Yes. either moment object (but not the formatted date) or the date object (javascript  new Date () ) type then i can get to know the century and other properties.  Anyways ngModel will always have the formatted date.

I hope I am clear

**Comment by vlio20** [comment]
Sorry but if you know the format and you have the value (which is have to be in the required format) then you can create the Moment/Date object yourself:  
```
const date = moment(value, format);
```

What am I missing?

**Comment by aditya-padhi-kbl** [comment]
Closing this issue as the solution stated above should work.
