### ISSUE TITLE
date not getting displayed when passed as a string (ISO)

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [vlio20/angular-datepicker#126]
I am passing '2017-07-09T00:00:00Z' to ng-model
In html
`<dp-date-picker [(ngModel)]="selectedDate" class="form-control" [config]="config" [theme]="theme" #datePicker (ngModelChange)="onDateChange()"></dp-date-picker>`

So selectedDate is '2017-07-09T00:00:00Z'.

the config is an object as per the documentation.
it has one paramenter  {format: 'DD-MM-YYYY'}

However the date is not displayed.  What am I missing

**Comment by vlio20** [comment]
You are passing a date in which is not aligned with the provided format :  
 '2017-07-09T00:00:00Z' !=  'DD-MM-YYYY'

**Comment by aditya-padhi-kbl** [comment]
Hi, This is resolved.  Thanks.
