### ISSUE TITLE
setting ngModel to '' or null doesn't clear the value

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [vlio20/angular-datepicker#127]
Suppose if I want to clear the selection I am doing this.selectedDate = '';
Still the selected the date is visible in the selection of date picker.

I have to manually set it by this.datePickerComponent._selected = [];  // this clears the datepicker.

this.datePickerComponent.inputElementValue = '';  //this clears the ng-model

**Comment by vlio20** [comment]
can you please post your template as well?

**Comment by aditya-padhi-kbl** [comment]
`  <div class="sp3-datepicker-com">  
     <div class="input-group">
        <dp-date-picker [(ngModel)]="selectedDate" class="form-control" [config]="config" [theme]="theme" #datePicker (ngModelChange)="onDateChange()" [disabled]="enablecontrols"></dp-date-picker>
        <span class="input-group-addon" (click)="openCalendar()" id="openCalendarPopup"><i class="fa fa-calendar" aria-hidden="true"></i></span>
        <span class="input-group-addon" (click)="closeCalendar()" id="closeCalendarPopup"><i class="fa fa-times" aria-hidden="true"></i></span>
    </div>
  </div>`

**Comment by vlio20** [comment]
Thanks, I will take a look. It would be much faster if you will post an example on github or plunker (even better)

**Comment by cen1** [comment]
I can confirm this bug. Setting the variable bound by `[(ngModel)]` to null does not reset the date to empty. Right now it seems there is no way to programatically clear the date. I'd make a plunkr if there is an existing one to modify, altho it is very easy to test this.

**Comment by vlio20** [comment]
Thanks for the steps to reproduce. I will check it ASAP.  A plunker or demo repo would be great.

**Comment by aditya-padhi-kbl** [comment]
@cen1 
In case you wish to clear the selection:-
this.selectedDate = null;  //ngModel
this.datePickerComponent._selected = [];  //reference
this.datePickerComponent.inputElementValue = ''; //DOMValue

**Comment by sandraacha9** [comment]
Hello, what type of object is datePickerComponent?
Thanks

**Comment by vlio20** [comment]
Please open a new issue
