### ISSUE TITLE
How to set locale

### ISSUE THREAD

**Issue by zjcboy** [vlio20/angular-datepicker#129]
This is better datepicker plugin,
but i need set locale,please tell me how to set it,
thanks!

**Comment by vlio20** [comment]
What exactly you need to be localised? The plugin is based on[ Momen.js](https://momentjs.com/) it has a great support for localisation, you can find more information: http://momentjs.com/docs/#/i18n/.

Basically you just need to change the locale as seen in the link above. Another option is to use the formatters provided within this component.

**Comment by zjcboy** [comment]
Hello, I need to change language, 
But i modify the file, It doesn't seem to work
‘/node_modules/_ng2-date-picker@2.1.1@ng2-date-picker/node_modules/moment/moment.js’

**Comment by vlio20** [comment]
@zjcboy, you don't need to change any file, just do: 
```
import * as moment from 'moment';
moment.locale('de') // or whatever language you require
```

Do it in you app.module file.

**Comment by zjcboy** [comment]
Thanks, I'm try it, It looks all right.
Last, i suggest add this to plugin option config.

**Comment by vlio20** [comment]
You are probably right. Will do!
