### ISSUE TITLE
Can't bind to 'mode' since it isn't a known property of 'dp-date-picker'.

### ISSUE THREAD

**Issue by permarco** [vlio20/angular-datepicker#138]
somehow the attrbute mode does not work instead i used attribut with name key to set the dp-date-picker to mothmode.

However in the documentation it says to switch the attribute mode...

**Comment by vlio20** [comment]
What you see in the documentation is the newer version of the component doc - which is not released yet. 

Please use `type` instead of `mode`.

Let me know if it fixes your issue.

**Comment by permarco** [comment]
yes type works for me thank you
