### ISSUE TITLE
IDatePickerDirectiveConfig should extend ITimeSelectConfig

### ISSUE THREAD

**Issue by dankrajnak** [vlio20/angular-datepicker#139]
The IDatePickerDirectiveConfig extends IDayCalendarConfig, and IMonthCalendarConfig, but not ITimeSelectConfig.

**Comment by vlio20** [comment]
oops! will be fixed in next version. Thanks.

**Comment by vlio20** [comment]
@dankrajnak, would you like to submit a PR?
