### ISSUE TITLE
IDatePickerConfig no longer contains weekdayNames

### ISSUE THREAD

**Issue by cen1** [vlio20/angular-datepicker#140]
This broke in 2.2.0 and I don't see any changes about this in the readme.

**Comment by vlio20** [comment]
You should use locale configuration. Let me know know

**Comment by cen1** [comment]
Locale seems to work great. Readme should be updated though.

**Comment by vlio20** [comment]
Locale is there...

**Comment by cen1** [comment]
Yes, but shouldn't weekdayNames be removed?

**Comment by vlio20** [comment]
Ohhh I missed that. Want to PR?

**Comment by cen1** [comment]
Sure , will do later today.
