### ISSUE TITLE
How to avoid seconds in date time field ?

### ISSUE THREAD

**Issue by boly38** [vlio20/angular-datepicker#145]
Hi
 Inline datepicker works well to select date + time. 
Once a selection is made on the popin, , I got the following result in the text field: "22-07-2017 14:35:52"
this result includes seconds.

 I would like to **avoid displaying seconds in the result text field**.
 seems the following config has no effect:

```
          showSeconds: false,
          secondsFormat: ""
````

Another way I tried the wollowing syntax (with datex directive):
```
    [ngModel]="mydate | datex:'DD-MM-YYYY HH:mm'"
```

but this format is used only at page init (not on datetime select).

How to do this ?
I noticed in demo that show second could be true or false, it has only effect in the popin: we always have seconds value in the text field.
I could provide additionnal info if required.
Thanks again

**Comment by vlio20** [comment]
`showSeconds: false` is only for the display. You could pass a format `'DD-MM-YYYY HH:mm'` then you shouldn't get it.

**Comment by boly38** [comment]
ho dumb, I just missed that option!
thanks
