### ISSUE TITLE
IE10 issue (on demo too): datepicker is not hidden

### ISSUE THREAD

**Issue by boly38** [vlio20/angular-datepicker#147]
Hi 
On my project I need IE10 compatibility, 

when I'm testing datepicker with mode = IE10,  I got some issue :/

I don't need to provide sample as I was able to reproduce with Demo.

Step to reproduce:
- open IE and go to  https://vlio20.github.io/angular-datepicker/
- press "F12" and select mode= "10" at the top-right of the developper's panel,

Issues:
- some calendars popins are already shown (must be hidden): >> Min-Date Validation (minDate) >>Min Selectable Date (min)
- when I click to select a date on the first main datepicker, the popin never close.

On angular2, "hidden" is to avoid for IE compatibility issue, some people recommend to use "ngIf" instead of "[hidden]" attribute. That's what I've done on my project. But for this component the show/hide behavior is included in the component source..

Let me know, thanks

**Comment by boly38** [comment]
I just found a fix !
Source: https://github.com/angular/angular/issues/5774 : cf (e-oz commented on 13 Apr 2016)


> better alternative to slow *ngIf is combination of [attr.data-hidden] (instead of [hidden]) and rule [data-hidden="true"]{display: none !important} in global CSS.


I've added the following style to my main css file:
```
/** Angular hidden and IE10 issue */
[data-hidden="true"]{display: none !important}
```

I made a search onto "node_modules\ng2-date-picker" for "hidden":
* I replaced ` [hidden]=`  by  `[attr.data-hidden]=`

I made a search onto "node_modules\ng2-date-picker" for "visibility" strings:
* I replaced  `visibility: hidden;`  by `visibility: hidden; display: none;`
* I replaced  `element.style.visibility = 'hidden';`  by ` element.style.visibility = 'hidden';      element.style.display = 'none';`
* I replaced  `element.style.visibility = 'visible';`  by ` element.style.visibility = 'visible';      element.style.display = 'inherit';`

I don't have time  to prepare a PR sorry
Hope to get a fix from you :)

**Comment by boly38** [comment]
Limit out of scope minor remarks:
* while using patched version of "ng2-date-picker" I noticed that some `.map` includes a potential wrong value for "sources". Example: "sources":["../../prebuild/app/calendar-nav/calendar-nav.component.ts"]

```
$ grep -Rnl prebuild
calendar-nav/calendar-nav.component.js.map
common/services/utils/utils.service.js.map
common/types/calendar-mode-enum.js.map
common/types/calendar-type-enum.js.map
common/types/calendar-value-enum.js.map
date-picker/date-picker-directive.service.js.map
date-picker/date-picker.component.js.map
date-picker/date-picker.directive.js.map
date-picker/date-picker.service.js.map
date-picker.module.js.map
day-calendar/day-calendar.component.js.map
day-calendar/day-calendar.service.js.map
day-time-calendar/day-time-calendar.component.js.map
day-time-calendar/day-time-calendar.service.js.map
index.js.map
month-calendar/month-calendar.component.js.map
month-calendar/month-calendar.service.js.map
time-select/time-select.component.js.map
time-select/time-select.service.js.map
```

to avoid warning, I replace "sources" with "calendar-nav.component.d.ts"(in my example)

**Comment by vlio20** [comment]
thanks @boly38, I will take a look.

**Comment by craigbrett17** [comment]
This issue still seems to be active, even though it's been closed. What's the status with this? 

Asking as it's been raised as an issue with an app we're developing.

**Comment by vlio20** [comment]
Please post a stackblitz

**Comment by craigbrett17** [comment]
To quote @boly38: "I don't need to provide sample as I was able to reproduce with Demo."

* Open up IE 10 on a VM (browser stack is what we have here)
* Browse to the demo page
* Voila!

This isn't a JS error. There is no "stack" to blitz, as far as I could tell.
