### ISSUE TITLE
set locale to the datepicker

### ISSUE THREAD

**Issue by MohamedAmineOuali** [vlio20/angular-datepicker#149]
Hello,

I want to set the locale for the datepicker but it didn't work.

In my componenet I have declared a config:     
config:{locale:"fr"};

and in my html I have:
<dp-date-picker mode="month" theme="dp-material" required="true" [(ngModel)]="selectedDate" [config]="config" ></dp-date-picker>

But the locale didn't change. what is the problem?

**Comment by vlio20** [comment]
Seems OK. Can you post a demo repo? 
Do you have any errors in you console?

**Comment by MohamedAmineOuali** [comment]
Hi,
No there is no errors in the console.
How can I post a demo repo?

**Comment by MohamedAmineOuali** [comment]
this is same Preview from debug session.
![image](https://user-images.githubusercontent.com/20454717/28739618-3eaf6894-73f4-11e7-82ac-8bc4ab92fde5.png)

![image](https://user-images.githubusercontent.com/20454717/28739674-a5b474f8-73f4-11e7-9237-a3ba881dcd3a.png)


As you can see in the second one the locale in config is always set to fr but the datepicker is in English

**Comment by vlio20** [comment]
Just create a simple project with your config and push it to github

**Comment by MohamedAmineOuali** [comment]
This is my project repo  https://github.com/MohamedAmineOuali/test
I am using http-server .   to start the server.

**Comment by vlio20** [comment]
from which folder should I run it? any build steps?

**Comment by MohamedAmineOuali** [comment]
from the root directory "test"

Go to root directory of the project then run this command "http-server ."  
the server should start on 127.0.0.1:8080   go to this url then press test.html and you will see the date picker in the page

you will find my component in.
test/my-webapp/Scripts/App/components/note-de-frais.component.ts
and my html template in 
test/templates/note-de-frais-template.html

**Comment by vlio20** [comment]
@MohamedAmineOuali, I will need the source code. I will want to change the code in order to debug it. Please post the precompiled code and instruction on how to compile it.

**Comment by MohamedAmineOuali** [comment]
I don't know what you mean by precompiled code I am using note-de-frais.componet.ts is the typescript where I make my changes I am using intellj to compile the typescript But if you want I can find you something that will compile the ts for you after making your changes.
Is that what you want?
I can also post my hole project without simplification but it is a javaEE project and it will be necessary to make some config in order to make it run.

**Comment by MohamedAmineOuali** [comment]
I am using google chrome in order to debugging the typescript

**Comment by vlio20** [comment]
Ok, so you compiling with intellij. That what I was looking for. thanks. Will take a look.

**Comment by MohamedAmineOuali** [comment]
Thank you very much, I am really appreciated your effort

**Comment by vlio20** [comment]
@MohamedAmineOuali, I am trying to debug your code. But it seems like my hangings aren't effecting the code execution.

Please try to see if it works with the demo you posted. Note - I am also using Intellij and compiling ts through it - but my changes are ignored.

**Comment by MohamedAmineOuali** [comment]
I think there is a problem with cache when using http-server

first of all try to verify the config of the typescript in intellj it should be like this 
![image](https://user-images.githubusercontent.com/20454717/28747794-86e14672-749f-11e7-8f79-3e4ed5f032fb.png)

run your server using this command "http-server -c-1 ." it will prevent cache

try to open the test.html in incognito window.

I did this and I can see my updates when refreshing the page use ctrl+f5 to prevent chrom from cahing things

**Comment by vlio20** [comment]
The files are compiled correctly as I see the changes in the js file. I also see that chrome status code for the required files is 200 (if it was 304 it means it brought from cache). I always see the old files.

**Comment by vlio20** [comment]
please try to do the following:  
add this line in your app.module.ts:  
`import 'moment/locale/fr';`
Don't forget to also add it to your system.config.js file.

**Comment by vlio20** [comment]
I am not an expert in SystemJS. But you have to somehow load the `fr` locale.

**Comment by vlio20** [comment]
I were able to make it work when I loaded:
`            'moment': 'npm:moment/min/moment-with-locales.js'`

in System.config.js

The better solution is to pull the required locale from node_module/locale/fr.js.

Though I am not sure how to do it with SystemJS.

Hope that helps.

**Comment by MohamedAmineOuali** [comment]
Thank you very much it work.

**Comment by MohamedAmineOuali** [comment]
And also thank you for this information
 

> I also see that chrome status code for the required files is 200 (if it was 304 it means it brought from cache).

 I didn't know that

**Comment by vlio20** [comment]
Was happy to help. Please ⭐️ it if you like it. 

Also, if you did as I suggested with the specific locale - please post your solution here for other users.
