### ISSUE TITLE
dp-date-picker mode daytime not showing time option

### ISSUE THREAD

**Issue by Avishaidev** [vlio20/angular-datepicker#153]
html:
`<dp-date-picker theme="dp-material" [(ngModel)]="startDate" [config]="dateConfig"></dp-date-picker>`

Config:
`dateConfig:any = {
    locale: 'he',
    disableKeypress: true,
    format: 'DD/MM/YYYY',
    opens: 'left',
    mode: 'dayTime',
    showTwentyFourHours: true
  }`

**Comment by FlawaCLV** [comment]
@Avishaidev I'm running the same error. What did you do to make it work ?

**Comment by FlawaCLV** [comment]
Nevemind, the solution `mode` is an attribute.

**Comment by AanchalMehrotra02** [comment]
Just add attribute mode="daytime" as follows :
<dp-date-picker mode="daytime" theme="dp-material" [(ngModel)]="startDate" [config]="dateConfig"></dp-date-picker>
