### ISSUE TITLE
Failed to Build after Install

### ISSUE THREAD

**Issue by cliffeby** [vlio20/angular-datepicker#155]
Using AngularCli and Angular 2.4.10.  Did an install and added import statements to app.module. 

ERROR in C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/ng2-date-picker/date-picker/date-picker.component.d.ts (17,45): Module '"C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/@angular/forms/index"' has no exported member 'ValidationErrors'.

ERROR in C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/ng2-date-picker/day-calendar/day-calendar.component.d.ts (10,45): Module '"C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/@angular/forms/index"' has no exported member 'ValidationErrors'.

ERROR in C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/ng2-date-picker/time-select/time-select.component.d.ts (8,45): Module '"C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/@angular/forms/index"' has no exported member 'ValidationErrors'.

ERROR in C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/ng2-date-picker/time-select/time-select.service.d.ts (5,36): Initializers are not allowed in ambient contexts.

ERROR in C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/ng2-date-picker/day-time-calendar/day-time-calendar.component.d.ts (4,45): Module '"C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/@angular/forms/index"' has no exported member 'ValidationErrors'.

ERROR in C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/ng2-date-picker/month-calendar/month-calendar.component.d.ts (7,45): Module '"C:/Users/cliff/WebstormProjects/RochV001/ngApp/node_modules/@angular/forms/index"' has no exported member 'ValidationErrors'.
webpack: Failed to compile.

**Comment by vlio20** [comment]
Please post a demo repo. You can fork this one and change the demo page accordingly to fit your settings which reproduce the error.

**Comment by vlio20** [comment]
will close for now

**Comment by hugohernani** [comment]
I'm having the same exactly issue.
