### ISSUE TITLE
Remove console.log from toggleMeridiem function

### ISSUE THREAD

**Issue by MOstafaMRady** [vlio20/angular-datepicker#156]
At file "**time-select.component.js:100**" 
It is not an issue, but the function has a console.log(this.selected.locale())
This keeps logging to console, removing it will be better

**Comment by vlio20** [comment]
Holly crap. Want to PR?

**Comment by MOstafaMRady** [comment]
Ok

**Comment by MOstafaMRady** [comment]
Somehow I'm new to github, I cloned the repo and removed the line but I can't create a PR or a branch
