### ISSUE TITLE
Integrate with bootstrap 4

### ISSUE THREAD

**Issue by Meistercoach83** [vlio20/angular-datepicker#158]
Is it possible to give the input field the same class as an form-control in bootstrap 4? The popup calendar should not be "updated", only the input field.

**Comment by vlio20** [comment]
you can add it with `theme` attribute. This will add a class to the popup component. You can find more info in the documentation.

**Comment by Meistercoach83** [comment]
I found that theme Option already. But I don´t know how to use it on my own. I import the demo.less stylesheet in my parent component but nothing happens.

**Comment by vlio20** [comment]
The theme property adds whatever class you want to the popup element. Please post a demo repo - I will try to help.

**Comment by vlio20** [comment]
@Meistercoach83, did it help?

**Comment by carlhussey** [comment]
I am interested in this from a general styling perspective. I see that the material style is built in to this component but would prefer to change it entirely. Along with @Meistercoach83 question, once changing `theme="custom123"`, how/where would we define the css we want to use to replace the default?

**Comment by vlio20** [comment]
Is there a problem to add a class to the theme attribute?

**Comment by Meistercoach83** [comment]
sorry, I´m in hospital... will answer it asap

**Comment by vlio20** [comment]
I hope it for child birth reasons!

**Comment by vlio20** [comment]
Because angular 2+ adds random attribute to the component tags, you will have to use important in your CSS attributes.

Cloasing for now
