### ISSUE TITLE
Navigation arrows not vertically centered (directive-based)

### ISSUE THREAD

**Issue by ameyer-pivotal** [vlio20/angular-datepicker#161]
Default styling for `dp-material` theme seems to be off a bit, as the navigation arrows are not vertically centered. There is no other styling, as this is out of the box with a newly-generated CLI project.

This is for a directive-based approach:
```
<input [(ngModel)]="selectedDate" [dpDayPicker]="datePickerConfig"
       theme="dp-material" mode="month">
```

Screen shot:

<img width="232" alt="screen shot 2017-08-03 at 10 33 42 pm" src="https://user-images.githubusercontent.com/24568368/28953272-8d529898-789c-11e7-9d4f-1ec092ef74db.png">

Doesn't seem to happen on non-directive-based approach:

```
<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig"
theme="dp-material" mode="month">
```

I was able to fix it by adjusting the line height, though I'm not sure if this is the best fix:
```
.dp-calendar-nav-right, .dp-calendar-nav-left {
    line-height: 0;
}
```
After:

<img width="228" alt="screen shot 2017-08-03 at 10 46 29 pm" src="https://user-images.githubusercontent.com/24568368/28953438-a28898c4-789d-11e7-9ec6-a880d6b8e562.png">

Version info:
```
└─┬ ng2-date-picker@2.2.0 
  └── moment@2.18.1 
```

**Comment by vlio20** [comment]
will fix in the next version
