### ISSUE TITLE
[Feature Request] Attribute readOnly

### ISSUE THREAD

**Issue by WaterBleu** [vlio20/angular-datepicker#164]
is it possible to implement readOnly attribute?
reason being that I'm not looking to disable the input but have the input readOnly
but also disable the toggling the calendar onclick

**Comment by vlio20** [comment]
Not sure what are the differences... Please elaborate.

**Comment by WaterBleu** [comment]
namely the display of it when working with material design

**Comment by vlio20** [comment]
I still not sure what is required from this type of option. Can I have an example?

**Comment by WaterBleu** [comment]
example being when using input as display field.
the input itself has readOnly tag but onClick of the input field calendar still pops out.
only eliminated when the whole input field is disabled (which is not the intended result)

**Comment by vlio20** [comment]
I suggest you to use just css for that. You could put pointr-events: none on the component. This way no cluck events will take place. Let me know if it helps you.

**Comment by vlio20** [comment]
closing for now
