### ISSUE TITLE
Error in inline monthpicker when selecting the same month in a different year

### ISSUE THREAD

**Issue by GuillaumeNury** [vlio20/angular-datepicker#167]
![bugdpdatepicker](https://user-images.githubusercontent.com/12662533/29208782-c28fb49c-7e8b-11e7-8de6-ebe5c3f32b89.gif)

Hello, I have a small but annoying bug with your datepicker : i cannot select the same month in another year.

**Comment by vlio20** [comment]
It's not looks like an inline component. Please put your template and configuration.

**Comment by GuillaumeNury** [comment]
Sorry i meant directive month picker

Here is my template :
```html
<form>
	<span>De</span>
	<md-input-container>
		<input
			mdInput
			name="fromDate"
			mode="month"
			[(ngModel)]="internalFromDate"
			(ngModelChange)="onDateChange()"
			[dpDayPicker]="datePickerConfig"
			theme="dp-material"
			attachTo=".mat-input-wrapper"
			required="required" />
	</md-input-container>
	<span>à</span>
	<md-input-container>
		<input
			mdInput
			name="toDate"
			mode="month"
			[(ngModel)]="internalToDate"
			(ngModelChange)="onDateChange()"
			[dpDayPicker]="datePickerConfig"
			theme="dp-material"
			attachTo=".mat-input-wrapper"
			required="required" />
	</md-input-container>
</form>
```
and my configuration :
```javascript
datePickerConfig = {
	format: 'MMM YYYY',
	min: moment('2014-01-01'),
	locale: 'fr',
} as IMonthCalendarConfig;
```

**Comment by vlio20** [comment]
Hi @GuillaumeNury I couldn't reproduce your issue :( 
![gif](https://media.giphy.com/media/xT39D0cfruei8vUqkg/giphy.gif)

On what version are you? (the gif taken on version 2.3.1).

**Comment by GuillaumeNury** [comment]
Hello, I'm using 2.2.0. I will try the new version tomorrow

**Comment by GuillaumeNury** [comment]
Hi, I think I found the issue !

In `month-calendar.component.ts`, in the `init()` method, you use:
```javascript
this.utilsService
        .getDefaultDisplayDate(this.currentDateView, this.selected, this.componentConfig.allowMultiSelect)
```

As a remember, here is the `getDefaultDisplayDate` method: 
```javascript
getDefaultDisplayDate(def: Moment, selected: Moment[], allowMultiSelect: boolean): Moment {
    if (def) {
      return def;
    } else if (allowMultiSelect) {
      if (selected && selected[selected.length]) {
        return selected[selected.length];
      }
    } else if (selected && selected[0]) {
      return selected[0];
    }

    return moment();
  }
```

As you do not `clone()` Moment object, I am in the case where `selected[0] === currentDateView`.
So, when I click on right nav, `onRightNav()` is called and when you do `this.currentDateView.add(1, 'year')`, `selected[0]` is updated as well !

I think you should use `clone()` in all cases in `getDefaultDisplayDate()`.

**Comment by vlio20** [comment]
@GuillaumeNury, did you try to update the version?

**Comment by GuillaumeNury** [comment]
Yes, the problem I pointed out was on the latest available version.

Here is a stackblitz that reproduce my problem : [HERE](https://stackblitz.com/edit/angular-datepicker-issue-167?file=app%2Fapp.component.html)

![angular-datepicker-167](https://user-images.githubusercontent.com/12662533/29765339-1893221e-8bdb-11e7-8971-688363a79f2b.gif)

**Comment by vlio20** [comment]
Awesome! I will try to reproduce on the demo page

**Comment by GuillaumeNury** [comment]
You need to initialize your component with a Date. In the demo, your datepicker is never populated on init.

In the `getDefaultDisplayDate` method of your `UtilsService`, I am in the following case: 
```javascript
else if (selected && selected[0]) {
  return selected[0];
}
```

**Comment by vlio20** [comment]
Do you want to submit a PR? it will be much faster

**Comment by GuillaumeNury** [comment]
Sure !

**Comment by vlio20** [comment]
awesome!
