### ISSUE TITLE
ChangeDetection OnPush support

### ISSUE THREAD

**Issue by GuillaumeNury** [vlio20/angular-datepicker#168]
Hello again,

Could you provide OnPush ChangeDetectionStrategy ?

**Comment by vlio20** [comment]
I am not sure what is OnPush ChangeDetectionStrategy. Can you please elaborate?

**Comment by GuillaumeNury** [comment]
Sure !

[Here is an example](https://stackblitz.com/edit/angular-datepicker-issue-168)

You can see two components `DefaultChangeDetectionComponent` and `OnPushChangeDetectionComponent`. They both have the same template.

`DefaultChangeDetectionComponent` is just a regular component and `OnPushChangeDetectionComponent` is the same component, but with Onpush change detection strategy.

```javascript
@Component({
  selector: 'on-push-change-detection',
  templateUrl: './template-example.html',
  styles: []
  changeDetection: ChangeDetectionStrategy.OnPush // <-- HERE
})
export class OnPushChangeDetectionComponent  { ... }
```

In the demo, you can see that, when you pick a date, your datepicker do not close itself in OnPush mode. I guess that you need to call `changeDetectorRef.markForChange()` in your component when you toggle the datepicker.

If your never heard of change detection strategy in Angular, it is such an interesting subject ! You can read this awesome [blog post](https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html).

**Comment by vlio20** [comment]
@GuillaumeNury, I read the blog (partly), I am a little afraid to add `changeDetectorRef.markForChange()` after toggling the picker - as it prou obably should be added in other places (right?).

Do you think other places should have `changeDetectorRef.markForChange()`?

**Comment by GuillaumeNury** [comment]
It is hard to say, but whenever you use a `setTimeout` and you update some properties, you need to call it.

For example, the `onDateClick()` method in `date-picker.component.ts` should call `changeDetectorRef.markForChange()` after calling `hideCalendar()`.

If you want, I can help you ! 😃

**Comment by vlio20** [comment]
PR would be much appreciated!
