### ISSUE TITLE
setting default time when timepicker appears

### ISSUE THREAD

**Issue by kirstenfrager** [vlio20/angular-datepicker#172]
Is there anyway to have a specific time set as the default for the time picker?
Currently the time before changing is 12:00 AM.
would like to have the option to setting a specific time instead of that one.
is this possible?

**Comment by vlio20** [comment]
You can do it by providing a date to the `Model`

**Comment by vlio20** [comment]
@kirstenfrager, did it help?

**Comment by kirstenfrager** [comment]
@vlio20 yes it did, thank you :)
