### ISSUE TITLE
console.log() in v2.3.1

### ISSUE THREAD

**Issue by amyrhsieh** [vlio20/angular-datepicker#174]
https://github.com/vlio20/angular-datepicker/blob/e918d377e6e7f996748803549fd40a3ea2d852e0/src/app/day-time-calendar/day-time-calendar.component.ts#L152

Please remove this console.log(); it is filling up my console every time I select a date. Thanks!

**Comment by vlio20** [comment]
Thanks! Do you want to PR?

**Comment by amyrhsieh** [comment]
Sure, to be clear, I should create a branch off of master with the fix, then create a PR for that branch?

**Comment by vlio20** [comment]
Correct

**Comment by amyrhsieh** [comment]
I created a local branch but do not have permission to push. Please give me access, thank you.

**Comment by vlio20** [comment]
You should fork and then create a new branch.

**Comment by amyrhsieh** [comment]
Thanks, I just did it. I had never done this before, it's good to learn!

**Comment by vlio20** [comment]
Awesome! Let me know if you need any help

**Comment by vlio20** [comment]
Thanks for the PR. 
Will be available in next release
