### ISSUE TITLE
Close on ios not firing

### ISSUE THREAD

**Issue by ld-gary** [vlio20/angular-datepicker#176]
Hey, thanks for this great solution to the lack of date/time pickers that play well with ng4!

Apologies if I'm missing something obvious here but I'm having an issue on ios. Basically the picker isn't closing when clicking (touching as it's ios) outside of the date picker, as happens in a desktop environment. It closes if I focus another input in the form, but not if I just want to escape the picker without moving on in the form.

Any suggestions as to why this might be happening?

**Comment by vlio20** [comment]
Does it reproduced on Safari? on what browser are you?

**Comment by ld-gary** [comment]
Both Chrome and Safari...

**Comment by vlio20** [comment]
I mean on desktop's Safari

**Comment by ld-gary** [comment]
No it's fine on desktop, fine on device emulation in chrome. Just actual mobile device is where I'm seeing the issue.

**Comment by vlio20** [comment]
mahhh, this one would be hard to test. Will need help with this one.

**Comment by ld-gary** [comment]
Ok no worries. I'm on a very tight deadline so may have to fudge some hacky solution for now but if I spot a fix in the package I'll hit you up. Thanks!

**Comment by ld-gary** [comment]
Hey, would it be possible to subscribe to open and close events for picker instances? My workaround involves introducing a close button on mobile but the logic gets pretty messy when catering for all platforms without a simple close event/state to subscribe to. This possible? I can't see anything currently to subscribe to.

**Comment by vlio20** [comment]
sounds plausible. Could you please open a different issue for that?

**Comment by vlio20** [comment]
@ld-gary, this is available in the newer versions. closing for now.
