### ISSUE TITLE
Validation for date format in reactive forms (Directive)

### ISSUE THREAD

**Issue by yaswanthpsl** [vlio20/angular-datepicker#177]
```
<input [dpDayPicker]="datePickerConfig"
                  name="endDate"
                  #dateDirectivePicker="dpDayPicker"
                  [theme]="material ? 'dp-material' : ''"
                  formControlName="endDate"
                  [placeholder]="'Select end date'"
                  (ngModelChange)="log($event)"
            />           <div *ngIf="endDate.invalid && (endDate.dirty || endDate.touched)">
              <div *ngIf="endDate.errors.required">
                End date is required
              </div>
              **<div *ngIf="endDate.errors.format"> // 1
                Please enter correct format
              </div>**
            </div>
```

1. Is there any validation to find if the format is correct?

**Comment by vlio20** [comment]
Honestly, I don't remember - I an on a vacation right now - will return back with an answer during next week

**Comment by vlio20** [comment]
Seems like there is no such validation. I will put it as a feature request.

**Comment by yaswanthpsl** [comment]
Thanks!

**Comment by vlio20** [comment]
@yaswanthpsl, this is now available in 2.5.0-beta
can you please assert that it is working as expected?

**Comment by vlio20** [comment]
@yaswanthpsl, any updates? I want to release 2.5.0

**Comment by yaswanthpsl** [comment]
@vlio20 Hey sorry for late response. It's working as expected. Thanks!

**Comment by vlio20** [comment]
Awesome!!!

Thanks!

**Comment by kumaresan-subramani** [comment]
can you please share one example with date min max validation?
@vlio20

**Comment by vlio20** [comment]
You can see how it done in the demo src code

**Comment by kumaresan-subramani** [comment]
@vlio20 , where is it?
demo src code?
i could not find?

**Comment by vlio20** [comment]
In this repo. Search for demo
