### ISSUE TITLE
[Feature Request] Insufficient height for calendar

### ISSUE THREAD

**Issue by WaterBleu** [vlio20/angular-datepicker#180]
The plugin works really well on a desktop.
However when navigating from a smaller screen (mobile phone) calendar gets cut off
so two solutions..
1. When event happens just pop up the calendar in dead center.
2. When event happens position the calendar that it is still relatively above/below the element but still within the bounding box

**Comment by vlio20** [comment]
Please share a screenshot.
Regarding your first suggestion. You could do it yourself with css.

**Comment by WaterBleu** [comment]
[Screenshot](http://imgur.com/a/rYVhm)

**Comment by vlio20** [comment]
As I mentioned before,  You should solve this issue in your own application css. 

Currently I don't want to add classes per platform.
