### ISSUE TITLE
ngModel produces a moment instance when field variable originally an empty string.

### ISSUE THREAD

**Issue by jalberto-ghub** [vlio20/angular-datepicker#181]
When the ngModel variable is originally a none empty string, and one provides format property in config, dp-date-picker returns a string as the new value. But if the ngModel is originally the empty string, dp-date-picker produces a moment instance when a date is selected.

Is there a way to specify one wants it to produce the formatted string date instead of a moment?

**Comment by vlio20** [comment]
When the initial value is an empty string, are you also providing a format?

**Comment by jalberto-ghub** [comment]
Yes, I am providing a format in the config. Here are the initialisation:

now: moment.Moment = moment();
  monthlyCfg = {format: 'YYYY-MM'}
  dobCfg = {
    format: 'YYYY-MM-DD',
    max: moment(this.now).subtract(18, 'years'),
    showMultipleYearsNavigation: true
  };

ngOnInit() {
    this.profile.personal.dob = this.dobCfg.max.format('YYYY-MM-DD');
    this.card.starts = '';
    this.card.expires = this.now.format('YYYY-MM');
  }

For card fields use the monthlyCfg. In the final card object after submission card.starts is a moment instance, but card.expires is a string, as expected.

This is how is being used:

For DOB:
        <div class="form-group">
          <label>Date of Birth</label>
          <dp-date-picker #dob="ngModel" name="dob"
                      [(ngModel)]="profile.personal.dob"
                      [config]="dobCfg" required></dp-date-picker>
          <small class="text-danger"
                [hidden]="dob.valid || (dob.pristine && !prf.submitted)">
                  <p><b>Date of Birth</b> is required</p>
          </small>
        </div>

For CARD:
        <div class="form-group">
          <label>Start Date (if present)</label>
          <dp-date-picker #start="ngModel"
                  name="start" [(ngModel)]="card.starts" mode="month"
                  [maxDate]="now" [config]="monthlyCfg"></dp-date-picker>
          <small class="text-danger"
                [hidden]="start.valid || (start.pristine && !crd.submitted)">
                  <p><b>Start Date</b> in format YYYY-MM</p>
          </small>
        </div>
        <div class="form-group">
          <label>Expiration Date</label>
          <dp-date-picker #exp="ngModel"
                  name="exp" [(ngModel)]="card.expires" mode="month"
                  [minDate]="now" [config]="monthlyCfg" required></dp-date-picker>
          <small class="text-danger"
                [hidden]="exp.valid || (exp.pristine && !crd.submitted)">
                  <p><b>Expiration Date</b> is required (format YYYY-MM)</p>
          </small>
        </div>

**Comment by jalberto-ghub** [comment]
It would be nice if there was a way to specify in the configuration whether one wants a moment or a string in the ngModel, rather than the picker guessing.

**Comment by vlio20** [comment]
So there is an edge case when you are providing an empty string then you are getting a moment object instead of string, correct?

**Comment by jalberto-ghub** [comment]
Yes, that is the case. In my case the field is optional, so it can be empty. I would have preferred for it to start as undefined, but then db-date-picker guessing strategy falls apart.

**Comment by RichardBoyder** [comment]
How do we format the moment if we have to get a moment back?

**Comment by vlio20** [comment]
The value that you are receiving is a Moment object. It has a method format: date.format('DD-MM-YYYY')

**Comment by RichardBoyder** [comment]
Would i put this on ngonInit in my component? i have referenced a variable as a moment:

import { Moment } from 'moment';


export class FuneralQuoteComponent implements OnInit {
 myMoment: Moment;

Sorry im a newby with angular and moment. So how do we set a global format for moment and any plugin like date picker to use the global format we want throught the app?

**Comment by vlio20** [comment]
There is no global format. You would have to apply the format on every change of the date. You could use the on change callback.

**Comment by RichardBoyder** [comment]
ok ill do some googling. thankyou for the help.

**Comment by RichardBoyder** [comment]
I’m having a hard time changing it. The value is a item in a form control array. Do you know how to change the format when a moment is in a form array?

**Comment by vlio20** [comment]
do you have multiple values? if so, you will have to loop through the array and make the conversion.
```
datas.map(d => d.format('DD-MM-YYYY'))
```

**Comment by RichardBoyder** [comment]
ok let me give it a shot.

**Comment by RichardBoyder** [comment]
is there any way i can add a value property to get the value directly from the date picker into a variable then easier for me to work with so i can patch the variable to the item in the array? 

for example doing:

<dp-date-picker [theme]="'dp-material'"  [value]="DOBTEST" ></dp-date-picker>

i am battling to loop through the array.

**Comment by vlio20** [comment]
sure, you should provide ngModel

**Comment by RichardBoyder** [comment]
Interesting I add model with empty date type .. and date is correct . Seems to ignore moment now 👍👍👍👍

**Comment by RichardBoyder** [comment]
ok it works but not when i add a ngModel, it puts invalid date in the input when the page loads... however when i select date it puts it in correctly...

**Comment by RichardBoyder** [comment]
all good sorted... i did the following:
so it starts with todays date:

[(ngModel)]="DOBTEST"

 DOBTEST = moment().format('YYYY-MM-DD');

all good now. Doesnt display place holder but this is second best.

**Comment by vlio20** [comment]
resolved in aaecbf7ca1c38625a1c047fbe74e0430eeb5ba77 - will be available in 2.5.0 version. There is an option to add `returnedTypeValue`
