### ISSUE TITLE
Setting the configuration for dpDayPicker

### ISSUE THREAD

**Issue by ninethug** [vlio20/angular-datepicker#182]
Hi,
First, thank you for this work, that's the best date picker i found for angular 👍 

I don't know if that's an issue or I juste don't know how to use it. 
Here is my code : 
`<input name="selectedDate" [(ngModel)]="selectedDate" mode="daytime" [dpDayPicker]="config" theme="dp-material" />`
and the configuration in my component is : 
`config = {
    hours24Format: 'false',
    firstDayOfWeek: 'mo',
    locale: 'fr'
  };`

The configuration works great except hours24Format which allows 24 format event if it's set to false. I have the same problem with showSeconds when set to false and closeOnSelect when set to true.

**Comment by vlio20** [comment]
Can you create some StackBlitz for that? https://stackblitz.com/edit/angular-mpajro

**Comment by ninethug** [comment]
Here : [https://stackblitz.com/edit/angular-cfynma]

**Comment by vlio20** [comment]
1. close on select is not suppose to work in day-time-picker - it doesn't make sense in this case. regarding the format - I am taking a look

**Comment by ninethug** [comment]
I see, maybe documentation needs to be up to date.
However, other options are not working.

**Comment by vlio20** [comment]
you should use `showTwentyFourHours: false` in order to disable it. https://stackblitz.com/edit/angular-piggrw

as you can see there is also no seconds in the time picker

**Comment by ninethug** [comment]
I see, so the configuration is only dot the date time picker, it will be useful to have the same in the input.
For example if showSeconds is false, the input should be in 'dd-MM-yyyy HH:mm' format. Maybe a new feature ?
Thank you

**Comment by vlio20** [comment]
You can have the input to be in any format as you like:
https://stackblitz.com/edit/angular-3buyok
