### ISSUE TITLE
accessing the CSS for calendar border

### ISSUE THREAD

**Issue by kirstenfrager** [vlio20/angular-datepicker#183]
Hello,

How do I access the CSS for the actual border of the calendar?
I thought I was accessing it correctly (reflects changes I made in localhost) but after I build the CSS property disappears.
I am accessing it through: dp-material[_nghost-c2] .dp-calendar-wrapper[_ngcontent-c2]
which I know isn't the correct way. But can't seem to find a class for it.

**Comment by vlio20** [comment]
The current solution is to use !important. Let me know if it works.

**Comment by nileshbhagwat** [comment]
@kirstenfrager if you are using style encapsulation then you may want to take a look at 
:host /deep/ (before 4.3)
:host ::ng-deep (4.3 onwards)

**Comment by vlio20** [comment]
closing for now
