### ISSUE TITLE
Changing minutesInterval after init does no work.

### ISSUE THREAD

**Issue by T3Alc** [vlio20/angular-datepicker#185]
Timepicker 
Setting `config: IDatePickerDirectiveConfig = { minutesInterval: 5 };` works fine, but if I want to change that value during run-time, picker uses old settings. While number itself changes in config var correctly.

**Comment by vlio20** [comment]
I will take a look, as a workaround I suggest to do a small hack and re-render the component.

**Comment by T3Alc** [comment]
Thanks for suggestion. I didn't mention that I was using `[dpDayPicker]` directive.

**Comment by vlio20** [comment]
@T3Alc, in order to make it work you will have to pass a new reference to the configuration object:
```
this.config = {...this.config, minutesInterval: 5}
```

this will make the component take in to consideration the new configuration.
