### ISSUE TITLE
[Feature Request] hide/show inline calendar

### ISSUE THREAD

**Issue by WaterBleu** [vlio20/angular-datepicker#186]
Due to dialog resizing issue I would like to request for
onClick input to show calendar and onselectdate to hide it.

**Comment by vlio20** [comment]
Can you please elaborate, I am not sure I am following your request

**Comment by WaterBleu** [comment]
basically on inline calendar.
when clicking on input shows the inline calendar
when onSelect would hide the inline calendar
or a trigger for the *ngIf denoting the state of the calendar

**Comment by vlio20** [comment]
if this is an inline component you can use you own logic and hide/show it with `*ngIf` or `[hidden]`

**Comment by WaterBleu** [comment]
right but I have no idea when the calendar button is clicked.
meaning I cannot add action to it

**Comment by vlio20** [comment]
why wouldn't you use the directive? why are you trying to implement input with an inline component?
