### ISSUE TITLE
Option to disable Array of dates.

### ISSUE THREAD

**Issue by sgavinolla001** [vlio20/angular-datepicker#187]
Hi 

Do we have any option to disable array of random dates here.

Thanks

**Comment by vlio20** [comment]
I am not sure I understand, can you please elaborate?

**Comment by sgavinolla001** [comment]
I have a requirement to enable random dates.. not in a interval of dates
I'll be passing some list of dates and those should be enabled and others should be disabled.
The dates are not in a range or interval, they are random.

**Comment by vlio20** [comment]
does `isDayDisabledCallback` helps you? please read about in the docs

**Comment by sgavinolla001** [comment]
Actually  I am having an array of dates and have to enable only those, this
I can't be doing with the disablecallback.

*Thanks & Regards*

*Srikanth Reddy.G*
*MangoApps Inc*
*Ph:9963333368*
*Email:srikanthgovinolla@gmail.com <Email%3Asrikanthgovinolla@gmail.com>*

**Comment by vlio20** [comment]
I think you can. The callback called for each date in the calendar, so if you callback returns true or will be disabled. This way you can check if that date is present in the list of random dates you have.

**Comment by carlos09** [comment]
@sgavinolla001 Were you able to do this using the disable callback function? do you have an example if you were able to achieve this?
