### ISSUE TITLE
Today radio button still active when "today" is out of range.

### ISSUE THREAD

**Issue by jalberto-ghub** [vlio20/angular-datepicker#189]
When the date-picker is configured with min/max values that exclude "today". The radio button still allows one to move the calendar outside the valid range.

Either the radio button should be disabled, or only move as far as the min/max values allow, or maybe if displayDate is set to a value in range, then go to that date.

In the following picture displayDate == config.max == (now - 18 years) however one is able to move the calendar to the following illegal position.

![image](https://user-images.githubusercontent.com/13122536/30243624-dbed409a-95a5-11e7-889a-65b398fb602b.png)

**Comment by vlio20** [comment]
That makes sense. I will apply add this to next release.

**Comment by vlio20** [comment]
@jalberto-ghub, would you like to submit a PR?
