### ISSUE TITLE
[New feature] Show a message when hover

### ISSUE THREAD

**Issue by ninethug** [vlio20/angular-datepicker#190]
Hi,
Do you think that it's possible to show a message when the mouse hover a particular date, maybe on the inline calendar ?

**Comment by vlio20** [comment]
This is a very specific request, as different users might want  a different behaviour.
What do you thing if I will provide you with a callback when users hovers on date? what data would you want to receive?

**Comment by ninethug** [comment]
I'm new in angular and don't master well yet. Callbacks are little bit abstract to me. But basically, I need to show how many events are organized for one day when hovering it.
For example if a user hover the 10th of october, he has to see a little floating message saying 10 events.
Here is an example : 
![image](https://user-images.githubusercontent.com/5955496/30278447-a9d94110-970a-11e7-8219-f8e9cd2df15f.png)

**Comment by vlio20** [comment]
Again, adding a tooltip to this component is something that I don't to do. What is possible is to provide a notification (transmit event) when item is being hovered

**Comment by ninethug** [comment]
I'll try to modify the source code by myself to get what i need when the mouse is on a date.
Thank you anyway.
