### ISSUE TITLE
Trigger after dropdown is closed

### ISSUE THREAD

**Issue by jphearse** [vlio20/angular-datepicker#191]
I want to trigger a function after the user has selected a date/time and has closed the dropdown. What is the best way to do this? I am currently using (blur)="function()", but this gets called every time I click a date or arrow through the time.

**Comment by vlio20** [comment]
do you want to trigger it on select or on close?

**Comment by jphearse** [comment]
Preferably on close.

**Comment by WaterBleu** [comment]
yeah this would be nice. I think I was using ngModelChange and that lead to a unpleasant result

**Comment by vlio20** [comment]
Please see https://github.com/vlio20/angular-datepicker/issues/178, it will be released in the next few days.
