### ISSUE TITLE
Which are the correct parameters that need the picker's constructor?

### ISSUE THREAD

**Issue by McB0y** [vlio20/angular-datepicker#192]
First I wanna say thanks for share this wonder component!

Well I try to use the component as a month picker and I'm setting some properties without any problem, but If I use the component with a *ngIf directive I cannot manipulate the picker because appears an error message on my console like this: 
'TypeError: Cannot set property 'theme' of undefined'

I guess this ocurs because I haven't any instance of my month picker, but the next code inside my constructor(){} it ain't works:

this.datePicker = new DatePickerComponent();

Please help

**Comment by vlio20** [comment]
please create a demo or even better stackblitz

**Comment by McB0y** [comment]
@vlio20  thanks! 

https://stackblitz.com/edit/angular-2xssfs

**Comment by vlio20** [comment]
you are not providing the configuration to the component:
```
<dp-date-picker
        #dayPicker
        [(ngModel)]="selectedDate"
        (ngModelChange)="showCurrentMonth($event)">
        </dp-date-picker>
```

So I am not sure what is the problem

**Comment by McB0y** [comment]
Sorry I was trying avoid the creation of a object configuration whith this:

            this.datePicker.theme = 'dp-material';
            this.datePicker.mode = 'month';
            this.datePicker.placeholder = 'Sep-17';

But now I' m mindful how it works.

Thank's a lot for your time and again for share this component :)

**Comment by vlio20** [comment]
I am glad to help! Stat would be much appreciated!
