### ISSUE TITLE
Custom CSS classes in a callback 

### ISSUE THREAD

**Issue by jak** [vlio20/angular-datepicker#193]
Much like dayBtnFormatter and related options, I think it would be useful to have a callback for defining custom CSS classes depending on the button.

Proposed option is `dayBtnCssClass` and `monthBtnCssClass`, with signature `(day: Moment) => string` where the resultant string is added to the `ngClass` on the button.

Would you be open to a PR for this feature?

**Comment by vlio20** [comment]
Sounds like a nice feature.
Sure, I would be happy for PR.
Could you please elaborate on how you are planning to implement it?

**Comment by jak** [comment]
I'm probably going to follow the `btnTextFormatter` as an example where possible. As the [component html currently places the classes in place](https://github.com/vlio20/angular-datepicker/blob/master/src/app/day-calendar/day-calendar.component.html#L28-L34) and I'll need to add a key to the object, I'll creating the object it into the component class instead.
