### ISSUE TITLE
Cannot include ng2-date-picker in a plunker

### ISSUE THREAD

**Issue by amr-alamir** [vlio20/angular-datepicker#197]
I tried to include **ng2-date-picker** in [this **plunker**](https://plnkr.co/edit/Wwj8djdo7rJyemJMllFu?p=preview) via **systemjs** as follows:
```javascript
  map: {
    //
    //  default angular packages
    //
    'ng2-date-picker': 'npm:ng2-date-picker/date-picker.module',
  },
```
but I got the following Errors:

```
GET https://run.plnkr.co/ACCosHqcWuVeBxLY/moment 404 ()
Error: (SystemJS) Error: XHR error (404) loading https://run.plnkr.co/ACCosHqcWuVeBxLY/moment
Error loading https://run.plnkr.co/ACCosHqcWuVeBxLY/moment as "moment" from
    https://unpkg.com/ng2-date-picker/common/services/utils/utils.service
```
![image](https://user-images.githubusercontent.com/17075151/30578980-de04f2c4-9d16-11e7-88e7-b10ea6e46945.png)

it seems that **utils.service** couldn't load **moment.js**

how to include the package in a plunker?

**Comment by vlio20** [comment]
not sure, you will have to add moment as well probablty

**Comment by WaterBleu** [comment]
was able to do it in #200

**Comment by amr-alamir** [comment]
@WaterBleu @vlio20  thank you this fixed the issue
