### ISSUE TITLE
Setting firstDayOfWeek to 'st' hangs the page eating all processor

### ISSUE THREAD

**Issue by amr-alamir** [vlio20/angular-datepicker#201]
In [**this plunker**](https://plnkr.co/edit/Wwj8djdo7rJyemJMllFu?p=info) I used [dpDayPicker] **directive**, and when I try to set **`firstDayOfWeek `** configuration, the page hanges with 100% processor (actually 25% in 4 cores).

I removed [ngModel] for simplicity.

**Comment by vlio20** [comment]
Does it happens in the component as well?

**Comment by amr-alamir** [comment]
yes, I change d to component and yes, same result

**Comment by vlio20** [comment]
Without changing the default first day of the week, does it still happen?

**Comment by amr-alamir** [comment]
I tried different values, and this is the behavior:
- No problem with all values `'su', 'mo', 'tu', 'we', 'th', 'fr'`  and including `'sa'`
- Only value `'st'` gives the problem
- In my local machine, when using `'sa'`, I get typescript error `Type '"sa"' is not assignable to type 'WeekDays'.` so I had to use `'st'`, which gives the problem

**Comment by vlio20** [comment]
@amr-alamir, do you want to submit a PR?

**Comment by amr-alamir** [comment]
ok, I'll try

**Comment by amr-alamir** [comment]
In my local development machine, I modified the file `/src/app/common/types/week-days.type.ts`  and changed `'st'` to `'sa'`, and this worked fine and resolved the issue locally.
I submitted the PR (my first PR actually), notify me if there is something wrong
