### ISSUE TITLE
[Feature Request] onSelect output on day-time-calendar

### ISSUE THREAD

**Issue by WaterBleu** [vlio20/angular-datepicker#202]
was using onChange for triggering closing dialog (md-dialog), but on switching the time would trigger the dialog to close resulting in unable to switching to the required time.

**Comment by vlio20** [comment]
Could you use the `close` output?

**Comment by WaterBleu** [comment]
I was not able to use the `close` output.
this is a inline day-time-calendar by the way

**Comment by vlio20** [comment]
mmm... I don't want to make specific events for time/date/month/year change. I would suggest you to see the diff between the changed date and the previous one - and in this way determine what exactly was changed. 

Also, why are you trying to implement your own picker where you can use the one provided with this lib?
