### ISSUE TITLE
Duplicate days with moment-timezone.

### ISSUE THREAD

**Issue by nathanmarks** [vlio20/angular-datepicker#205]
I am using [moment-timezone](https://momentjs.com/timezone/) in my application, and when I set the default timezone for moment as so in my application:

```
import * as moment from 'moment-timezone';

moment.tz.setDefault('America/Santiago');
```

it's causing an issue with the date picker resulting in duplicate days:

![image](https://user-images.githubusercontent.com/4420103/30768925-69963906-9fdd-11e7-8da5-0a0a302b1925.png)

Notice there are two days that both claim to be 12th of august.

**Comment by vlio20** [comment]
Holly crap! I will take a look!

Could you share more screen shots of your implementation? It looks awesome!
