### ISSUE TITLE
[New feature] Change days name

### ISSUE THREAD

**Issue by ninethug** [vlio20/angular-datepicker#206]
Hi,

Is there a way to change the name of days ? Put for example only the first letter ?

**Comment by vlio20** [comment]
please try `weekDayFormat` - looks like I forgot to add this to the docs.

**Comment by vlio20** [comment]
let me know if it helps

**Comment by ninethug** [comment]
It seems there is a bug, It renders a number when I set it to 'd' but works fine if I set it to 'dd'

**Comment by vlio20** [comment]
it's not a bug, this is the format, according to MomentJS.

**Comment by ninethug** [comment]
Ok, is there a way to make it show only a letter ?

**Comment by vlio20** [comment]
Not, it doesn't make sense to show only one letter, Sunday and Saturday both starts with S

**Comment by ninethug** [comment]
It does in some other languages

**Comment by vlio20** [comment]
I will add a formatter, callback method.

**Comment by vlio20** [comment]
@ninethug  Please open a different issue for that!

**Comment by ninethug** [comment]
Hi vlio,

Thank you for the update, I was waiting for it ! However, I've never used callbacks yet as I'm new to it. Could you give me an example of using it please ?
My apologises for beginners questions

**Comment by vlio20** [comment]
Sure:
config: {
   weekDayFormatter: (dayIndex: number) => {
      // return you string according to index
   }
}

Please note that this is still not available via npm

**Comment by vlio20** [comment]
your ⭐️ would be much appriciated

**Comment by ninethug** [comment]
Already done a long time ago 👍
