### ISSUE TITLE
production build gives an error

### ISSUE THREAD

**Issue by bun-enoikio** [vlio20/angular-datepicker#208]
Hi,
Production build gives me the following error:
 'DpDatePickerModule' is not exported by node_modules/ng2-date-picker/date-picker.module.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
dist/src/date-picker/date-picker.module.js (4:9)
import { CommonModule } from '@angular/common';
import { DpDatePickerModule } from 'ng2-date-picker';
            ^
var DatePickerModule = (function () {
  function DatePickerModule() {
.....
....

-Bun

**Comment by vlio20** [comment]
Are you using angular-cli?
please provide some demo project.

**Comment by vlio20** [comment]
closing for now
