### ISSUE TITLE
Set initial value, how?

### ISSUE THREAD

**Issue by lenpino** [vlio20/angular-datepicker#210]
I see no way to set the initial value (date). I tried setting the string and it shows in the input field, but when I open the calendar the date is still today.

Is there a way to pre populate the calendar with values from the server for example?

Thanks in advance

**Comment by vlio20** [comment]
please provide a stackblitz

**Comment by lenpino** [comment]
The files are:
https://stackblitz.com/edit/angular-yrr1bg?embed=1&file=app/auth/useredit/useredit.component.ts
https://stackblitz.com/edit/angular-yrr1bg?embed=1&file=app/auth/useredit/useredit.component.html

The problem is that even though I can see the date (18-09-1970) on the field when the template loads, when I click to open the calendar, it opens on today's date. I want it to open on 18-09-1970

Thanks

**Comment by vlio20** [comment]
you can find `displayDate` in the documentation - I think it is exactly what you need.
Let me know if it solves your issue.

**Comment by lenpino** [comment]
Yes, that was it... thank you!!
