### ISSUE TITLE
Style problem

### ISSUE THREAD

**Issue by agustin18** [vlio20/angular-datepicker#211]
First of all, sorry for my english.

I have a problem, i dont know probably because I'm a beginner. But I have a problem with style when applying this component, I just followed the "getting started" github. I show you a preview of what my component looks. Any idea how I can make it look better? Thank you very much

[https://image.prntscr.com/image/Fuoj16v8QtqLNkZaEi6EmQ.png](https://image.prntscr.com/image/Fuoj16v8QtqLNkZaEi6EmQ.png)

And  to select more than one date on calendar for several months it's just a matter of adding something else to the html component?
@vlio20

**Comment by vlio20** [comment]
the link is dead.

**Comment by agustin18** [comment]
Sorry i upload again

[https://image.ibb.co/niRmFb/Screenshot_50.png](url)

@vlio20 

Thank you

**Comment by vlio20** [comment]
you need to set the theme to be: `dp-material" you can find full example in the docs.

**Comment by rrohitesh** [comment]
@agustin18 did you got your solution?

**Comment by ezequiel88** [comment]
Not working 'dp-material'.
