### ISSUE TITLE
Possible to create a Year Picker? 

### ISSUE THREAD

**Issue by joakimgk** [vlio20/angular-datepicker#212]
Thanks for a great picker component! I've been looking for one with different levels, and your Month Picker is perfect. However, I'd also need a Year Picker. Is that easy to extend?

**Comment by vlio20** [comment]
nope, you can use: `showMultipleYearsNavigation`  &  `multipleYearsNavigateBy`

**Comment by joakimgk** [comment]
But, the point is to be able to display a picker which shows, say, a 3x4 matrix of years:

` <                           >`
`2017 2018 2019 2020`
`2021 2022 2023 2024`
`2025 2026 2027 2028`

 Setting the options you're suggesting, we're still seeing a _month_ picker. I need a component where the user can click and select 2019, for example. Not some month in 2019, just the year.

**Comment by vlio20** [comment]
@joakimgk, I understand your requirement, but I don't want currently change the current implementation. 

Do you want to PR? if so, we can add an option to choose between the 2 implementations.
