### ISSUE TITLE
Disable dates

### ISSUE THREAD

**Issue by carlos09** [vlio20/angular-datepicker#219]
Hello,
I am trying to figure out a way so to disable certain days out of the.  I was able to get the isDayDisabledCallback working, kind of, but not sure how to match up/compare dates. For example, if i have an array of dates that i would like disabled, how do "add" those in to be disabled?

Thanks!

**Comment by vlio20** [comment]
I would convert this array to a Set, then on callback I  would check if the callback date exists in this set.

Please let me know if you need any help.

**Comment by cedricve** [comment]
@vlio20 I would like to have something similar, using min and max properties is not enough for my use case. Any ideas? 👍

**Comment by vlio20** [comment]
Please use isDayDisabledCallback

**Comment by cedricve** [comment]
thanks @vlio20, just curious about the  implementation, if I pass an arrow function with one attribute it stays null.

**Comment by vlio20** [comment]
@cedricve, if you will post a stackblitz I will be more than happy to help

**Comment by cedricve** [comment]
hey @vlio20 not that much to display, I simply pass above parameter to the config.

**Comment by vlio20** [comment]
It would be helpful if you could create a demo with the error u r getting.
