### ISSUE TITLE
Form control name Value

### ISSUE THREAD

**Issue by RichardBoyder** [vlio20/angular-datepicker#220]
The config "year month day" works perfectly for the input , but when i see the date added to the FormControl , the format shows : Tue Oct 17 2017 00:00:00 GMT+0200

How do i change the actual format of date that gets inserted to the form control ? in reactive forms.

is there a config i can do?

thanks for a awesome date picker.....

**Comment by RichardBoyder** [comment]
Anyone able to help?

**Comment by vlio20** [comment]
Hi @RichardBoyder. Please provide a stackblitz demo. It would be much easier to help you.

**Comment by RichardBoyder** [comment]
Thankyou I will do so .

**Comment by RichardBoyder** [comment]
Basically. When after selecting a date it shows correctly .
<img width="174" alt="screen shot 2017-10-08 at 15 58 34" src="https://user-images.githubusercontent.com/16017411/31317456-b55d9954-ac41-11e7-98ff-69f100ed4c70.png">

but when i write it to page, im using reactive form it appears like this:
<img width="146" alt="screen shot 2017-10-08 at 15 58 45" src="https://user-images.githubusercontent.com/16017411/31317468-d356cb88-ac41-11e7-9e41-916b493a667e.png">

Console log shows : 
<img width="404" alt="screen shot 2017-10-08 at 16 01 31" src="https://user-images.githubusercontent.com/16017411/31317481-0dc3ff52-ac42-11e7-8efe-18b0aa652f47.png">

However i want the value that i got added and not use Moment as you can see above. I basically want it to show the same as the value in "CoverAmount" , meaning not showing "Moment" but the same value as i got after choosing a date....

**Comment by RichardBoyder** [comment]
this is my line:
<dp-date-picker [theme]="'dp-material'"  [config]="DateInputConfig" placeholder="Date of Birth" formControlName="spouseDateOfBirth" ></dp-date-picker>

**Comment by RichardBoyder** [comment]
Sorry its a whole project i cant place it in blitz. But its just the functioning of when the value gets put into the formControl that it changes from the simple formated date to the long date. So i just wonder why it does use the config format : DateInputConfig = {format: 'YYYY-MM-DD', appendTo: 'body'};
To insert the exact same format into my formcontrol... why does it change to "Moment" object

**Comment by vlio20** [comment]
What is your initial data?

**Comment by RichardBoyder** [comment]
I am inputing the data straight from the date picker , default settings , no additions, and using that format set up in the config. Nothing else. When I pick a date it adds it to the view exactly as I want it but the binding to the form control changes in the back ground to use a different date format. However I don’t have any control over that. 

So this is just a normal date field with no extra data input ...

**Comment by RichardBoyder** [comment]
im getting this: 
<img width="348" alt="screen shot 2017-10-08 at 17 43 00" src="https://user-images.githubusercontent.com/16017411/31318301-3f1f87ca-ac50-11e7-8074-79082468ec11.png">

when i actually want to get a format more like:

{spouseDateOfBirth:'11-22-1980'} 

So it displays it correctly in the page... but that spouseDateOfBirth form control it shows a complicated full date and time....

**Comment by vlio20** [comment]
This is the reason, currently, when you not providing an initial value the value you will get in return is a Moment object. The format applies to the format seen in the input.

This is the same issue that was reported earlier.

As a workaround, you could format the moment object to any format that you want. I encourage you to read the Moments documentation. It is very simple.

Let me know if you have any questions.

**Comment by RichardBoyder** [comment]
Oh right that makes sense, sorry i didnt see the other issue, yes its the same issue.. Im a bit new to formating the moment object... since its handled inside the datepicker... where would i set the format of the moment ?

**Comment by alanent** [comment]
https://stackoverflow.com/questions/50947642/angular-material-6-datepicker-reactive-form 
Can you help me please ?
