### ISSUE TITLE
Unable to make this work

### ISSUE THREAD

**Issue by keshav1007** [vlio20/angular-datepicker#221]
Hi,

1. Installed : npm install ng2-date-picker --save
2. Imported : import {DpDatePickerModule} from 'ng2-date-picker'; in my app.modules
3. Added into my imports : Add DpDatePickerModule to your module imports

<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig"></dp-date-picker>

My component has : 

selectedDate = new Date();

datePickerConfig = {
firstDayOfWeek: 'su',
            monthFormat: 'MMM, YYYY',
            disableKeypress: false,
            allowMultiSelect: false,
            closeOnSelect: undefined,
            closeOnSelectDelay: 100,
            onOpenDelay: 0,
            weekDayFormat: 'ddd',
            drops: 'down',
            opens: 'right',
            showNearMonthDays: true,
            showWeekNumbers: false,
            enableMonthSelector: true,
            yearFormat: 'YYYY',
            dayBtnFormat: 'DD',
            monthBtnFormat: 'MMM',
            hours12Format: 'hh',
            hours24Format: 'HH',
            meridiemFormat: 'A',
            minutesFormat: 'mm',
            minutesInterval: 1,
            secondsFormat: 'ss',
            secondsInterval: 1,
            showSeconds: false,
            showTwentyFourHours: false,
            timeSeparator: ':',
            multipleYearsNavigateBy: 10,
            showMultipleYearsNavigation: false,
            locale: 'en',
            hideInputContainer: false
}

4. After adding this in HTML got the following error : No value accessor for form control with unspecified name attribute

5. After googling added ngDefaultControl in the HTML like below:
<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig" ngDefaultControl></dp-date-picker>

6. Errors are gone but the date picker is not coming in the HTML.

What am i missing? I installed moment also. Please add plunkr on how to get this work if possible.

**Comment by vlio20** [comment]
First, selected date shouldn't be an instance of Date. Currently only string and moment types are supported.

Second, please provide a stackblitz, would be much easier

**Comment by keshav1007** [comment]
Changed selectedDate as '2017-09-01' - but still datepicker is not coming in the HTML. I am not aware of stackblitz :)

**Comment by vlio20** [comment]
Google it :)

**Comment by keshav1007** [comment]
Got it.. thanks for introducing stackblitz. Issue was with my app.module. imported DpDatePickerModule into my common modules and it worked. Thanks for the awesome date picker 👍

**Comment by vlio20** [comment]
u r welcome!
you ⭐️  would be much appreciated
