### ISSUE TITLE
Always need the date picker to drop down

### ISSUE THREAD

**Issue by keshav1007** [vlio20/angular-datepicker#222]
Hi,

I always need the date picker to drop down and don't want to change the direction based on the space available.

I have created here : https://stackblitz.com/edit/angular-q4ryeb
I have given the drops as 'down' but still it comes on top(because of less space in the bottom). But i will be having a scrollable div in my application so that i need all datepickers to drop down not on top.

How can i achieve this?

**Comment by vlio20** [comment]
I will check it as soon as I will have time, from your description seems like a bug.

**Comment by priyanka3110** [comment]
Same issue I always wanted to make drop down appear at bottom

**Comment by vlio20** [comment]
This one is on my list to the next release 2.5.0 or 2.5.1

**Comment by vlio20** [comment]
Resolved in c26d168
