### ISSUE TITLE
More than one picker can be opened at the same time

### ISSUE THREAD

**Issue by keshav1007** [vlio20/angular-datepicker#223]
Hi,

I am able to open more than one date picker at the same time. I want to open only one date picker at a time.

stackblitz : https://stackblitz.com/edit/angular-yg84jc?file=app%2Fapp.component.html

![image](https://user-images.githubusercontent.com/20353796/31325397-2dcfed90-acda-11e7-9c76-bbdf0397510f.png)

how can i avoid this?

**Comment by vlio20** [comment]
seems like it is happening only when clicking on the right side of the input. Probably because of the focus on current day button. I will take a look as soon as I can.

As a workaround I suggest you to disable this button if it is not required in your case.

**Comment by vlio20** [comment]
Resolved in dd283c5
