### ISSUE TITLE
disableKeypress not working for mode='month'

### ISSUE THREAD

**Issue by keshav1007** [vlio20/angular-datepicker#225]
Hi,

I have set true for disableKeypress and still i am able to edit the input field by key press. This happens only when i set the mode to 'month'.

stackblitz: https://stackblitz.com/edit/angular-yg84jc?file=app%2Fapp.component.html

**Comment by vlio20** [comment]
does it happens in the demo page as well?

**Comment by keshav1007** [comment]
yes. It happens in demo page as well

**Comment by vlio20** [comment]
thanks, will take a look as soon as i can.
Feel free to PR

**Comment by vlio20** [comment]
@keshav1007, note that it happens for all directives
