### ISSUE TITLE
[Feature Request] Change hardcoded locale 'en' in default config to use current moment locale

### ISSUE THREAD

**Issue by eivindr** [vlio20/angular-datepicker#228]
We are setting the moment locale at app init (based on user config) and using moment.js in other parts of the app. But when a datepicker component is included the moment locale is changed to 'en'. This affects all other parts of the system using moment. I know we could define the locale for each datepicker instance, but we want to avoid this.

So what do you think about changing `locale: 'en'` to `locale: moment.locale()` in all the default config definitions?

**Comment by vlio20** [comment]
I need to check into `moment.locale()`. However I wouldn't want the users to use something different than passing a string

**Comment by eivindr** [comment]
Thanks, as I understand it the default locale in moment is 'en'. `moment.locale()` will return the current locale id as string. They are working on a "default" id that will auto detect the browser locale. But it needs to be manually called, so I think it will be safe to use `moment.locale()` also in the future for 'en' users.
Correct me if I'm wrong.

**Comment by vlio20** [comment]
let's say that I will change the default from `en` to `moment.locale()` will it work for you?

**Comment by eivindr** [comment]
Yes, that would be great!

**Comment by vlio20** [comment]
resolved in dd283c5
