### ISSUE TITLE
Event problem get dates

### ISSUE THREAD

**Issue by agustin18** [vlio20/angular-datepicker#229]
Hello.

Thank you for all your work, sorry for my poor level, but I think I read all the documentation and can't get  the dates I select on the calendar.

I want to select a group of dates and get them with an event. I know I should do it with onchanges. But could you provide me with a minimum code of how I should make that part of code in my. ts file.

on my html page I have this code
```
<dp-day-calendar 
            [(ngModel)]="selectedDate" 
            [config]="config"
            name="dayCalendar"
            #dayCalendar="ngModel"
            [theme]="material ? 'dp-material' : ''"
            (ngModelChange)="holiday($event)"
            [minDate]="validationMinDate"
            [maxDate]="validationMaxDate"
            [required]="required">

        </dp-day-calendar>
```

and on my. ts page I have this empty

```
holiday(event: CalendarValue){
        var holidays = {
         .....
         .....
        }
        
      }
```

 could you help me?

Thank you very much

**Comment by vlio20** [comment]
I would be happy to help. Please provide a stackblitz. Please use the 2.5.0-beta version.

**Comment by agustin18** [comment]
Thank you

but the code is the same that i put on the first message.

Here 

https://stackblitz.com/edit/angular-ypvqlv

thank you, is the portion of code of calendar.

**Comment by vlio20** [comment]
Next time plz provide a working dir:
https://stackblitz.com/edit/angular-p2p6vg

**Comment by agustin18** [comment]
@vlio20 I thought, showing you the part of the code where datepicker intervenes, you might understand what he was saying. But the code running of the whole project is difficult because I have to ask for authorizations.

What I was asking is how do I get the days that are selected in the calendar with an event. The html structure is here with the onchange event 

```
<dp-day-calendar 
            [(ngModel)]="selectedDate" 
            [config]="config"
            name="dayCalendar"
            #dayCalendar="ngModel"
            [theme]="material ? 'dp-material' : ''"
            (ngModelChange)="holiday($event)"
            [minDate]="validationMinDate"
            [maxDate]="validationMaxDate"
            [required]="required">

        </dp-day-calendar>
```

but in my. ts code what i have to specify, i want to get the days that i select on the calendar, i want to know day and month.


```
holiday(event: CalendarValue){
        var holidays = {
       day: event. (here how i get the day)
       month: event. (here how i get the month)
        }
        
      }
```
Sorry I couldn't be more cooperative.

**Comment by vlio20** [comment]
please see this stackblitz, it has a working demo: https://stackblitz.com/edit/angular-p2p6vg

**Comment by agustin18** [comment]
Thank you so much.

**Comment by vlio20** [comment]
a ⭐️ would be much appreciated.

Note that the version in the the demo is 2.5.0-beta, but it also should work on 2.4.0 - stay tuned for 2.5.0

**Comment by agustin18** [comment]
Thanks a lot, sorry for my poor level.

**Comment by vlio20** [comment]
we all were there, learning takes it's time
