### ISSUE TITLE
customise date picker size height/width

### ISSUE THREAD

**Issue by kirstenfrager** [vlio20/angular-datepicker#234]
Am trying to change the height and width of the calendar date picker.
i am able to access the css elements individually but it comes out very buggy on devices and is not uniform across (can't make it dynamic etc).

Would be awesome to have a simple height/width setter for the whole component or do you know a different way I could do it?

**Comment by vlio20** [comment]
I am not planning to add this type of capability.
Css is your best friend here.

Will be happy to assist.

**Comment by kirstenfrager** [comment]
can you please help me?

i have this:

  // gets rid of the border css for the main calendar body
  .dp-material .dp-calendar-wrapper {
    border: transparent !important;
  }

  // gets rid of the border css for the header of the calendar 
  .dp-material .dp-calendar-nav-container {
    border: transparent !important;
  }

  // calendar header row (eg. Oct 2017)
  .dp-material .dp-nav-header-btn {
    font-size: 20px !important;
    // width: 100px !important;
  }

  // size of the calendar header
  .dp-material .dp-calendar-weekday {
    // width: 35px !important;
    font-size: 18px !important;
    margin-bottom: 5px !important;
  }

  // size of arrow icons
  .dp-calendar-nav-left::before, .dp-calendar-nav-right::before {
    height: 10px !important;
    width: 10px !important;
  }

  // size of the calendar body
  .dp-calendar-day {
    // width: 35px !important;
    // height: 30px !important;
    font-size: 16px !important;
  }

  // calendar months dates
  .dp-material, .dp-calendar-month {
    font-size: 17px !important;
  }


i have commented out the height and widths for now as on some devices it was fine but on smaller screens it obviously doesn't dynamically resize. any ideas?

**Comment by vlio20** [comment]
Please create a stackblitz

**Comment by kirstenfrager** [comment]
never used stackblitz before. 
having trouble getting it to read my CSS file.

https://ionic-4ty5xe.stackblitz.io

**Comment by vlio20** [comment]
Are you using ionic?

You could look into other issues in this repo, they have a link to a working stackblitz.

I won't be next to a computer until the evening
