### ISSUE TITLE
29th October 2017 displayed twice

### ISSUE THREAD

**Issue by waveywhite** [vlio20/angular-datepicker#235]
I've found that the 29th Oct 2017 is displayed twice.

![screenshot from 2017-10-12 16-15-22](https://user-images.githubusercontent.com/2602241/31503939-e75c3af8-af68-11e7-91ec-ae50975bb419.png)

**Comment by vlio20** [comment]
holly crap, indeed. 
On what version are you?

**Comment by waveywhite** [comment]
From npm list:
ng2-date-picker@2.5.0

**Comment by vlio20** [comment]
try to rollback. I am working on a fix.

**Comment by waveywhite** [comment]
Thank you @vlio20. I'll probably wait as this is in development atm and not affecting us yet.
Who knows - perhaps the 29th will be so good it's worth repeating.

**Comment by vlio20** [comment]
:)

what is special with the 29th - I think the summer clock (DST) switches to a winter clock (DWT) (winter is coming  ❄️ )

**Comment by waveywhite** [comment]
Yes, here in the UK it ends at 2am on the 29th. So it's not a way of reminding everyone when it's your birthday, then?

**Comment by vlio20** [comment]
Nope, but it's a good idea to put some easter eggs on this fate ;)

**Comment by vlio20** [comment]
available now in 2.5.1

**Comment by waveywhite** [comment]
That fixes it, thank you.

**Comment by vlio20** [comment]
Glad to hear

**Comment by vlio20** [comment]
Your ⭐️ would be much appreciated

**Comment by waveywhite** [comment]
Absolutely. Done.
