### ISSUE TITLE
min and max selecteble dates

### ISSUE THREAD

**Issue by Daewl** [vlio20/angular-datepicker#248]
Hello All,

i am trying to achive, disable past days and allow only selectible 4 days later include today.

thanks for help.

**Comment by vlio20** [comment]
You can use the disabled callback. You can find it in the documentation. Would be helpful if you provide a stackblitz

**Comment by Daewl** [comment]
Sorry, new to angular and typescript.tried to use stackblitz but got some errors so here is my code i used.

--html-- 
<form action="/" method="post" class="form-login-lc basic-form" #userform="ngForm" (ngSubmit)="complateMyOrder(userform.value)">
<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig" name="selectedDate" theme="dp-material"></dp-date-picker>
</form>

--component.ts--

import {DpDatePickerModule, DatePickerComponent, IDatePickerDirectiveConfig} from 'ng2-date-picker';

datePickerConfig: IDatePickerDirectiveConfig = {
        hours24Format: 'HH',
        showTwentyFourHours: false,
        firstDayOfWeek: 'mo',
        locale: 'tr',
        closeOnSelect: true,
        showSeconds: false
    };

complateMyOrder(order) {
        var OperationDate = order.selectedDate;
        this.apiService.callService(new Method('Order/CompleteOrder', { OperationDate}, 'put'))
            .subscribe(h => {
                debugger;
                this.orderPayment = h["result"];
            })
    }

**Comment by Daewl** [comment]
member can only select 17,18,19 and 20th of october, tomorrow it will ve 18,19,20 and 21th of october and so on.

**Comment by vlio20** [comment]
`isDayDisabledCallback` is your friend, you can put there any logic that you like

**Comment by Daewl** [comment]
here is stackblitz:
https://angular-sevzfn.stackblitz.io

**Comment by Daewl** [comment]
https://stackblitz.com/edit/angular-sevzfn

**Comment by sunnykantkr** [comment]
Is this resolved? Could you please provide the usage of isDayDisabledCallback or isMonthDisabledCallback.
