### ISSUE TITLE
ReactiveForms printing out date as string

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#249]
I'm using `ReactiveForms`

We introduced the `dpDayPicker` as per docs, like that:

`<input type="text" formControlName="myDate" [dpDayPicker]="datePickerConfig" />`

That is our `datePickerConfig`:

```ts
public datePickerConfig = <IDatePickerConfig>{
  locale: "de",
  format: "DD.MM.YYYY",
  firstDayOfWeek: "mo"
};
```
That is the result once a day is selected:

![image](https://user-images.githubusercontent.com/16785357/31718325-d1e73b5e-b40f-11e7-931a-4eeb17d53e28.png)

Why is it showing as a string and not as a proper date?

**Comment by vlio20** [comment]
What are you expecting to receive?

**Comment by dgroh** [comment]
I'll close this issue. I see that the `log` is printing out the correct date as:

`Wed Feb 01 2017 00:00:00 GMT+0100 (Mitteleuropäische Zeit)`

So is something I have to handle in the callback. I think it was a misunderstanding
