### ISSUE TITLE
Documentation for max date Moment|String is wrong?

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#250]
When trying to set the `max` property of the `IDatePickerConfig` as a string, it does not work.

The documentation says it can be either String or Moment.

![image](https://user-images.githubusercontent.com/16785357/31721016-7a4640e4-b418-11e7-91f6-39919fff9be2.png)

**Comment by vlio20** [comment]
Sounds like a bug.
Will take a look.

**Comment by vlio20** [comment]
resolved in ad98d1b
