### ISSUE TITLE
How to properly style?

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#251]
I'm using the standard theme `dp-material`, it looks odd:

![image](https://user-images.githubusercontent.com/16785357/31729588-b49804b4-b42f-11e7-9dc2-a7800dcc1f7d.png)

How do I set the `width` for the container? Also the circles are way too ovals.

Is there any documentation for styling?

**Comment by vlio20** [comment]
this is looking very bad indeed...
Maybe some other styles are effecting your implementation. try to set the `appendTo: 'body'`.

Let me know if it helps, if not please post a stackblitz.

**Comment by dgroh** [comment]
I created a stackblitz but it looks good there: https://stackblitz.com/edit/angular-trty1e

I'm trying to see what is making this in my environment, but I don#t find any css overriding it, but in any case would be good if we could override the theme, set a width, height and so on?

**Comment by dgroh** [comment]
just found the place and fixed it, but how can I set the width of the datepicker so that it has the same size of the input?

![image](https://user-images.githubusercontent.com/16785357/31758783-23918208-b4af-11e7-8d0f-2db139b6c539.png)

**Comment by vlio20** [comment]
Currently not possible. Will be easier with https://github.com/vlio20/angular-datepicker/issues/252

As a workaround you will have to do the adjustments in your css.
