### ISSUE TITLE
[New feature] Use table instead of div

### ISSUE THREAD

**Issue by ninethug** [vlio20/angular-datepicker#252]
Hi there,

Is it possible to make the calendar responsive ? To take all the width of the parent container ?
It seems that .dp-calendar-day and .dp-calendar-weekday fix the width of every single day and the sum gives the width of the calendar.

I suggest to use a table instead of div inside divs to make it take all the width of the parent container  and also to make it responsive.

**Comment by vlio20** [comment]
using table instead of a div is something that I want to do... 
PR will be very welcomed!

**Comment by ninethug** [comment]
PR stands for ? (english is not my principle language)

**Comment by vlio20** [comment]
Pull Request.
If you are new to contributing and submitting a PR please see the following: https://help.github.com/articles/creating-a-pull-request/

If you have any question or you need any further help, please let me know - I would be very happy to assist you.

**Comment by ninethug** [comment]
Pull Request, of course 😄 
I'd be glad to contribute to make it responsive but I'm short for now. I'm trying to find a faster alternative, but It would be my pleasure to help you with it once I have more time.

**Comment by vlio20** [comment]
So I will keep this one open, until I will get a chance to get to it.

**Comment by SentyQ** [comment]
I'm waiting for this fix too..

**Comment by vlio20** [comment]
@SentyQ why does it matters if it's a table or divs?

**Comment by vlio20** [comment]
Marking this as "won't do" as it is a breaking change and I don't see how tables are helping making the picker to be more responsive.
