### ISSUE TITLE
displayDate on the directive one doesn't work

### ISSUE THREAD

**Issue by miyolou** [vlio20/angular-datepicker#254]
Hi there,

I was using the directive datepicker and I couldn't get the displayDate working at all and turns out even on the demo it doesn't work when I populate the display date on the date time picker directive while the date time picker works ok.

Not working:
https://prnt.sc/gzchkx

Working:
https://prnt.sc/gzchyk

**Comment by vlio20** [comment]
Hi. It would be great if you will post a stackblitz demo.

**Comment by miyolou** [comment]
I'm sorry, been racking my head on this and realised it wasn't a config but an attribute to the component. The question now then is, is displayDate supported for the directive version?

**Comment by vlio20** [comment]
yes, it should be. The  `displayDate ` is only for open the calendar on a specific date (default is today)

**Comment by miyolou** [comment]
https://stackblitz.com/edit/angular-nf5gyb?file=app%2Fapp.component.html,
Could only think of binding [displayDate] on the input element but it just complains that it is not an attribute.

**Comment by vlio20** [comment]
this is a bug! will address as soon as possible

**Comment by miyolou** [comment]
You're the best! Thank you!

**Comment by vlio20** [comment]
resolved in  984aab8
