### ISSUE TITLE
Make min date as default when calendar opens

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#256]
Is it possible to make a default date in calendar if I set it to min?

Scenario: The current date is `10-19-2017`, but the min date that the user can select is `12-01-2017`

When the user opens the DatePicker, he is going to see `10-19-2017` and won't understand what is happening. This is a common feature for the most of DatePicker controls.

Using `displayDate` could solve this, but thing is we don't want so show anything in the input so long the user has not picked any date.

**Comment by vlio20** [comment]
`dislplayDate` is only made to open the calendar on specific date.

**Comment by dgroh** [comment]
That is ok, but what about my question? Does this make sense? I can try a PR if you want I think that is a very useful feature.

**Comment by vlio20** [comment]
I don't understand why dispalayDate doesn't solve your case

**Comment by dgroh** [comment]
Because we don’t want to display anything until the user picks a day. It doesn’t make sense to show in calendar the current date if the min date is set for later. I’ll create a stackblitz to demonstrate the behavior

**Comment by dgroh** [comment]
I'm trying to create a Stackblitz with moment but it does not work: https://stackblitz.com/edit/angular-trty1e

**Comment by vlio20** [comment]
try this one: https://stackblitz.com/edit/angular-1e7a7vv

**Comment by dgroh** [comment]
I get:

>Yikes! The page you requested couldn't be found.
> If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core

**Comment by dgroh** [comment]
Ok I got it to work: https://stackblitz.com/edit/angular-trty1e

Note that although the min date is december, when the picker opens it shows the current month. This does not make sense. If you check other datepickers you will see that the min is always de default date, for example:

https://dojo.telerik.com/IzEfI

**Comment by vlio20** [comment]
@dgroh, it make sense. I will implement it in the next version (2.6.0)

**Comment by dgroh** [comment]
Brilliant much appreciated

**Comment by vlio20** [comment]
resolved in 5663b7a

**Comment by ld-gary** [comment]
Hey,

Sorry to open this again but I am trying to implement this exact behaviour and have the latest version, but no joy.

Below is my initialisation of the config object, setting a time of 12:30 the next day, followed by the picker instance in the view. Feel free to let me know if I'm being stupid but I can't see what I'm doing wrong?

Thanks!

`let findTomorrow = moment(new Date()).set({'hour': 12, 'minute': 30, 'second': 0}).add(1,'days');`

`this.tomorrow = findTomorrow.format("DD MMM [at] HH:mm");`

`
      this.dateConfig = {
	    	format: "DD MMM [at] HH:mm",
	    	min: this.tomorrow,
	    	showTwentyFourHours: true,
	    	disableKeypress: true,
	    	minutesInterval: 15
	    };
`

----- Date Picker Instance -----

`						<dp-date-picker
						*ngIf="showDatePicker"
						#Picker
						formControlName="temp_date"
						(ngModelChange)="dateToChange($event, false)"
						(close)="dpClosed(false)"
						[config]="dateConfig"
						theme="dp-material"
						[placeholder]="date_open ? '' : 'Set Date & Time'"
						mode="daytime"></dp-date-picker>`

**Comment by vlio20** [comment]
pls provide a stackblitz

**Comment by ld-gary** [comment]
https://stackblitz.com/edit/angular-up6aaq?file=app%2Fapp.component.ts

**Comment by ld-gary** [comment]
So as I understand it, setting the min parameter of the config object to a particular date should select that date if the current date is earlier?

**Comment by ld-gary** [comment]
Hey, just an update/clarification. The above code and the original stackblitz had the date strings formatted in such a way that there was no year present ("DD MMM [at] HH:mm"). I have updated in my code and on the stackblitz which half solves the issue in that the picker opens on the minimum date, but the time is still just set to whatever time it is when the page loads.

I understand that setting the model (or control name) does cause the picker to open at a specified time, but I don't want to actually have to set the date and time on load. I just want the picker to open at the date and time that corresponds to the minDate value. Can it be done in a way that I am missing?

Thanks and Happy New Year!
