### ISSUE TITLE
Prevent user from editing the text input

### ISSUE THREAD

**Issue by gildebrand** [vlio20/angular-datepicker#258]
I've run into an issue that I haven't found any information about in this library's documentation. 

**Issue**
After the user has selected a date, if they edit the value in the input field the model value is bound to the string value instead of a Moment instance. This can easily be reproduced in the examples (https://vlio20.github.io/angular-datepicker/). Select a date, and remove a character from the input field. This causes the previously selected date in the datepicker to be unselected.

**Proposed solution**
The input field should be disabled, listening to the click event to bring up the datepicker.

**Comment by vlio20** [comment]
Not sure I am understanding your proposed solution.
The reason it is changed to string is because it is invalid input, of the user will set a valid date you will get back a moment object again. 

If you want to be updated only when a valid date has been set, than please use onChange output event

**Comment by gildebrand** [comment]
Sorry for being unclear. I'll try to explain it better 😄
A textfield makes sense to use for *presentation* of the selected date. However, the textfield shouldn't be editable by the user because that causes the ngModel bound value to become a string instead of a Moment instance. This shouldn't be possible.

The solution could simply be to give the input field (`.dp-picker-input`) rendered by the `DatePickerComponent` (for instance) the `disabled` attribute.

Looking at the source, I can affect the disabled attribute by passing the input `disabled`. However this causes that the date picker isn't shown at all.

There's an issue however with using the disabled attribute; the user can't tab to the field.

Is the issue understandable, and do you have any idea how to solve this issue?

**Comment by vlio20** [comment]
I hope I understand, does `disableKeypress` solves your problem?

**Comment by gildebrand** [comment]
I'm a little bit embarrassed now. That's exactly what I was looking for 😄

**Comment by vlio20** [comment]
Np
