### ISSUE TITLE
how to change date picker config settings dynamically

### ISSUE THREAD

**Issue by gauravumrani** [vlio20/angular-datepicker#265]
i want to change date picker settings dynamically.
at component loading, allowmultiselect is true, and on click of a button.. i want it to be allowmultiselect false..
i tried this, but didnt worked.
`
datePickerConfig: IDatePickerConfig = {
    firstDayOfWeek: 'mo',
    format: 'DD-MM-YYYY',
    allowMultiSelect:true
  };
`
`
 addToCart()
  {
    this.datePickerConfig.allowMultiSelect=false;
    console.log(this.datePickerConfig);
  }
`

**Comment by vlio20** [comment]
please post a stackblitz

**Comment by vlio20** [comment]
Closing for now
