### ISSUE TITLE
Please consider using Moment instead of String in the ControlValueAccessor

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#266]
First I want to give a thumbs up for the new features in `2.6.0`.

Does it make sense to return the value of the selected date as `Moment` date instead of a `String`? To show in the input as a `String` is ok, but for the form result should be a `DateTime` / `Moment` date. 

If I use: `{{ this.myForm.value }}` the selected dates are going to be printed out as `String` and this is bad for an api that expects a `DateTime`. This means, before sending to my api `{{ this.myForm.value }}` I need to get the date controls e convert them to `DateTime`. This could be fixed by making the `ControlValueAccessor` value a Moment property.

Does this make sense? This is just a suggestion. For example Angular Material Date Picker does exactly the same. It prints out in the input a string, but the form is a DateTime.

**Comment by vlio20** [comment]
The value returned can be modified by the `returnedValueType ` option. let me know if it helps

**Comment by dgroh** [comment]
More or less. The most of the backend apis do not understand Moment. I would have to use `toDate()`. Correct?

I cannot submit a form without changing the value type before. Unfortunatelly I cannot create a Stackblitz with an Api call, but imagine that I have a type `DateTime` as parameter and I have to submit a form with this parameter. Until now, for example, with DatePicker of Angular Material Design I had only to to: `submit(this.myForm.value)`

**Comment by dgroh** [comment]
ok, I think there is no way around it. I'm closing this issue as I think I was misunderstanding things.
