### ISSUE TITLE
disableKeypress doesn't work on the directive

### ISSUE THREAD

**Issue by miyolou** [vlio20/angular-datepicker#267]
<label>Directive Input</label>
<input [dpDayPicker]="directiveConfig" mode="day" [(ngModel)]="date">

<label>Component Input</label>
<dp-date-picker [config]="directiveConfig" mode="day" [(ngModel)]="date2">
</dp-date-picker>
 
directiveConfig = {
  disableKeypress: true;
}

https://stackblitz.com/edit/angular-pgjndr?file=app%2Fapp.component.html

Browser seems to complain about setAttribute on Element requiring 2 arguments instead of one. Still works on the component datepicker thought, if you comment out the Directive date picker in the stackblitz.

**Comment by vlio20** [comment]
looks like a bug. will check as soon as possible.

**Comment by miyolou** [comment]
Thank you!

**Comment by vlio20** [comment]
resolved in 1c00e48
