### ISSUE TITLE
Rounding Time

### ISSUE THREAD

**Issue by jphearse** [vlio20/angular-datepicker#268]
Is there a way to have the Day Time picker start at the nearest increment of 15?

Example: If I opened the Day Time picker at 12:27pm, the time would show 12:30pm and I could increment from there.

**Comment by vlio20** [comment]
you can pass any `displayDate` that you want. Let me know if it helps.

**Comment by jphearse** [comment]
Sorry I don't think I explained very well. What I am trying to do is allow users to create meeting without our app. The problem I'm having is when the user opens the dateTime picker it shows the current time, for example if the user opens the datetime picker at 12:27pm the datetime picker shows the current date at 12:27pm. I am wondering if I can have the datetime picker open and show the current date at 12:30pm. Essentially, is it possible to go to nearest increment of 15 minutes on open?

**Comment by vlio20** [comment]
so in order to open open it on the rounded date time use `displayDate` and for the interval of 15 min use `minutesInterval`, does it helps?

**Comment by jphearse** [comment]
I can get the `minutesInterval` to work but I cant seem to get the `displayDate` to work properly.

**Comment by vlio20** [comment]
please post a stackblitz, I will be happy to help

**Comment by vlio20** [comment]
Glad you solved it. Would really appreciate a ⭐️
