### ISSUE TITLE
Date picker popup is buried inside the div

### ISSUE THREAD

**Issue by keshav1007** [vlio20/angular-datepicker#270]
Hi,

If i place the date picker inside a div which has overflow: auto the date picker is not coming out of the div instead it is coming inside the div itself. I want the date picker to pop outside the div.

https://stackblitz.com/edit/angular-yg84jc?file=app%2Fapp.component.html

Please let me know how can i achieve this.

**Comment by vlio20** [comment]
you can find in the documentation `appendTo` configuration, pls let me know if it helps.

**Comment by keshav1007** [comment]
No still it is not coming outside the div

https://stackblitz.com/edit/angular-zdkhmw?file=app/app.component.ts - updated the stackblitz

**Comment by keshav1007** [comment]
oh i have to map it to the outer most div. It worked thanks :)

**Comment by vlio20** [comment]
Great! You could also use body.
It would be great if you can ⭐️ this repo!

**Comment by keshav1007** [comment]
I have already ⭐️ this 👍
