### ISSUE TITLE
Browser translate causes interpolates values to NOT update

### ISSUE THREAD

**Issue by chrxs** [vlio20/angular-datepicker#277]
We have an issue where the date picker is translated to German
The users browser gives them the option to translate the page (say to English for example)
The user does this and translates the page to English
The interpolated text values (`{{monthName}}` for example) no long update when changing months

![](https://d26dzxoao6i3hh.cloudfront.net/items/321c0Q0c2r3A311T0e3a/Screen%20Recording%202017-11-01%20at%2010.13%20am.gif?v=a2d83a0b)

This is the original HTML for the month names:
```html
<div class="dp-calendar-nav-container">
  <div class="dp-calendar-nav-container-left">
    <button class="dp-calendar-nav-left" type="button"></button>
  </div>
  <span class="dp-nav-header">November 2017</span>
  <button class="dp-nav-header dp-nav-header-btn" type="button" hidden="">
    November 2017
  </button>
  <div class="dp-calendar-nav-container-right">
    <button class="dp-calendar-nav-right" type="button"></button>
  </div>
</div>
```

...and this is the HTML after the browser translates:
```html
<div class="dp-calendar-nav-container">
  <div class="dp-calendar-nav-container-left">
    <button class="dp-calendar-nav-left" type="button"></button>
  </div>
  <span class="dp-nav-header">
    <font style="vertical-align: inherit;">
      <font style="vertical-align: inherit;">November 2017</font>
    </font>
  </span>
  <button class="dp-nav-header dp-nav-header-btn" type="button" hidden="">
    <font style="vertical-align: inherit;">
      <font style="vertical-align: inherit;">November 2017</font>
    </font>
  </button>
  <div class="dp-calendar-nav-container-right">
    <button class="dp-calendar-nav-right" type="button"></button>
  </div>
</div>
```

You can see some `<font>` tags have been added, after this changes don't seem to update these tags.

Angular version: **4.4.4**
I have only seen this on Google Chrome browser.

**Comment by chrxs** [comment]
...a side note, we've had this problem throughout our entire app, and have gone through changing all
```html
<div>{{value}}</div>
```
to:
```html
<div [innerText]="value"></div>
```
It seems to resolve the problem, with no perceived side effects, presumably because it replaces the contents on the HTML element and removing the `<font>` tags generated by the translation.

**Comment by vlio20** [comment]
Did you find any mention for this on Angular's site? Seems like something that should happen a lot.

**Comment by chrxs** [comment]
I know what you mean, but we weren't able to find any information about it, when we search "translate" we just kept getting results about angular's i18n and the translate service, not the browsers translation feature

**Comment by vlio20** [comment]
thanks for the PR, fixed in 8f6d69e

**Comment by vlio20** [comment]
@chrxs, the gif you posted, is it this your implementation of this component?

**Comment by chrxs** [comment]
Yeah, that's right

**Comment by vlio20** [comment]
what version are you using? the nav buttons of 2.6.0 are not placed like in the image

**Comment by chrxs** [comment]
oh i see what you mean, not the latest version, we're using version 2.4.0

**Comment by vlio20** [comment]
so be ready to implement some changes if you want to use 2.6.0

**Comment by chrxs** [comment]
ok will do 😄 thanks
