### ISSUE TITLE
displayKeypress with material input still allows key presses

### ISSUE THREAD

**Issue by miyolou** [vlio20/angular-datepicker#285]
Using the directive with a config of `disableKeypress` matched with angular material's input form field, it still allows key presses.
  
```
<mat-form-field>
   <input matInput [(ngModel)]="date" [dpDayPicker]="config" mode="day">
</mat-form-field>

config = {
    disableKeypress: true,
};
```
Using:
    Angular v5.0.0
    Material 2.0.0-beta.12
    ng2-date-picker 2.6.1

**Comment by vlio20** [comment]
Does it happens with ordinary input?

**Comment by vlio20** [comment]
please provide a stackblitz. I will close this issue until then.
