### ISSUE TITLE
format in IDatePickerConfig not working

### ISSUE THREAD

**Issue by ninethug** [vlio20/angular-datepicker#287]
Hi,

The format field for IDatePickerConfig is not working, it's always returning a Moment object event if the selectDate ngModel field is a String. I'm using it with an inline day calendar.

PS: For inline day calendar section in the documentation, you maybe should correct IDayPickerConfig to IDatePickerConfig. A little bit confusing for beginners.

Cheers

**Comment by vlio20** [comment]
Try to use `returnedValueType` to specify the returned type of the value.

**Comment by vlio20** [comment]
@ninethug, please let me know if it worked for you.
