### ISSUE TITLE
Input and DateTimePicker not synced

### ISSUE THREAD

**Issue by jphearse** [vlio20/angular-datepicker#288]
![image](https://user-images.githubusercontent.com/14226072/32631750-c91c0c08-c566-11e7-833f-6174f61e7681.png)
 
Any idea why the datepicker does not open up to the datetime that is in the input? It just opens to the current time, instead of what is in the input.

**Comment by vlio20** [comment]
Can you please post a stackblitz with your config?

**Comment by jphearse** [comment]
I got the problem fixed by changing my dateTimeConfig some. 

Before:
```
  dateTimeConfig = {
    locale: 'en',
    firstDayOfWeek: 'su',
    format: "DD MMM, YYYY hh:mm A",
    monthFormat: "MMMM",
    dayBtnFormat: "D",
    minutesInterval: 15
  };

```
After:
```
  dateTimeConfig = {
    locale: moment.locale(),
    firstDayOfWeek: 'su',
    format: "DD MMM YYYY hh:mm A",
    dayBtnFormat: "D",
    minutesInterval: 15
  };
```
