### ISSUE TITLE
Question: max not greying out future dates

### ISSUE THREAD

**Issue by deiyanfott** [vlio20/angular-datepicker#289]
Hi,

I was expecting days from November 11 onwards to be greyed out but they are not. I am not sure if I missed out on some configuration or some other setup.

component.html
`<dp-date-picker [(ngModel)]="auditMapping.dateFrom" [config]="datePickerConfig" placeholder="Select a start date" theme="dp-material" (onChange)="onChangeDate(auditMapping.dateFrom, 'start')"></dp-date-picker>`

component.ts
`this.datePickerConfig = {
            disableKeypress: true,
            format: "YYYY-MM-DD",
            showNearMonthDays: false,
            monthFormat: "MMM, YYYY",
            showMultipleYearsNavigation: true,
            max: moment()
        }`

Not greyed out future dates.
![capture](https://user-images.githubusercontent.com/33542094/32649935-e8ac219a-c636-11e7-959c-2abbb237ceb4.JPG)

**Comment by vlio20** [comment]
Can you please post a stackblitz?
