### ISSUE TITLE
moment as peerDependency

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#290]
Is there a reason why `moment` is not as `peerDependency`?

**Comment by vlio20** [comment]
Mmmm.... Not sure why it should be. What are the cases for peer dependencies?

**Comment by dgroh** [comment]
it`s a `peerDependency` IMO. We are importing twice in our application, from the DatePicker and already our old moment reference. It's used for development but there is no need to export it together with the DatePicker. Maybe this might be helpful: https://github.com/Hacker0x01/react-datepicker/issues/122

**Comment by vlio20** [comment]
I don't want to make users to download moment, it makes them do another step in implementing the component. 

I plan to remove this dependency in v3 (it might take a while though...)

**Comment by kirillgroshkov** [comment]
Any updates on removing moment as dependency?

**Comment by vlio20** [comment]
@kirillgroshkov yeas there are such plans but currently I have no capacity to do it
