### ISSUE TITLE
Performance issue Internet Explorer

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#292]
We have a big problem with IE when embedding the DatePicker.

If we remove it everything work fine. We have four of them in our web site.

I could also reproduce it on your your web site: https://vlio20.github.io/angular-datepicker/

Try scrolling open and down several times. Also open the task manager and check that internet explorer is driving crazy.

Is there any event bound to it like onScroll or something like that?

Thank you very much

**Comment by vlio20** [comment]
Need to check....

**Comment by vlio20** [comment]
I added some improvements to listeners in 2.6.2, @dgroh can you pls approve that it helped? (I don't have computer which is running IE).

**Comment by dgroh** [comment]
If you mean that `https://vlio20.github.io/angular-datepicker/` is already in 2.6.2, then unfortunatelly the scroll is still hanging even if the datepicker is closed. I know IE sucks, but unfortunatelly there are a lot of applications running on IE. I few like there is a kind of scroll event attached to the datepicker, because when I scroll with opened datepicker, the datepicker scrolls with the scrollbar. Let me know if the `https://vlio20.github.io/angular-datepicker/` is with the newest version.

**Comment by vlio20** [comment]
it is... What version of IE are you using? Could please do some profiling to tell what function make it hangs?

**Comment by vlio20** [comment]
BTW, the demo is still with the scrolling listeners but I made it more efficient within the component. Can you tell if you see any difference within your application?

**Comment by dgroh** [comment]
@vlio20 , i'm using IE11. I'll compare the 2.6.1 and 2.6.2 within my application on Monday. Profiling on IE is hard, so I think the easiest first step for me will be to fork, remove the listener and see what happens. I'll let you know.

**Comment by dgroh** [comment]
Hi @vlio20 , good news, within the application it's much quickier now. The only problem is when the datepicker is opened. Before this update, the browser was hanging even when the datepicker was closed, now it hangs only when opened. Any chance to fix this also? For usability, I'm not quite sure if it makes sense to still show the datepicker when scrolling. See the datepicker from amterial design:

https://material.angular.io/components/datepicker/examples

You are not even able to scroll if it's opened.

**Comment by vlio20** [comment]
I don't want to do such ux decisions. You can block the scrolling on your side. I can't remove the scrolling listener when the picker is open when the element attached to body or other element that moakes the picker in absolute position.

I saw that you forked the repo, let me know if you find any other options for improvement.
