### ISSUE TITLE
Setting min value dynamically overrides previous properties

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#293]
issue was first referenced here: https://github.com/vlio20/angular-datepicker/issues/269#issuecomment-343474730

I created a stackblitz with the new `2.6.1`: https://stackblitz.com/edit/ng2-date-picker

The code below is setting the configuration to its default:

```
    // When DateFrom changes we set the min selectable value for DateTo
    this.filterForm.get("dateFrom").valueChanges.subscribe(value => {
      this.dateToDp.displayDate = value; // DateTo
      this.dateToDp.config = {
        min: value
      }
    });
```

using `...this.dayPickerConfig` will break the `min` selectable value.

**Comment by vlio20** [comment]
What do you mean by breaking the value?

**Comment by dgroh** [comment]
That is weird, I just tried again with `...this.dayPickerConfig` and it's working.

https://stackblitz.com/edit/ng2-date-picker-cnmlqb

I'll close this issue and hope not to come back here with it :)

On Monday I'll smoke test everything again in our test system!

**Comment by vlio20** [comment]
@dgroh, this is not the way you should change the config.. You shouldn't  change the config via `ViewChild`. You should only change the reference to the config attribute object

**Comment by dgroh** [comment]
Hi @vlio20, so how can I change the min value of the one DatePicker component? If I change the config attribute object this change will propagate for all the components. Should I use then one config for each component?

**Comment by vlio20** [comment]
You could use the same configuration, and use ...this.config when you want to update one of the properties

**Comment by dgroh** [comment]
Unterstand. Fair enough..thanks
