### ISSUE TITLE
If select same date twice it disappear in field..

### ISSUE THREAD

**Issue by AntRider** [vlio20/angular-datepicker#298]
If select same date twice it disappears in the field...
If I understand correctly it works like a checkbox. Can we set some configuration for disabled this option?

**Comment by vlio20** [comment]
can you please provide a use case? The question is how would the users clear their selection?

**Comment by AntRider** [comment]
I mean that when we press for example on February 20 one time, then everything works fine, but when we click on it again the chosen day disappears.
In your example, the same situation...

**Comment by lazysatyr25** [comment]
any progress on this?

**Comment by AntRider** [comment]
Probably, better will add some icon like '×'  in the text field, then if someone needs to remove date they will push this icon. What do you think about it ?!

**Comment by vlio20** [comment]
Sound alright.

**Comment by AntRider** [comment]
So any progress on this?

**Comment by vlio20** [comment]
Not yet. Dont have much time lately...

**Comment by aditya-padhi-kbl** [comment]
Hi @vlio20 ,

This issue is reproducible.  I select a date and click on the date-picker which opens a calendar.  Then I click on the selected date again.  The value in the field disappears.

**Comment by vlio20** [comment]
this will be enabled only for non-multiselect.

**Comment by AntRider** [comment]
Happy New Year!))
Any progress with this issue?

**Comment by vlio20** [comment]
Unfortunately I don't have time to put my hands on it. PR would help.

**Comment by vlio20** [comment]
resolved in 45e15ac
