### ISSUE TITLE
Bug in reactive form - date picker does not navigate to initial date

### ISSUE THREAD

**Issue by naharyd** [vlio20/angular-datepicker#299]
Hi,

When we are using reactive form and setting an initial date,
Date picker calendar is not navigating to initial date.
The reason: at `date-picker.component.ts` -> when `onViewDateChange` is being called -> at `set currentDateView` -> `this.dayCalendarRef` is not initialized (undefined).
Using timeout to set initial date will solve it.

*Code Example:*
HTML:
```html
<div class="dp-demo-page">
    <h2 class="dp-page-header">Angular Date/Time/Month Picker</h2>
    <form #form="ngForm">
      <div class="dp-picker-day-directive">
        <form [formGroup]="formGroup">
          <input [dpDayPicker]="config"
                 name="datePicker"
                 [theme]="'dp-material dp-main'"
                 formControlName="datePicker"/>
        </form>
      </div>
    </form>
</div>
```

Component:
```javascript
import {IDatePickerConfig} from '../../date-picker/date-picker-config.model';
import {DatePickerComponent} from '../../date-picker/date-picker.component';
import {Component, OnInit} from '@angular/core';
import {FormControl, FormGroup} from '@angular/forms';
import {ECalendarValue} from '../../common/types/calendar-value-enum';

@Component({
  selector: 'dp-demo',
  templateUrl: './demo.component.html',
  entryComponents: [DatePickerComponent],
  styleUrls: ['./demo.component.less']
})
export class DemoComponent implements OnInit{

  formGroup: FormGroup = new FormGroup({
    datePicker: new FormControl('02-01-2016')
  });

  config: IDatePickerConfig = {
    format: 'DD-MM-YYYY',
    returnedValueType: ECalendarValue.String
  };

  ngOnInit() {
    //uncomment this to make it work
    //setTimeout(this.modeChanged.bind(this), 0);
  }

  modeChanged() {
    this.formGroup.get('datePicker').setValue('03-01-2016');
  }
}
```

**Comment by vlio20** [comment]
thanks for the issue, could you pls create a stackblitz?

**Comment by naharyd** [comment]
https://stackblitz.com/edit/angular-hnyvcf?embed=1&file=app/app.component.ts

**Comment by vlio20** [comment]
will take a look asap

**Comment by vlio20** [comment]
@naharyd , do you want submit a PR?

**Comment by naharyd** [comment]
@vlio20 , Thank, but I don't have a fix.

**Comment by vlio20** [comment]
I am not sure if it's a bug. why the calendar should be opened on the selected date?

**Comment by dgroh** [comment]
you need to use `displayDate`:

```ts
  @ViewChild("dp") dp: DatePickerDirective;

  ngOnInit() {
    //uncomment this to make it work
    this.modeChanged();
  }

  modeChanged() {
    this.formGroup.get('datePicker').setValue('03-01-2016');
    this.dp.displayDate = '03-01-2016';
  }
```

which in my opinion should be automatically updated when setting the input value.

**Comment by naharyd** [comment]
@dgroh , what you did is a WA, as you mention the value of `displayDate` should be set automatically.

**Comment by naharyd** [comment]
@vlio20 , well, this is deepened on your design.
Usually, if I have selected date by default I expect it will be open on default date.
Anyway, in case it's not your design, then you have different issue, you have race condition issue.
In your example/Demo when setting default date it will be open on default date,
but in my example it won't happen (probably because *ngIf).

**Comment by vlio20** [comment]
I will soon ad an api to move the calendar to any date you like programmatically
