### ISSUE TITLE
Issue with displayDate

### ISSUE THREAD

**Issue by sarates** [vlio20/angular-datepicker#300]
I want to set initial value for datepicker.

```
<div class="form-group">
      <label for="day">Day</label>
      <input class="form-control" id="day" name="day" [(ngModel)]="selectedDate.date" theme="dp-material" mode="day" displayDate="{{selectedDate.date}}" [dpDayPicker]="datepickerSettings" />
</div>
```

```
ngOnInit() {
    this.datepickerSettings = {
      'appendTo' : 'body',
      'format' : 'YYYY-DD-MM',
      'enableMonthSelector' : false
    };

    this.selectedDate = {
      date : moment(new Date()).add(1,'days').format("YYYY-MM-DD")
    };
  }
```

Page just stop working. What Im doing wrong? Thx

**Comment by sarates** [comment]
Problem was with different 'format' : 'YYYY-MM-DD' and moment(new Date()).add(1,'days').format("YYYY-DD-MM"). Need to handle this error

**Comment by vlio20** [comment]
I am not sure what you are asking

**Comment by sarates** [comment]
Just need to compare format setting with displayDate date format.

**Comment by vlio20** [comment]
if you are providing a string. It has to be in the same format as the format attribute in the configuration
