### ISSUE TITLE
moment-jalali.js

### ISSUE THREAD

**Issue by sasanazizi** [vlio20/angular-datepicker#303]
hey , can i use moment-jalali library on this datePicker? And how please 
thanks for your awesome module

**Comment by vlio20** [comment]
What are u trying to achieve? Just put you locale in the configuration

**Comment by sasanazizi** [comment]
i'm trying to have a date picker with local calendar without georgian calendar 
you can show this fork from your module to pay atention my idea : 
[](https://fingerpich.github.io/jalali-angular-datepicker/)

**Comment by vlio20** [comment]
Did you try to see how it works in the demo?

**Comment by sasanazizi** [comment]
@vlio20 Yes:  
[https://fingerpich.github.io/jalali-angular-datepicker/](url)
that i shared with you in last comment!

**Comment by vlio20** [comment]
url is broken

**Comment by sasanazizi** [comment]
[https://fingerpich.github.io/jalali-angular-datepicker/
](url)

excuse me its fine

**Comment by sasanazizi** [comment]
excuse me its fine:
https://fingerpich.github.io/jalali-angular-datepicker/

**Comment by vlio20** [comment]
I am talking about the demo of this component. Not the one presented in the demo you shared

**Comment by vlio20** [comment]
closing for now
