### ISSUE TITLE
closeOnSelect not working when mode is 'daytime'

### ISSUE THREAD

**Issue by nitinsh99** [vlio20/angular-datepicker#305]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [X] Provide a **minimal code snippet**, please make sure it is well formatted.
Provided below
- [X] What's the **version** of Angular you're using?
4.4.5
- [X] Does this occur on specific browser?
No
- [ ] Provide **screenshots** where appropriate
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.

HTML:

```
  <dp-date-picker  [config]="config" closeOnSelect="'true'" theme="dp-material" [mode]="'daytime'">
    </dp-date-picker> 
```

TS:
```
 config: IDatePickerConfig = {
    firstDayOfWeek: 'su',
    monthFormat: 'MMM, YYYY',
    disableKeypress: false,
    allowMultiSelect: false,
    closeOnSelect: true,
    closeOnSelectDelay: 100,
    openOnFocus: true,
    openOnClick: true,
    onOpenDelay: 0,
    weekDayFormat: 'ddd',
    appendTo: document.body,
    showNearMonthDays: true,
    showWeekNumbers: false,
    enableMonthSelector: true,
    yearFormat: 'YYYY',
    showGoToCurrent: true,
    dayBtnFormat: 'DD',
    monthBtnFormat: 'MMM',
    hours12Format: 'hh',
    hours24Format: 'HH',
    meridiemFormat: 'A',
    minutesFormat: 'mm',
    minutesInterval: 1,
    secondsFormat: 'ss',
    secondsInterval: 1,
    showSeconds: false,
    showTwentyFourHours: false,
    timeSeparator: ':',
    multipleYearsNavigateBy: 10,
    showMultipleYearsNavigation: false,
    locale: moment.locale(),
    hideInputContainer: false,
  };

```

If you select a date, it won't dismiss the calendar. If the mode is default i.e without time, then the closeOnSelect works as expected

**Comment by vlio20** [comment]
On datetime there is close on select option shouldn't work. It was made by design. If you want to add such behaviour, you will have to listen on change event and then close the picker with the provided api.

**Comment by nitinsh99** [comment]
@vlio20 
Thanks for replying. I understand it's by design and I already tried the workaround you suggested but it's not working for me since I am using the datepicker with my custom input element.

It looks something like this:

```
<button #datePicker style="padding:3px;" type="button" class="btn btn-primary btn-with-icon" [dpDayPicker]="config" [mode]="'daytime'"
          theme="dp-material" closeOnSelect="'true'" (onChange)="fromDateTimeSelected($event)">
        </button>
```

Is there a way for me to close the calendar the calendar from fromDateTimeSelected() method?
Thanks

**Comment by vlio20** [comment]
You can close the datepicker with `api.close` the api should be provided as explained in the docs. Currently, there is no such `fromDateTimeSelected `, but there is `onChange` event. You can use it with the api to achieve your requirements

**Comment by nitinsh99** [comment]
May be I wasn't clear enough. If you look at my code:

```
<button #datePicker style="padding:3px;" type="button" class="btn btn-primary btn-with-icon" [dpDayPicker]="config" [mode]="'daytime'"
          theme="dp-material" closeOnSelect="'true'" (onChange)="fromDateTimeSelected($event)">
        </button>
```

I am calling my own function called "fromDateTimeSelected" on "onChange" event. As you can also see I am not using datepicker directive directly here but using it in conjunction with a button. If I use your library directly like following:

```
  <dp-date-picker  [config]="config" closeOnSelect="'true'" theme="dp-material" [mode]="'daytime'">
    </dp-date-picker>  
```

api.close() works just fine and I can close the calendar without any issue. However if I bind datepicker to an input or a button as shown above then api.close() doesn't work. So, in a nutshell my question is how can I close the date-picker which is bound to a button with onChange event. Hope that clear things out.

**Comment by vlio20** [comment]
Mmmm, could you create a stackblitz. It looks like a bug.

**Comment by nitinsh99** [comment]
Ok. I have created stackblitz as you requested. 
https://stackblitz.com/edit/angular-dim1tq

Steps to reproduce:
1. First click on default dp-datepicker input, click on any date and you will notice api.close() works as expected and datepicker gets dismissed.
2. Now go to app.component.html file, **comment out default datepicker and uncomment button element.**
3. Click on button, datepicker will be displayed, click on any date and in the console you will notice the exception. It fails to call api.close() here.

Let me know if anything is not clear.

**Comment by vlio20** [comment]
I managed to reproduce it, will fix this issue in next version (probably 2.7.0).

**Comment by vlio20** [comment]
not sure what fixed it, but in 2.7.0 this issue will be resolved as it not reproducible anymore in the next branch

**Comment by nitinsh99** [comment]
Hey, I just tried again with v2.7.0 and unfortunately I am still seeing the issue.  I updated the version on the stackblitz and could still reproduce it.

Do you mind taking a look and reopening this bug.
https://stackblitz.com/edit/angular-dim1tq

Thanks

**Comment by vlio20** [comment]
hi @nitinsh99 , there was an issue with building the module after upgrading to ng5. The issue was fixed. Please check this https://stackblitz.com/edit/angular-ystybm. This link should contain the working version of 2.7.2 - please let me know if you still have a problem

**Comment by nitinsh99** [comment]
Hello @vlio20 Thanks for following up.

Unfortunately I am still seeing the issue with v2.7.2. I tried the above link you mentioned.

![api_close_issue](https://user-images.githubusercontent.com/1389212/34996692-619abf80-faa8-11e7-9d29-fd227d82b0e1.png)

**Comment by vlio20** [comment]
this one is working: https://stackblitz.com/edit/angular-ystybm.
Notice that you have to set: `#dateDirectivePicker="dpDayPicker" ` and make sure you are taking the correct element reference in the `ViewChild` decorator. Let me know
