### ISSUE TITLE
After manually entering the time in Firefox

### ISSUE THREAD

**Issue by lm-ml** [vlio20/angular-datepicker#307]
After manually entering the time in Firefox
![bugs](https://user-images.githubusercontent.com/22191670/33643537-b0b56ce4-da7a-11e7-9bae-58567ed9ee5e.png)

**Comment by vlio20** [comment]
Please elaborate...

**Comment by lm-ml** [comment]
When I manually input time 2016-06-06 12:00:00, the time selection part will have a duplicate date, then delete the date of completion, and click on the open window again, it will appear in the image above.I can show it normally in Google browsers.   tks.

**Comment by vlio20** [comment]
Please post a stackblitz. I will take a look asap

**Comment by lm-ml** [comment]
I'm so sorry.After testing several times did not find the same problem,I think it should be my problem,Thank you for providing such a good calendar control

**Comment by vlio20** [comment]
Your ⭐️ would be much appreciated
