### ISSUE TITLE
How to load styles

### ISSUE THREAD

**Issue by Lazarencjusz** [vlio20/angular-datepicker#308]
Maybe it is a stupid question, but I can't see any style files inside module and the component is not styled. How I can apply styles?

**Comment by vlio20** [comment]
In order to get the material style you will need to add the the material theme. No need to load any css files.

**Comment by dave0688** [comment]
I had the same issue - I found that out only after I found this thread. Could you please add this in the docs?

**Comment by vlio20** [comment]
It is already written in the docs, look for theme

**Comment by rrohitesh** [comment]
@vlio20 I have used       theme: 'dp-material',
to set the style and them in the config but its not working still i can see the datepicker without any theme. Am missing anything here.
