### ISSUE TITLE
Inline - Day Calendar - ngModel does not response to value changed

### ISSUE THREAD

**Issue by AhugoA** [vlio20/angular-datepicker#309]
Hi, 
I'm using your great package and thank you for it!

I have a problem:

		<dp-day-calendar theme="dp-material" [(ngModel)]="selectedDate" [config]="config" (onSelect)="onSelect($event, 'day')"></dp-day-calendar>

and on my component it's:

	selectedDate: Moment = moment();
	config: IDatePickerConfig = {
		enableMonthSelector : false,
		showGoToCurrent: true,
	};
OnInit(){
			this.selectedDate = this.selectedDate.add(7, 'day'); <----- here I'm changing the ngModel

}

BUT the picker's model doesn't change 👎 
I've debugged it and saw that the function 'onViewDateChange' is not been called.

Any chance of a quick help? Is it a bug?

Thanks again.

**Comment by vlio20** [comment]
I would be happy to help, it would be helpful if you will post a stackblitz

**Comment by AhugoA** [comment]
[here it is](https://stackblitz.com/edit/angular-fpxkbk).

I know that for some reason the moment() is not working but on my app it does, don't want to spent too many time on understanding the mystery of 'moment' package...

Do you see my point?
On the button callback I'm changing the ngModel property but the picker is not affected by it...

**Comment by vlio20** [comment]
Thanks, I will take a look

**Comment by vlio20** [comment]
you need to pass a new date for that, in moment when you do `.add` it is mutating the object that the method applied on. Here is a working example: https://stackblitz.com/edit/angular-7jcy4r?file=app/app.component.ts
