### ISSUE TITLE
Request: Don't outline current day

### ISSUE THREAD

**Issue by asherbig** [vlio20/angular-datepicker#310]
I was wondering if there was a way to not outline the current day. It's not useful in my application.

https://i.gyazo.com/999e2e90b4ba9bd7e727db6722f6dd8e.png
Screenshot relevant.

**Comment by vlio20** [comment]
Yes. Use your own css. Override the button border.

**Comment by vlio20** [comment]
Put a link to one of your stackblitz demoes editor, I will try to show you there.

**Comment by asherbig** [comment]
https://stackblitz.com/edit/angular-yucbd7?file=app%2Fapp.component.html

**Comment by vlio20** [comment]
https://stackblitz.com/edit/angular-ffjoxw?file=styles.css
