### ISSUE TITLE
Request: Format invalid days differently than valid days

### ISSUE THREAD

**Issue by asherbig** [vlio20/angular-datepicker#311]
When I use the 'min' and 'max' options in the config, it restricts what days I can choose correctly by not letting me select an invalid day when I try to click on it. 

My request is, could there be a visual indicator that the day is invalid? Maybe tint the day red? Could you make this styling configurable?

**Comment by vlio20** [comment]
Sure there are the minDate and maxDate attributes

**Comment by asherbig** [comment]
HTML:
`<dp-day-calendar
      [(ngModel)]="curDate" 
      (onSelect)="onDateChange($event)" 
      [minDate]="minDate"
      [maxDate]="maxDate"
      theme="dp-material"
      [config]="config">
    </dp-day-calendar>`

Component code snippet:
`this.config = {
      min: this.minDate,
      max: this.maxDate,
      format:'MM/DD/YYYY',
      monthFormat: 'MMM YYYY',
      allowMultiSelect: false,
      weekDayFormat: 'dd',
      showNearMonthDays: true,
      yearFormat: 'YYYY',
      showGoToCurrent: false,
      monthBtnFormat: 'MMM',
      locale: moment.locale(),
    };`

Yet, my view for the calendar still doesn't format invalid days differently. Right now, the minDate is 1 month in the past, and the maxDate is one month in the future. This is what my rendered component looks like. Is there a confic or attribute somewhere I'm missing?
(max date is Jan 13) https://i.gyazo.com/8d7e8316f61dfb72070304d18b1b60ed.png
(min date is Nov 13) https://i.gyazo.com/507f67ff604e542967f38cc7627cfb63.png

**Comment by vlio20** [comment]
Please provide a stackblitz. It would be much easier for me to help.

**Comment by vlio20** [comment]
Providing a stackblitz would be a great. If you only want the form validation, you should use the attributes. It will make your form invalid. You could use this data to put your own logic. You can see how it works in the demo.

**Comment by vlio20** [comment]
I am not sure what do you mean by saying "invalid days look like".

**Comment by asherbig** [comment]
So in the stackblitz, the days that are invalid are days that are after January 13th. Those days look slightly more gray than the valid days. Can they be changed to be a different color? Maybe red? Can the background of them be changed to be a light red tint or something? The more configurable, the better.

**Comment by vlio20** [comment]
you can add any class you want with dayBtnCssClassCallback

**Comment by asherbig** [comment]
Do you have an example of how to use this? I haven't been successful using it yet, and there aren't any examples or demos I can find.

**Comment by vlio20** [comment]
```
config = {
   dayBtnCssClassCallback: (day: Moment) => { 
      return this.isValid(date) ? 'valid' : 'invalid';
   }
}
```
