### ISSUE TITLE
Request: Open Inline day calendar to configurable date

### ISSUE THREAD

**Issue by asherbig** [vlio20/angular-datepicker#312]
Title says it all. The non-inline calendars have the displayDate attribute that determines what day the calendar opens up on. Can we get similar functionality for the inline calendars? Currently, mine only opens to the current date.

**Comment by vlio20** [comment]
Stackblitz would be helpful.

**Comment by asherbig** [comment]
https://angular-yucbd7.stackblitz.io
In this example, I would like to be able to open the calendar, select a date in January, then close the calendar. If I go back to open the calendar again, then it should open on the view with January as the month, not as december.

**Comment by vlio20** [comment]
I need to link to the editor pls

**Comment by asherbig** [comment]
https://stackblitz.com/edit/angular-yucbd7?file=app%2Fapp.component.html

**Comment by vlio20** [comment]
it is working with displayDate **BUT** there is a bug that locks the navigation when this property is set.

**Comment by vlio20** [comment]
It is already possible to move calendar to specific date by calling `moveCalendarTo` I will add this to the documentation. Will be available in the docs with the release of 2.7.0

**Comment by vlio20** [comment]
resolved, will be available in 2.7.0
