### ISSUE TITLE
Open on

### ISSUE THREAD

**Issue by vlio20** [vlio20/angular-datepicker#314]
Open date components on, options:
1. current date (default)
2. selected -> fallbacks to 1
3. specific date (will lock navigation if set).

**Comment by vlio20** [comment]
won't be done. all options will lock the nav. closing

**Comment by asherbig** [comment]
Was there any functionality added to be able to open the calendar to the date associated with ngModel?

**Comment by vlio20** [comment]
No. There is an api to (not documented) that can move the calender to any date.

**Comment by asherbig** [comment]
How can I use this? Could you show in a stackblitz? 
https://stackblitz.com/edit/angular-yucbd7?file=app%2Fapp.component.html

**Comment by vlio20** [comment]
Use ViewChild and access the api of the calendar component. You will find
there exactly what you need.
