### ISSUE TITLE
dayBtnCssClassCallback performance issues

### ISSUE THREAD

**Issue by asherbig** [vlio20/angular-datepicker#317]
I'm using the dayBtnCssClassCallback to change the styling for certain days, however, the callback gets called seemingly infinitely, and causes performance problems with the webpage. Is this normal behavior?

**Comment by vlio20** [comment]
This should be called on each digest cycle, please provide a stackblitz to demonstrate your issue

**Comment by asherbig** [comment]
I can't reproduce the infinite calling bug that I'm getting, but here's an example with the dayBtnCSS method getting called multiple times. You can see in the console, it's getting called 6x84 times. 84 most likely because there's 2 calendars on the page, but really no idea why it's getting called for both calendars every time, or why it's getting called 6 times for each.
https://stackblitz.com/edit/angular-yucbd7?file=app%2Fapp.component.ts

**Comment by vlio20** [comment]
I am working on changing the components change detection to `onPush` this should solve this issue.

**Comment by vlio20** [comment]
will be added as part of 2.7.0 (#325)
