### ISSUE TITLE
Dynamically selected day not working (ngModel)

### ISSUE THREAD

**Issue by asherbig** [vlio20/angular-datepicker#318]
https://stackblitz.com/edit/angular-yucbd7?file=styles.css

I'm trying to dynamically update the currently selected day. When that stackblitz initializes, you can see the min and max dates on the TO calendar. When you select another date on the FROM calendar such as the 14th (whatever yesterday is). The TO calendar selected date auto-corrects itself to be a date in the selected range (in this case, the 18th), however, it's not getting the styling that it should be getting (blue background). It seems that the ngModel is not picking up on the new curDate. How do I fix this?

**Comment by vlio20** [comment]
It happens because you are overriding the default styling, the selected date still has the selected date class. You can see it in the link below. You will have to adjust you css. 
http://i.prntscr.com/qvesvrv8Quu7nE7dApyJ5g.png

**Comment by asherbig** [comment]
It's not that though. The curDate for the class shows the correct value, but if you inspect the calendar, you can see that the selected-day class is applied to the wrong calendar value. It's still on the old value. That's why the style is getting overridden. It's getting overridden because the ngModel didn't update to the actual current date, so what the calendar thinks is the current date is getting overridden by the invalid day styling, because it is an invalid day. It shouldn't still be the selected day.

**Comment by vlio20** [comment]
Can you please provide steps to reproduce with expected behavior? It's hard for me to follow

**Comment by asherbig** [comment]
In the from calendar, open the calendar and select yesterday's date. Now view the TO calendar. In the code, the current date (which is linked to the ngModel) has been changed to be 4 days from the date selected in the from picker calendar, but the TO calendar displays no changes for the selected day. It status on the day that it was initialized on
