### ISSUE TITLE
GoToCurrent should emit event

### ISSUE THREAD

**Issue by SaraOunissi** [vlio20/angular-datepicker#328]
Hi everybody,

I'm using ng2-date-picker and I observed that the button goToCurrent only put the focus on the current month. However,  when goToCurrent is clicked I need the date and time to be set to now (select current date and set the time to now). 

I started to look at the component to see how it is possible to resolve this issue. There is no accessible event fired when the button is clicked. I looked at the function moveToCurrent() of the component but it's not firing anything neigher. I'm starting to see if I should desable the goToCurrent button, and add my own button today.

Did anyone meet the same issue?! Do you have any idea of how I could handle it?!

Thank you for your help

**Comment by vlio20** [comment]
Hi Sara,
You are correct, by clicking on go to current you are only navigated to the current month (or year, in the month calendar).

I will mark this issue as a feature request to add event when this button is clicked.

**Comment by vlio20** [comment]
BTW, you are welcome to PR.

**Comment by justtal** [comment]
On it

**Comment by vlio20** [comment]
@justtal, thanks!

**Comment by vlio20** [comment]
resolved by @justtal will be available in 2.7.0. thanks @justtal
