### ISSUE TITLE
Could not find a declaration file for module ng2-date-picker

### ISSUE THREAD

**Issue by alijohn** [vlio20/angular-datepicker#338]
Hi,

I have updated my project recently with latest Jquery 3.2.1 and now the build is broke. I am getting:

Could not find a declaration file for module 'ng2-date-picker'. '../node_modules/ng2-date-picker/prebuild/app/index.js' implicitly has an 'any' type

I am using webpack inside the Visual Studio

Please help.

**Comment by vlio20** [comment]
on what version of the module are you?

**Comment by DustinQQ** [comment]
> on what version of the module are you on?

2.7.3 - same problem, probably it happened after "Upgrade to Angular 5"

**Comment by vlio20** [comment]
How do are you building your application? could you please submit a demo repo or even better publish a stackblitz?

**Comment by vlio20** [comment]
here is a working example; https://stackblitz.com/edit/angular-ystybm
