### ISSUE TITLE
DateTime picker - past time from current day can be selected

### ISSUE THREAD

**Issue by pbialy** [vlio20/angular-datepicker#340]
Hi

First of all - thank you for great library!

I found a bug tho - I'll describe it below, but I've also made a short gif to illustrate it, you can find it [here](https://ibb.co/b9DySR) or [here](https://gfycat.com/SoggyFrailBuffalo).

Basically - If you pass "min" to your datepicker config then calendar shouldn't allow you to select a date / datetime before this "min".

So if the "min" is set to, lets say, 1st January 2017, 11:00, then you won't be able to change it to 10:00.
BUT
If you change the date to 2nd Jan and change the time to 10:00, then you are able to change the date back to 1st Jan, which results in having 1st Jan 10:00, which is before the "min".

I'll be glad if this could be fixed.
Or maybe there's some setting which allows to prevent this situation? I'll be happy to know it then.

Regards
pbialy

**Comment by vlio20** [comment]
mmm nice one. Will mark this as bug. PRs are welcome

**Comment by vlio20** [comment]
Solutions (Bug fix):
1. Set the time to min time when there is a conflict as described above 
2. Disable the min date when time is changed (if required)

WDYT?

**Comment by vlio20** [comment]
resolved in 18db1ca
