### ISSUE TITLE
Metadata version mismatch 

### ISSUE THREAD

**Issue by MerkulovDev** [vlio20/angular-datepicker#343]
`Metadata version mismatch for module /projectFolder/node_modules/ng2-date-picker/index.d.ts, found version 4, expected 3, resolving symbol HistoryModule in /projectFolder/src/app/pages/history/history.module.ts, resolving symbol HistoryModule in /projectFolder/src/app/pages/history/history.module.ts
`
package.json
`"dependencies": {
    "@angular/animations": "4.4.5",
    "@angular/common": "4.4.5",
    "@angular/compiler": "4.4.5",
    "@angular/core": "4.4.5",
    "@angular/forms": "4.4.5",
    "@angular/http": "4.4.5",
    "@angular/platform-browser": "4.4.5",
    "@angular/platform-browser-dynamic": "4.4.5",
    "@angular/router": "4.4.5",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "2.0.0",
    "angular2-jwt": "0.2.3",
    "angular2-toaster": "4.0.1",
    "bootstrap": "4.0.0-beta.2",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.1",
    "element-closest": "2.0.2",
    "intl": "1.2.5",
    "moment": "^2.20.1",
    "ng-sidebar": "6.0.4",
    "ng2-date-picker": "^2.7.3",
    "ng2-datepicker": "2.1.6",
    "ng2-inputmask": "0.2.5",
    "ng2-webstorage": "1.8.0",
    "ngx-bootstrap": "2.0.0-beta.8",
    "rxjs": "5.4.3",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "1.4.7",
    "@angular/compiler-cli": "4.4.5",
    "@angular/language-service": "4.4.5",
    "@types/jasmine": "2.6.0",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.0.41",
    "codelyzer": "3.2.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "ts-node": "3.3.0",
    "tslint": "5.7.0",
    "typescript": "2.5.3"
  }`

**Comment by vlio20** [comment]
I am not sure that I understand the bug. please elaborate

**Comment by MerkulovDev** [comment]
instaled datepicker. imported in module. trying to run project and got this error
`Metadata version mismatch for module /projectFolder/node_modules/ng2-date-picker/index.d.ts, found version 4, expected 3, resolving symbol...`

**Comment by vlio20** [comment]
I will need a stackblitz

**Comment by mdarfilal** [comment]
I got the same error today, 
when passing node 6.9.4 to 8.9.4 
npm 3.10.10 to 5.6.0

**Comment by vlio20** [comment]
Please provide a stackblitz

**Comment by denispodtykan** [comment]
I have the same error on the version of angular 4.2.4, if I run on 5.2.0 all is well

**Comment by vlio20** [comment]
@denispodtykan thanks... If anyone can help with that would be great.

**Comment by denispodtykan** [comment]
I found a strange way to solve
In the folder /node_modules/ng2-date-picker/ I replaced all occurrences of **"version": 4** to **"version": 3**
and it all worked for me, I do not know how right it is

**Comment by vlio20** [comment]
It is auto-generated, so we need a more deterministic solution

**Comment by denispodtykan** [comment]
Of course, therefore, and pointed out that this is not entirely a solution)

Now I tried to change the version from 2.7.3 to 1.4.3 all worked correctly

**Comment by vlio20** [comment]
The question is: is there a way to make the date picker backward compatible to version less than ng5

**Comment by uweDuesing** [comment]
@mdarfilal The problem with this approach is that in big complex projects simply upgrading everything is a huge task

**Comment by uweDuesing** [comment]
I have the same problem and I agree with vlio20, the date picker needs to be backwards compatible.

**Comment by MerkulovDev** [comment]
I cant upgrade angular to v5 because a have many modules and there dependencies that would not work on v5.

**Comment by vlio20** [comment]
@MerkulovDev please use version 2.6.2

**Comment by MerkulovDev** [comment]
yes. i've tried 2.6.2 but some options is not working. i will try 2.6.2 now

**Comment by MerkulovDev** [comment]
in 2.6.2 everything is worse 
`
 Type '{ firstDayOfWeek: "mo"; monthFormat: string; disableKeypress: false; allowMultiSelect: false; clo...' is not assignable to type 'IDatePickerConfig'.
`

**Comment by vlio20** [comment]
@MerkulovDev, please open a different issue, and provide a stackblitz for the issue that you having 2.6.2

**Comment by vlio20** [comment]
@MerkulovDev , @uweDuesing, @mdarfilal , @denispodtykan I have just deployed 2.7.4-alpha version could you please try it out and let me know if it works for?

**Comment by nitinsh99** [comment]
I was also getting this error which seem to have been **resolved** for me in 2.7.4-alpha.

`ERROR in Error: Metadata version mismatch for module .node_modules/ng2-date-picker/index.d.ts, found version 4, expected 3, 
`
Thank you for fixing this.

**Comment by vlio20** [comment]
@nitinsh99 thanks. I will wait for few more replies and will publish a stable version

**Comment by vlio20** [comment]
@MerkulovDev , @uweDuesing, @mdarfilal , @denispodtykan any updates?

**Comment by mdarfilal** [comment]
@vlio20 
Since this issue I updated my angular/node/date-picker version to latest.
I juste try the version 2.7.4-alpha, results as follow : 

- angular 5.2.0
- node 8.9.4
- npm 5.6
=> OK

- angular 4.2.4
- node 8.9.4
- npm 5.6
=> OK

**Comment by vlio20** [comment]
Awesome, will make a new release soon

**Comment by vlio20** [comment]
should be fixed in 2.7.4
