### ISSUE TITLE
Selecting same month of same year set the date to undefined 

### ISSUE THREAD

**Issue by upendrasengarmbwk** [vlio20/angular-datepicker#344]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [X] Provide a **minimal code snippet**, please make sure it is well formatted.
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

Having issue using month picker when i select same month it sets the month to be undefined, after debugging in library found that `date.selected` is true if we select same month as already selected so it returns `[]`.

Is it known issue ? please revert.

```
 UtilsService.prototype.updateSelected = function (isMultiple, currentlySelected, date, granularity) {
        if (granularity === void 0) { granularity = 'day'; }
        var isSelected = !date.selected;
        if (isMultiple) {
            return isSelected
                ? currentlySelected.concat([date.date])
                : currentlySelected.filter(function (d) { return !d.isSame(date.date, granularity); });
        }
        else {
            return isSelected ? [date.date] : [];
        }
    };
```

**Comment by vlio20** [comment]
could you please create a stackblitz?

**Comment by upendrasengarmbwk** [comment]
@vlio20 I think after creating stackblitz demo, I've understood the concept. it is to deselect the selected month if you again click the selected month.

Can you please tell how to stop this behaviour like I don't want to deselect if month is already selected.

https://stackblitz.com/edit/angular-kheex4?file=app%2Fapp.component.html

**Comment by vlio20** [comment]
sure: use `unSelectOnClick: false`

**Comment by upendrasengarmbwk** [comment]
No luck this doesn't work out. @vlio20

**Comment by vlio20** [comment]
you will need to upgrade to 2.7.3 version in order to receive this feature:
https://stackblitz.com/edit/angular-pvnqgx

**Comment by vlio20** [comment]
@upendrasengarmbwk, did it help?

**Comment by upendrasengarmbwk** [comment]
@vlio20 Yes upgrading to 2.7.3 solves my problem but AOT build fails with updated date picker with the message.

> 
> ERROR in Metadata version mismatch for module /home/upendrasengar/node_modules/ng2-date-picker/common/types/single-calendar-value.d.ts, found version 4, expected 3
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './../compiled/src/app/app.module.ngfactory' in '/home/upendrasengar/project/src'
>  @ ./src/main.ts 3:0-80


Angular version using - 4.2.6

**Comment by vlio20** [comment]
for this error, please see:  #343. Currently version 2.7.x works only with ng5

**Comment by upendrasengarmbwk** [comment]
@vlio20 

How can I recreate a date picker once it is initialised? I want to change min/max property from config object based on the selection of start date, disable dates in the end date picker.
