### ISSUE TITLE
Disable different dates

### ISSUE THREAD

**Issue by ThalesMatoso** [vlio20/angular-datepicker#345]
Sorry my english.

I need to block specific dates that have already been selected, for example days 22-25-26 are disabled and days 23 and 24 can be selected.

I have searched the documentation and found nothing relevant, can you give me a hand?

Calendar Image
![image](https://user-images.githubusercontent.com/20910274/35224066-e1d1d9d8-ff6a-11e7-91cb-91df4d75b99e.png)

Calendar Code
![image](https://user-images.githubusercontent.com/20910274/35224218-5f8e874a-ff6b-11e7-9322-f9a8be248752.png)

Calendar Config
`this.datePickerConfig = {
      returnedValueType: ECalendarValue.StringArr,
      allowMultiSelect: true,
      format: 'YYYY-MM-DD',
      min: moment().format('YYYY-MM-DD'),
      enableMonthSelector: false
    };`

**Comment by vlio20** [comment]
you will probably have to remove the selected days within your application.

**Comment by ThalesMatoso** [comment]
If I remove the user will not be left without the information that day has already been selected?

**Comment by vlio20** [comment]
But the same will happen ( the user will not be left without the information that day has already been selected) if the component will remove it for him

**Comment by ThalesMatoso** [comment]
I do not understand, how to remove the information? Do you have an example to give me?

**Comment by ThalesMatoso** [comment]
The value `unSelectOnClick: false` worked in DatePickerConfig as false, but I can not change the DatePickerConfig dynamically, it does not accept change of configuration once created

has Solution?

**Comment by ThalesMatoso** [comment]
Changing only the object does not work, is it necessary or is there any event to accomplish this? I have a search in your example code you do per event, but there is a `ga` variable that I could not find in your service.

**Comment by vlio20** [comment]
it does works, it works in the demo page. you can look there.

**Comment by ThalesMatoso** [comment]
Excuse me for this being annoying is because in my case it's giving problem look the way I'm doing

I import the variable at the beginning of the project
```
  public datePickerConfig: IDatePickerConfig = {
    returnedValueType: ECalendarValue.StringArr,
    allowMultiSelect: true,
    format: 'YYYY-MM-DD',
    min: moment().format('YYYY-MM-DD'),
    enableMonthSelector: false,
  };
```
I have a `init ()` function inside the constructor that starts my searches, inside the `init ()` function I call another that searches all the dates in the database and after I have all the dates I do this:

```
        this.selectedDates = selectedDates;
        this.existingDates = selectedDates;
        this.datePickerConfig.unSelectOnClick = false;
```
My idea is to block all the dates that are already selected, not allowing the user to uncheck them or mark others on the same day.


But it does not work, it seems to me that when the html is already loaded the settings do not work and this is a big problem for me, since it is necessary to go to the database to get all these dates.

How can I use your plugin to solve my real problem which is:

BLOCK THE DATE IMPOSSIBILITATING CHANGES BY LEAVING ENABLE TO CHANGE DATES NOT ALIGNED.

**Comment by vlio20** [comment]
It would be great to have it in a stackblitz demo

**Comment by ThalesMatoso** [comment]
I do not know how to work with this because of the importantions, would you have some blank example with everything necessary to turn the angular?

**Comment by vlio20** [comment]
sure: https://stackblitz.com/edit/angular-pvnqgx

**Comment by ThalesMatoso** [comment]
In this example, the dates already marked are not appearing [https://stackblitz.com/edit/angular-cqb7h5](https://stackblitz.com/edit/angular-cqb7h5)

**Comment by ThalesMatoso** [comment]
In my example I need the dates "2018-01-23", "2018-01-24", "2018-01-25", "2018-01-26", "2018-01-27" to be blocked without the release and other dates without this being able to enable and disable them, you understand?

**Comment by vlio20** [comment]
you can change the example as you like

**Comment by ThalesMatoso** [comment]
I have already edited and it is identical to mine and what I need to do is not working.


I have succeeded in reproducing the problem, there is no error but it does not happen what I need. Can you help me with the goal? Or is this functionality not working with your plugin?

**Comment by renanmoraes** [comment]
A question because in this example when the values ​​are not in the constructor it is not marked?

https://stackblitz.com/edit/angular-cqb7h5?file=app%2Fapp.component.ts

**Comment by vlio20** [comment]
@ThalesMatoso, sorry I think that I am not getting you clearly. 
@renanmoraes, please see this example: https://stackblitz.com/edit/angular-uhrtyx
