### ISSUE TITLE
Disable specific dates

### ISSUE THREAD

**Issue by renanmoraes** [vlio20/angular-datepicker#346]
The plugin of the possibility to disable some dates for example I give him an array of dates ["2018-01-23", "2018-01-24"] and these dates are unavailable to be selected. Can I do this with your plugin?

**Comment by renanmoraes** [comment]
I've been visiting the doubts, and I noticed that you have a lot of problems with this, is not it a time to make available some related example, or to implement this functionality (logical in the face of possibilities)?

**Comment by vlio20** [comment]
you should use `isDayDisabledCallback` more info found in the documentation

**Comment by renanmoraes** [comment]
I would have an example, because the documentation for me is empty, I know he gives me the return, but I do not know how to pass the information to him, please give me a mini example of how you would use this?

**Comment by vlio20** [comment]
```
config = {
  isDayDisabledCallback: (day: Moment) => {
     ...
      return  // true or false according to your logic
   }
}
```

**Comment by vlio20** [comment]
@renanmoraes, your ⭐️ would be much appriciated
