### ISSUE TITLE
Is there any way to make weekend dates unselectable?

### ISSUE THREAD

**Issue by ankushgoyal27** [vlio20/angular-datepicker#348]
I am using inline day calendar.

<dp-day-calendar [(ngModel)]="selectedDate" [config]="config" [theme]="theme"></dp-day-calendar>

According to requirement, i want to make weekend dates unselectable.

Is there any configuration available to make this scenario working.

Thanks

**Comment by vlio20** [comment]
sure: 
```
config = {
  isDayDisabledCallback: (day: Moment) => {
     ...
      return  // true or false according to your logic
   }
}
```

For disabling you could use: https://momentjs.com/docs/#/plugins/moment-business/

**Comment by ankushgoyal27** [comment]
Thanks a lot. It is working as required.

**Comment by vlio20** [comment]
You ⭐️ would be much appreciated
