### ISSUE TITLE
Not able to change min config of second datepickcer based on value of first datepicker

### ISSUE THREAD

**Issue by shriniwassurve** [vlio20/angular-datepicker#354]
I have  been trying to implement  this 'to and from month picker'. But i am not able to change min configuration on second month picker based on the value of first month picker.   Please tell me what I am doing wrong.

This is the stackblitz:
https://stackblitz.com/edit/angular-rqxzjv-changeminconfig-dynamically

**Comment by vlio20** [comment]
check this - https://stackblitz.com/edit/angular-rqxzjv-changeminconfig-dynamically-9etwfw?file=app%2Fapp.component.ts

You need to update the reference to the config file and not mutate the config object.
