### ISSUE TITLE
Add min as an attribute

### ISSUE THREAD

**Issue by cen1** [vlio20/angular-datepicker#365]
Sometimes you want to use `min` config dynamically. Let's say you have two datepickers and the second one should have min=firstOne, so you can only pick bigger dates (eg. depature, arrival). In case like this, binding such as [min]="firstDatepicker.date" would be a welcome addition.

Right now I tried to workaround with 
```
focus() {
        this.config.min = this._minDate;
}
```
but it doesn't seem like I can manipulate the config dynamically (this._minDate is an @Input one way bind to first datepicker).

**Comment by vlio20** [comment]
you can do it easley by update the configuration object like so:

```
wantToChangeTheMin(min) {
      this.datePickerConfig = {
            ...this.datePickerConfig,
            min: min
      }
}
```

**Comment by cen1** [comment]
Yeah, changing just the one attribute did not trigger the change. Updating the whole config makes it work, many thanks!

Altho when I tried to do some crazy stuff like
```
this._minDate = this._minDate.add(1, 'day');
this.config.min=this._minDate;
```

it suddenly started to shift by a day on each focus. I am guessing some Angular binding exotics at work..

**Comment by vlio20** [comment]
You should not access the component in ways that are not mentioned in the documentation.

BTW your star would be appreciated :)
