### ISSUE TITLE
set isDayDisabled dynamically

### ISSUE THREAD

**Issue by molikh** [vlio20/angular-datepicker#370]
[X] question
Is there any way that I can set disabled days after page loaded?
user opens the page then select an item , after that i call an api to get disabled days.
Is there anyway to do this? (using isDayDisabledCallback).
I have tried to change config after i have called api , but it's not working.

**Comment by vlio20** [comment]
The isDayDisabledCallback is perfect for that. Isn't it working for you?

**Comment by molikh** [comment]
it works if I set that before page load but after that it's  not working.
I get it work with a trick.
I set an *ngIf="apiLoaded" for date-picker element which is false at first, then when i get result from api , set 'apiLoaded' = true , so component loads again in my page and config reset again and everything works perfect.
but without this trick, nothing happens if i only change config.

**Comment by vlio20** [comment]
Please post the code you have, I will try to assist. Please post it on stackblitz

**Comment by molikh** [comment]
example code: 
https://stackblitz.com/edit/angular-eam1hw

**Comment by vlio20** [comment]
here you go:

https://stackblitz.com/edit/angular-gseeni?file=app/app.component.ts

Please see line 31.

You should be using arrow function instead of plain function inside the setTimoute.

Let me know if it helps.

**Comment by vlio20** [comment]
closing for now

**Comment by molikh** [comment]
yes , it's working.
thanks a lot.

**Comment by vlio20** [comment]
Your ⭐️ would be much appreciated
