### ISSUE TITLE
[New feature] Usable API while using Directive

### ISSUE THREAD

**Issue by pbialy** [vlio20/angular-datepicker#375]
Maybe I missed something, but I can't find a way to manually trigger "close" while using the datepicker in the "Directive" mode, so with something like
`<input [dpDayPicker]="config">`.

My best try was to handle it in a way like this:
`<input #ref [dpDayPicker]="config" (blur)="onBlur(ref)">`.
and then:
```
  public onBlur(ref): void {
    const datepickerElement = ref.parentElement.querySelector('dp-date-picker').querySelector('div.dp-open');
    if (datepickerElement) {
      datepickerElement.classList.remove('dp-open');
    }
  }
```

but it's not always working, and also it's a hacky way.

So - is there a way to call API method in this mode?
If no - maybe it would be good to add something like:
`<input [dpDayPicker]="config" [dpDayPickerAPI]="apiHandler">`.
so one will be able to hadle api calls this way:
```
apiHandler = {
  open: () => {console.log('attempted to open');}
  close: () => {console.log('attempted to close');}
}
```

**Comment by vlio20** [comment]
You already have such apis, look for api in the documentation. you can also see the demo page source code to see how it is done with directive,

**Comment by pbialy** [comment]
Thanks for response and for giving a tip on how to find the solution.
Looks like `#dateDirectivePicker` is the solution for my problem.
It's not in the docs however, I found it in demo's source code, as You suggested.

Maybe it would be a good idea to add info about it to docs?

I created a pull request:
https://github.com/vlio20/angular-datepicker/pull/376
Please consider merging it :)
