### ISSUE TITLE
Use UTC time instead of local time

### ISSUE THREAD

**Issue by zpb210** [vlio20/angular-datepicker#378]
Hi,

I am looking into view/select dates that are in UTC time instead of local time. Any thoughts on this?

I spent a couple days learning your architect and set the times to UTC in the utils.service.convertFromMomentArray() method. A code snippet is below. This correctly works the first time you select a date on the calendar. The displayed time will be the current time in UTC. However, on the second click on the calendar, the calendar logic offsets the current time by the difference the local time is to UTC. I have not figured out how to prevent the offsetting from happening. Any insight? Thanks again!

```
utils.service.convertFromMomentArray(format: string, value: Moment[], convertTo: ECalendarValue): CalendarValue {
    //convert to UTC         
    if(value[0] != null){
      for (let moment of value) {
        moment = moment.utc();
      }  
    }
...
}
```

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [x] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by vlio20** [comment]
There are many places that moment() is being used, I don't think that it would be easy to track the source of the issue. But I do see that it might be a requirement in some applications.

This should be configurable. and provided through configuration with should be set to default as local.

I suggest you to search every place that uses moment() and instead use `utils.getCurrentTime(config)`

**Comment by zb-oath** [comment]
Thank you for the quick response and insight.

I changed all (62) instances of `moment()` to `moment().utc()` and this indeed works. So, adding the configuration will also work.

**Comment by zpb210** [comment]
Thank you for the quick response and insight.

I changed all 62 instances of `moment()` to `moment().utc()` and this indeed works. So, adding the configuration will also work.

**Comment by vlio20** [comment]
@zpb210, did you make it with some util method?

**Comment by zpb210** [comment]
I am working on the utility part now. This is what I was thinking:

1. In IConfig, add a new field: `timezone?: string`.
  - Initially, "local" and "utc" are the only valid timezones since the [moment timezone package](https://momentjs.com/timezone/) is not currently included with the picker.

2. In utils.service, add a new method with the following signature: `getCurrentTime(config: IDayCalendarConfig): Moment`

3. In all the places that call moment(), use `utils.service.getCurrentTime(config)` instead.
  - Currently, I am not for sure how I will get a handle on the config in all the various places.

What are your thoughts?

**Comment by vlio20** [comment]
1. Please provide an enum for the options.
2. Get current time is ok, but it should only receive the timezone, not the whole config.
3. The method should be static.

**Comment by cyates81** [comment]
I would just like to add my support for this feature request, however, as @vlio20 mentioned it should be configurable.  In my case, I want to always show a specific time zone.  When I use moment-timezone the time displayed shows the offset of the intended timezone.  For example, I'm in mountain time at 10:30 AM, I use moment().tz('America/New_York') for the minimum date setting which is UTC-4:00 and the calendar uses 4:30 PM as the minimum time, which is EST 12:30 PM plus 4 hours.

Thank you for all your work on this awesome control.

**Comment by vlio20** [comment]
thanks @cyates81

**Comment by vlio20** [comment]
Any updates on this one?

**Comment by coffeymatt** [comment]
I'd love to find a date picker that supports UTC/timezone free dates but every library I've found so far just has it in the backlog. So yea, just adding my voice to the request, as my current work arounds are rather hacky.

**Comment by vlio20** [comment]
@zpb210 long time since this issue was opened but I think that it would be possible to do what you is asking for. As the calendar is now using Dayjs under the hood, you will just need to set the required timezone like described in the Dayjs documentation:
https://day.js.org/docs/en/timezone/timezone

@cyates81 & @coffeymatt you might find it also interesting
