### ISSUE TITLE
How to recreate date picker with new config?

### ISSUE THREAD

**Issue by upendrasengarmbwk** [vlio20/angular-datepicker#379]
How can I recreate a date picker once it is initialised? I want to change min/max property from config object based on the selection of start date disable dates in the end date picker.

- [ x] Provide a **minimal code snippet**, please make sure it is well formatted.
- [x ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ x] Provide **screenshots** where appropriate
- [ 2.7.5] What's the **version** of Angular you're using?
- [x ] Does this occur on specific browser?

**Comment by vlio20** [comment]
Same as here  #375.
I'll need to update the config file. 

Let me know if it works for you.
