### ISSUE TITLE
Feature request: Custom Theme

### ISSUE THREAD

**Issue by wernerva** [vlio20/angular-datepicker#380]
Hello,

Currently this component allows only a choice of no theme or dp-material.

It would be great if one could create a custom scss theme configuration in order to set colours and component part sizes.

The particular problem I have is that I'd like to increase the size of the month calendar (dp-month-calendar)

**Comment by vlio20** [comment]
Hi,
You can create any theme you want with plain css.

**Comment by Romko775** [comment]
Hi! Can you make a little sample of how to pass class to popup and how to style input? I tried, but only shifts all the form.

<dp-date-picker #datePicker
                  [config]="config"
                  [theme]="'dp-main'"
                  [mode]="'month'">

**Comment by vlio20** [comment]
There is no "Theme", you can style it in any way you want with plain css
