### ISSUE TITLE
Not bind to formatted value

### ISSUE THREAD

**Issue by wgf4242** [vlio20/angular-datepicker#384]
`  datePickerConfig = {'format': 'YYYY-MM-DD' , 'firstDayOfWeek':'mo'};
`
`<dp-date-picker required [(ngModel)]="object.date" name="date" [config]="datePickerConfig"></dp-date-picker>`
![20180328160619](https://user-images.githubusercontent.com/3336626/38017324-48a55b32-32a4-11e8-9af8-b0987b076bd3.png)
I need value format like 'YYYY-MM-DD'.

**Comment by vlio20** [comment]
Please provide a stackblitz

**Comment by wgf4242** [comment]
https://stackblitz.com/edit/ng-datepicker-test

If bind a initial formatted string to dp-date-picker, string shows like that.

**Comment by vlio20** [comment]
Looks like a bug. Will take a deeper look in the next few days.

**Comment by vlio20** [comment]
resolved in d389c96.
Will be available in the next release (2.10.1). @wgf4242 thanks for opening this issue.
