### ISSUE TITLE
Can we override CSS

### ISSUE THREAD

**Issue by rrohitesh** [vlio20/angular-datepicker#388]
Hello All,

I am trying to modify the default css e.g: for the datepicker componet i want to change the width which i am doing like:

.dp-day-calendar .dp-day-calendar-container {
    background: #FFFFFF;
    width: 40vw !important;
}

But, the changes are not reflecting can you please let me know whether overriding of css is possible?

**Comment by vlio20** [comment]
I would happy to help. Please post a stackblitz with what you are trying to achieve.

**Comment by vlio20** [comment]
closing for now
