### ISSUE TITLE
IE 10 monthpicker remains open by default and does not toggle

### ISSUE THREAD

**Issue by abhishekakj33** [vlio20/angular-datepicker#392]
![calendar](https://user-images.githubusercontent.com/11902561/38892899-9506d0c0-4256-11e8-92b6-2c72b476c09e.PNG)

- Angular Version 5.0.0
-  IE 10

**Comment by mrenou** [comment]
You have an IE10 mention in README

Compatibility
Internet Explorer 10:
Internet explorer 10 doesn't support hidden attribut, but you can use a css rule on data-hidden to hide date picker components:

[data-hidden="true"] {
  display: none !important;
}

**Comment by vlio20** [comment]
thanks @mrenou
