### ISSUE TITLE
Font issue in all iPhone Devices

### ISSUE THREAD

**Issue by hiren1217** [vlio20/angular-datepicker#394]
Font weight gets lighter in all iPhone devices.
Font style i am using is roboto regular.

**Comment by vlio20** [comment]
Please share a screen shot

**Comment by hiren1217** [comment]
Dear sir ,
Please reply ASAP

**Comment by vlio20** [comment]
@hiren1217 , you understand that this is an open source project - right?

**Comment by hiren1217** [comment]
no.. its not ...

**Comment by hiren1217** [comment]
i tried doing fonts dark using css but there was no effect on real device(iphone)
