### ISSUE TITLE
date picker config: closeOnSelect is ignored when unSelectOnClick is false

### ISSUE THREAD

**Issue by oritm84** [vlio20/angular-datepicker#397]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [x] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

foo.ts
```javascript
//...
private config = {
  unSelectOnClick: false,
  closeOnSelect: true,
}
//...
```

foo.html
```html
<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig"></dp-date-picker>
```

I believe that when `unSelectOnClick == false` and `closeOnSelect == true` clicking on the currently selected item should close the popup, as the current behavior is not consistent.

The source of the issue is that `DayCalendarComponent .dayClicked` returns early when `unSelectOnClick == false`.
Moving the `unSelectOnClick` logic deeper into `UtilsService.updateSelected` should solve this issue.

**Comment by vlio20** [comment]
could you please provide a stackblitz? would be easier for me to see it in action

**Comment by vlio20** [comment]
closing for now
