### ISSUE TITLE
How to pre select multiple dates. Please Replay ASAP.

### ISSUE THREAD

**Issue by logicalravii** [vlio20/angular-datepicker#399]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by vlio20** [comment]
This is an open source project there are no option to replay ASAP.
