### ISSUE TITLE
Build errors when `fullTemplateTypeCheck` is enabled

### ISSUE THREAD

**Issue by sirajc** [vlio20/angular-datepicker#400]
- [x ] What's the **version** of Angular you're using?
Angular 6
- [ x] Does this occur on specific browser?
This occurs during build

When we add `fullTemplateTypeCheck": true` in `angularCompilerOptions` of tsconfig.json and run build, following error is thrown
```
../../node_modules/ng2-date-picker/ng2-date-picker.d.ts.DatePickerComponent.html(57,29): : Argument of type '"selection"' is not assignable to parameter of type 'SelectEvent'.
```

This happens because in https://github.com/vlio20/angular-datepicker/blob/master/src/app/date-picker/date-picker.component.html file because of `(onSelect)="dateSelected($event, 'day', 'selection')"`. Third parameter is passed as string and in component.ts file `SelectType` enum is expected

Solution would be to assign enum to local variable in component and use enum value through this enum variable in template

ref: https://coryrylan.com/blog/angular-tips-template-binding-with-static-types

Thanks

**Comment by sirajc** [comment]
@nileshbhagwat

**Comment by vlio20** [comment]
@sirajc , is it reproduced in latest version?

**Comment by vlio20** [comment]
closing for now
