### ISSUE TITLE
October Date being shown twice (28th Oct 2018, 27th Oct 2019)

### ISSUE THREAD

**Issue by itsphil** [vlio20/angular-datepicker#407]
**Angular**: 5.2.11
**ng2-date-picker**: 2.7.3

`{
            allowMultiSelect: true,
            disableKeypress: true,
            firstDayOfWeek: 'mo',
            format: 'YYYY-MM-DD',
            locale: null,
            min: moment(),
            max: moment().add(2, 'year'),
            theme: 'dp-material',
        }`

<img width="374" alt="screen shot 2018-06-01 at 09 21 58" src="https://user-images.githubusercontent.com/983400/40830213-b5fc02ce-657d-11e8-8a0b-25a6da2f828b.png">

**Comment by vlio20** [comment]
could you please see if upgrading to 2.9.0 fixes your issue?

**Comment by vlio20** [comment]
closing for now
