### ISSUE TITLE
Whenever we update the config to a new object the calendar navigates back to current month in daytime picker

### ISSUE THREAD

**Issue by iamramkey** [vlio20/angular-datepicker#409]
Hi Everyone,

After resolving [minDate/minTime](https://github.com/vlio20/angular-datepicker/issues/408) issue with @Maxsky5 comment. I am facing another issue which I mentioned in my last comment. I am able to select the updated fromDate on toDate calendar but what happened is that calendar is moving to the current month rather the selected month (only when min date or minTime changed). 

I am using date picker component in angular reactive forms also using ngFor to render component dynamically. So, I cannot use API method moveCalendar method to navigate to the selected date.

Please suggest me if I am doing any mistake or Am I missing anything.

Let me know if this is possible / How can I achieve in general the below case :
I need to update just min date & minTime but as angular won't trigger change detection, I am reassigning the same object by creating a duplicate to it. But I am using ag-grid in my application. It has input gridOptions a predefined class to pass required parameters to plot grid in the application. Whenever I update rowData property(which is part of gridOptions) of it It is going to redraw the grid data. How can I achieve the same here using date picker component/in my own custom component?

Thanks in advance

**Comment by vlio20** [comment]
hi @iamramkey , please provide a stackblitz

**Comment by vlio20** [comment]
It would be hard for me to help without a stackblitz.
