### ISSUE TITLE
unSelectOnClick and dpDayPicker directive

### ISSUE THREAD

**Issue by tzoratto** [vlio20/angular-datepicker#410]
Hi,
thanks for this awesome datepicker, I was struggling to find a datepicker with day and month mode !

I encountered a small bug (I think) though, when using the component `dp-date-picker` with ngModel everyhing is fine but when I use the directive `dpDayPicker` the way it's shown in the doc `<input name="someName" [(ngModel)]="selectedDate" [dpDayPicker]="config" />` even with no config at all, when I click a second time on the same month the input still contains the old selected month.

As I understand the intended behavior, when you click a first time on a month this month is selected (shown both in the input and on the month picker with material theme by a blue circle) and when you click again on the same month everything is reset (both the input and the month picker). In the directive case, the month picker is reset but not the input

I can provide more information if you need me to

thanks

**Comment by vlio20** [comment]
Could you please provide a stackblitz?

**Comment by vlio20** [comment]
@tzoratto ?

**Comment by tzoratto** [comment]
Sorry I was on vacation, I’ll try and do that this week

**Comment by tzoratto** [comment]
sorry for the delay...

here is a stackblitz to reproduce the issue :

https://stackblitz.com/edit/angular-5-example-2nv6px

**Comment by dgroh** [comment]
I can confirm this (or similar). When selecting the date twice, the `dp-selected` class is removed from the DOM element. This means. 

To reproduce:

1. select a date
2. open the datepicker again
3. select the same date you have selected before

The `dp-selected ` gets removed from the DOM.

**Comment by vlio20** [comment]
@tzoratto , is this still an issue?

**Comment by vlio20** [comment]
closing for now
