### ISSUE TITLE
ng2-datepicker hang the browser under certain circumstance

### ISSUE THREAD

**Issue by JLHwung** [vlio20/angular-datepicker#412]
ng2-datepicker will hang the browser when using `[ngModel]` and `(ngModelChange)` together. It is recommended to checkout the **stackblitz** demo [here](https://stackblitz.com/edit/angular-6c9mff?file=src/app/form-control-date.component.ts) as I use
```
viewProviders: [{
    provide: ControlContainer,
    useExisting: NgForm
  }]
```
to have `ng-date-picker` under a custom form control component. I know it is not some popular usage and the bug may be related to that.

I've tackled around the scenario and find that `ngModelChange` will constantly emitting `moment` instance, thus the event loop will ultimately consume all the memory and hang the miserable browser.

I use some dirty check as workaround:
```ts
datetimeChange($event) {
    if ($event !== undefined) {
      if ($event instanceof moment) {
        $event = $event.format(this.dateFormat);
      }
      if ($event !== this.previousValue) {
        this.ngModelChange.emit($event);
        this.previousValue = $event;
      }
    }
  }
```

- [x] Provide a **minimal code snippet**, please make sure it is well formatted.
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.

https://stackblitz.com/edit/angular-6c9mff?file=src/app/form-control-date.component.ts
- [x] Provide **screenshots** where appropriate
I expect the browser does not hang and the ngModelChange event is triggered only once after I select a date.
- [x] What's the **version** of Angular you're using?   6.0.3
- [x] Does this occur on specific browser? Hang on all browsers

**Comment by vlio20** [comment]
thanks, will take a look asap

**Comment by vlio20** [comment]
I will take a look ASAP though there are some other things on the pipeline. If it's really urgent, consider reach via [Fiverr](https://www.fiverr.com/vladioffe/add-features-and-fix-bugs?arrived_from_manage_gigs=true&display_share=true).

**Comment by vlio20** [comment]
As you said this is very unpopular approach, I will close this for now.
