### ISSUE TITLE
weekDayFormatter doesn't work in day mode

### ISSUE THREAD

**Issue by clem4net** [vlio20/angular-datepicker#415]
https://github.com/vlio20/angular-datepicker/blob/75abe90cf7d19f6078a70f3d9677ac1d0479ce10/src/app/date-picker/date-picker.service.ts#L62

Method DatePickerService.getDayConfigService(...)
=> the weekDayFormatter properties is not in the result.

So, the weekDayFormatter is never used.

Thanks

**Comment by vlio20** [comment]
Please provide as stackblitz

**Comment by Felttrip** [comment]
@vlio20 I'm having the same issue, I would expect the `weekDayFormatter` config option to also work with `dp-date-picker`
stackblitz showing the issue here https://stackblitz.com/edit/angular-ewx1wb

**Comment by vlio20** [comment]
thanks, I will take a look asap

**Comment by vlio20** [comment]
I will take a look ASAP though there are some other things on the pipeline. If it's really urgent, consider reach via [Fiverr](https://www.fiverr.com/vladioffe/add-features-and-fix-bugs?arrived_from_manage_gigs=true&display_share=true).

**Comment by vlio20** [comment]
resolved in b09964c and will be available in version 8.0.0
