### ISSUE TITLE
DatePicker in Reactive Forms

### ISSUE THREAD

**Issue by ChristianGalvez23** [vlio20/angular-datepicker#416]
I have DatePicker installed in my app which is using Reactive Forms Paradigm.
I was building a view where I put this component as control, so, I came across that formControlDirective and the component don't work together, because I need to disable the component programmatically when certain conditions happen.

1. I tried to set "disabled" formcontrol property to true/false and doesn't work.
2. I tried to invoke "disable" method from DatePicker Component and this worked nice!

Nevertheless, the datepicker input doesn't change its appearence when I enabled the datepicker component or viceversa. To achieve the earlier behavior I have to click in the component and is like it was sleeping and when it wakes up it changes its appearence.

Check this out:
https://angular-p987mi.stackblitz.io
https://stackblitz.com/edit/angular-p987mi

Is DateTimePicker Component working well with Reactive Forms?

**Comment by vlio20** [comment]
> Is DateTimePicker Component working well with Reactive Forms?
It should, if not, than it is an issue that needs to be resolved. 

I will take a look asap.

**Comment by vlio20** [comment]
There are some other things on the pipeline. If it's really urgent, consider reach via [Fiverr](https://www.fiverr.com/vladioffe/add-features-and-fix-bugs?arrived_from_manage_gigs=true&display_share=true).

**Comment by vlio20** [comment]
Fixed in 5e18e22 will be available in version 8.0.0
