### ISSUE TITLE
question about Formats

### ISSUE THREAD

**Issue by nico281** [vlio20/angular-datepicker#417]
Hi, im making a form builder and i need to change the format in a configuration but the changes to the config are not being reflected on the input. only after reload the page. there is a way to tell the directive to update the format?
Cheers

**Comment by vlio20** [comment]
It would be easier to have a stackblitz, so please post one and I will try to help.

**Comment by nico281** [comment]
https://stackblitz.com/edit/angular-maohqz
my idea is to have the ability to change the format on runtime.
If you look at the example, i set a default format but if i change the config format, the input still continue showing the default format and not the updated one.

**Comment by marcelcremer** [comment]
Hey,

I have the same issue - thx @nico281 for creating the stackblitz. 

I want to add, that the same is true when the object changes (which triggers ng change detection).

Forked stackblitz as demo:

https://stackblitz.com/edit/angular-gftrbi?file=src%2Fapp%2Fapp.component.ts

**Comment by vlio20** [comment]
Will mark as bug...
Will take a look shortly. There are some other things on the pipeline though. If it's really urgent, consider reach via [Fiverr](https://www.fiverr.com/vladioffe/add-features-and-fix-bugs?arrived_from_manage_gigs=true&display_share=true).

**Comment by marcelcremer** [comment]
Thank you @vlio20, if I get into it, I might also send a PR. Unfortunately, I'm having a deadline this week, so maybe I can spend time on it next week.

**Comment by vlio20** [comment]
it's working, you shouldn't change it inline:
https://stackblitz.com/edit/angular-vh88mz?file=src/app/app.component.ts
