### ISSUE TITLE
question about Input Text Mask

### ISSUE THREAD

**Issue by Romko775** [vlio20/angular-datepicker#418]
Hi, just wonder if it is possible to put on input a mask like ' **\d\d / \d\d / \d\d\d\d** ' or ' **99/99/9999** '. Tried to use vanilla text mask [https://github.com/text-mask/text-mask/tree/master/vanilla], but it cannot find input, used querySelector and used @ViewChild.
**html**
`<dp-date-picker #input>
  </dp-date-picker>`

**ts**
`dateMask = [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/];
maskedInputController;
@ViewChild('input', {read: ElementRef})
  input;
ngAfterViewInit(): void {
    setTimeout(() => {
      this.maskedInputController = textMask.maskInput({
        inputElement: this.input.nativeElement,
        placeholderChar: '\u2000',
        mask: this.dateMask
      });
    });
  }`

Cheers

**Comment by vlio20** [comment]
Nope, no support for input masks for now

**Comment by vlio20** [comment]
I suggest you to try:
https://css-tricks.com/input-masking/
