### ISSUE TITLE
The datepicker does not update `ng-untouched` class after user selects date string

### ISSUE THREAD

**Issue by JLHwung** [vlio20/angular-datepicker#426]
The datepicker should set its `class` attribute to include `ng-touched` after the user has interacted with the datepicker.

- [x] Provide a **minimal code snippet**, please make sure it is well formatted. See below
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug. https://stackblitz.com/edit/angular-datepicker-example?file=src%2Fapp%2Fapp.component.css
- [ ] Provide **screenshots** where appropriate
- [x] What's the **version** of Angular you're using?  v6
- [x] Does this occur on specific browser? Every browser

**Comment by vlio20** [comment]
resolved in 86ba0a6.
Thanks @JLHwung

**Comment by JLHwung** [comment]
Cool. Would like to see this get published to npm soon.
