### ISSUE TITLE
Missing Dates Bug!!!

### ISSUE THREAD

**Issue by Avishaidev** [vlio20/angular-datepicker#427]
Open the picker on March 1990 see dates from 24 then missinig 25 and 27 how its acceptable????

**Comment by vlio20** [comment]
Will take a look ASAP

**Comment by Avishaidev** [comment]
Please help to fix it i have a very big project on production.
Thanks

**Comment by Avishaidev** [comment]
in file: ng2-date-picker.es5.js
Line: 659
Code:
`if (current.format('HH') !== '00') {
                current.startOf('day').add(1, 'day');
            }`

What is the if condition meaning to?
Because if i remove this "if" block bug are fixed.

**Comment by vlio20** [comment]
As far as I remember it solves another issue in the calendar. Try to remove and look for for months in 2017.

**Comment by Avishaidev** [comment]
I removed and checked all 2017 months everything are ok.

**Comment by vlio20** [comment]
try to PR. let's see if all tests are passing.
Please push your PR to next branch

**Comment by Avishaidev** [comment]
Sorry i don't know how to do this.
Change are in src/app/day-calendar/day-calendar.service.ts
Line: 89-91
fixed: remove this lines
code to remove:
`if (current.format('HH') !== '00') {
          current.startOf('day').add(1, 'day');
        }`

**Comment by vlio20** [comment]
I will do it later today.

Thanks.

**Comment by vlio20** [comment]
resolved in e41ad9b will be available later today in version 2.10.2. Thanks again
