### ISSUE TITLE
Date 4 and 6 are missing from the Month of November 2018

### ISSUE THREAD

**Issue by shuvrodeb-kar** [vlio20/angular-datepicker#432]
**ng2-date-picker version**; 2.9.0
**Angular version:** 5.2.0
**Browser**: All browser.
**Windows**: 10
**Code Snippet**: <dp-date-picker name="mydateFrom" #dayPickerFrom [(ngModel)]="dateTimeModel.fromDate" [config]="datePickerConfig" [disabled]="disableDateSelection"></dp-date-picker>

![33](https://user-images.githubusercontent.com/6039535/46201545-3d5dae00-c336-11e8-8029-01f2e6c51716.png)

One of our user is complaining that she cannot see the date 4 and 6 from the month of November. We cannot reproduce the issue but the user is always able to reproduce the issue from her end.

Can you please advise us what could be the root of this issue?

**Comment by vlio20** [comment]
@shuvrodeb-kar,  maybe it is related to her locale. Can you provide this information?

**Comment by vlio20** [comment]
The locale of the user

**Comment by shuvrodeb-kar** [comment]
![image005](https://user-images.githubusercontent.com/6039535/46391766-51bbf500-c700-11e8-9ccf-67eb2a86e6a2.jpg)

**Comment by vlio20** [comment]
@shuvrodeb-kar, what is your locale? do you experience the same issue?

**Comment by shuvrodeb-kar** [comment]
Sorry, we also could not reproduce it. 

But, have you tested on ng2-date-picker version; 2.9.0?

This version we have used in our end. we just want align.

**Comment by vlio20** [comment]
Nope I didn't. But I suggest y to upgrade to latest version as there were some bug fixes related to dates display. Please let me know if it helped.

**Comment by vlio20** [comment]
closing for now
