### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by vlio20** [vlio20/angular-datepicker#434]
Add support for ng7

**Comment by ZihanTang** [comment]
HI vlio20, can I ask for the eta of Angualr 7 support ?

**Comment by vlio20** [comment]
Hi,
There no Eta. I planned to do it on my free time. If it's urgent, you can reach me via my fiverr account and I will give it a higher priority.

**Comment by vlio20** [comment]
available in version 2.11.0
