### ISSUE TITLE
[Feature Request] closeOnEnter

### ISSUE THREAD

**Issue by WaterBleu** [vlio20/angular-datepicker#438]
much like closeOnSelect, but when user hits enter key would close the calendar popup

**Comment by vlio20** [comment]
Sounds like you need to use the directive approach, does it solves your case?

**Comment by WaterBleu** [comment]
can solve with directive and listen on Enter of the input, this is more or less a correct behaviour ui/ux
I would consider putting into the component

**Comment by vlio20** [comment]
Sounds legit, you are welcome to create a PR. Currently I am working on other suff that is on the pipeline.

**Comment by vlio20** [comment]
resolved in da0fe4d
