### ISSUE TITLE
Set initial date and time for inline date-time calendar

### ISSUE THREAD

**Issue by fabsalito** [vlio20/angular-datepicker#439]
Hi,

Is there some way to set initial values for date and time for an inline date-time calendar?

I tried with displayDate but this is only for date and, on the other hand, the date was not highlighted.

Regards,

**Comment by vlio20** [comment]
What type of form are you using? Template or reactive?

**Comment by fabsalito** [comment]
Hi @vlio20,

I am using template. I made it work setting both, the displayDate and the ngModel value.

Regards,
