### ISSUE TITLE
[Feature Request] multiDaysDisabled 

### ISSUE THREAD

**Issue by zainkhwaja** [vlio20/angular-datepicker#440]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?
- [ * ] Feature Request?

Can we have something of a **multiDaysDisabled** thing?
Which takes an array of dates (moment) as argument and disables the rest of the calendar?

Also, if anyone can help me how the isDayDisabledCallback attribute works? 

TiA.

**Comment by vlio20** [comment]
The approach to do it is to use the isDisabled callback, this way you can apply any logic that you want.
