### ISSUE TITLE
IE11 needs to click twice to select the date

### ISSUE THREAD

**Issue by acejiyu** [vlio20/angular-datepicker#443]
In the case of using the placeholder attribute, IE 11 needs to click twice to select the date.
You can use IE 11 to access the homepage([angular-datepicker](https://vlio20.github.io/angular-datepicker/)) to reproduce this problem.

**Comment by vlio20** [comment]
As it seems like a very minor concern of the community of this library I will close this case for now. If there will be more people with the same problem I will reopen it. Sorry, for not taking care of this issue but my time is limited and I prefer to focus on other cases - Don't hesitate to PR.

**Comment by aishwaryardandi** [comment]
@vlio20 I am facing the same issue

**Comment by acejiyu** [comment]
> @vlio20 I am facing the same issue
> 
> @acejiyu were you able to find a way to overcome this?

The problem is caused by IE11's poor support for "placeholder".
There are currently two ways to solve:
1.Remove "placeholder" attribute.
2. Replace original "placeholder" with custom tags
HTML
```
<input placeholder="{{placeholder}}" *ngIf="!datePickerValue" class="customPlaceholder">
<dp-date-picker theme="dp-material" [(ngModel)="datePickerValue"]
```
CSS
```
.customPlaceholder {
 position: absolute;
 pointer-enents: none;
 background: none;
 border: none;
 z-index: 1;
}
```
Move the control to the appropriate position by style.
I solved it using 2 and hope it helps you.
