### ISSUE TITLE
Disable Selecting same selected Date

### ISSUE THREAD

**Issue by chaityashah** [vlio20/angular-datepicker#445]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [x] What's the **version** of Angular you're using?
- [x] Does this occur on specific browser?

**Comment by chaityashah** [comment]
We are using Angular version 4. And this is not browser specific.

**Comment by vlio20** [comment]
sounds like a feature request.

**Comment by chaityashah** [comment]
Hi,

I think this can be achieved through passing configuration "unSelectOnClick" false, which will not allow user to deselect current selected date. 

I tried that and it worked for me. 
Let me know if that configuration is for different purpose and have any other effect which I might not have noticed. 

Thanks.

**Comment by vlio20** [comment]
happy to hear that. The configuration is exactly for that. @chaityashah I will be happy if you could share a link or a screenshot of you usage of that component.
