### ISSUE TITLE
Datepicker dirty after init

### ISSUE THREAD

**Issue by house-md** [vlio20/angular-datepicker#446]
Hello,
In our project We are a experiencing problem with dirty datepicker right after it's initialized with data even when inner input is pristine.

Demo: **[Stackblitz](https://stackblitz.com/edit/angular-d5rgym)**
Screenshot: 
![image](https://user-images.githubusercontent.com/7100025/54027409-b8f33f00-41a1-11e9-8c87-ff53658e001b.png)

Angular version: **6.1.9 (demo is with version 7.2.8)**
Browser specific: **false**

------------------------------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [x] Provide **screenshots** where appropriate
- [x] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by DDeme** [comment]
I see the same problem in my project.

**Comment by vlio20** [comment]
Yes, I am was able to reproduce this issue. I will try to fix it soon. In the meantime PRs would be helpful.

**Comment by house-md** [comment]
@vlio20 any update on this? this bug is blocking us at some features

**Comment by vlio20** [comment]
Not really, didn't have time to work on this one. I would except PRs

**Comment by house-md** [comment]
@vlio20 Finally me and my colleague did a little bit of research and found a cause - https://github.com/angular/angular/issues/14988.

What is happening at first is that "**writeValues**" method is triggered with _null_ value which is in second call replaced with desired value which causes the change of status to dirty.

I am trying to work on PR but I am getting out of ideas on how to fix it.

**Comment by vlio20** [comment]
@house-md seems like this is an angular issue: https://github.com/angular/angular/issues/14988

**Comment by vlio20** [comment]
I will close this one until there will be a resolution from Angular side
