### ISSUE TITLE
month-picker implementation

### ISSUE THREAD

**Issue by Jagat-sdrc** [vlio20/angular-datepicker#447]
how to use month-picker, becoz there is no month-picker, only date-picker is available

**Comment by vlio20** [comment]
You can see that it is available in the demo. Let me know if you have a specific question.

**Comment by Jagat-sdrc** [comment]
There is no month-picker, there is only a month calendar. So if you are saying that there is month picker available in demo, requesting you kindly share me the snippet of that particular code. 

Thanks for you response @vlio20

**Comment by vlio20** [comment]
Here you go:
http://prntscr.com/n9f5m0

**Comment by Jagat-sdrc** [comment]
Requesting you to kindly share the code for month picker @vlio20

**Comment by vlio20** [comment]
Did you checkout the documentation?

**Comment by Jagat-sdrc** [comment]
Yes

**Comment by vlio20** [comment]
http://prntscr.com/na5sj9
