### ISSUE TITLE
how do I re initialise date picker with after updation in configuration ?

### ISSUE THREAD

**Issue by chirag97** [vlio20/angular-datepicker#448]
how do I re initialise the component with updated configuration of the date picker.
- I want to change the locale based on the api call and if the date picker loads with defalut locale then I want to update it and reinitialise the date picker.

**Comment by vlio20** [comment]
You need to reassign the configuration. Please post a stackblitz - it will help to help you

**Comment by keub** [comment]
here is a link to the problem.
the expected behavior is that the changes are taken into account when the configuration passed as an attribute of the picker date is modified
Thank you! Thank you!

**Comment by vlio20** [comment]
Here you go: 
https://stackblitz.com/edit/ng2-date-picker-ckvhhm?file=app/app.component.ts

Please give this repo a ⭐️
