### ISSUE TITLE
make date picker input read only 

### ISSUE THREAD

**Issue by sadra74** [vlio20/angular-datepicker#450]
I want to be able to make my input in my date picker read-only.
if I want to put it simply, I should say I want to have a date picker that does not have the ability of typing in. in other word I want the user to just use date-picker through clicks no keyboards.
if you are asking why I am doing this I should say I want this because I want to prevent a user from typing any invalid characters.  I would be very glad if you can help me.

**Comment by vlio20** [comment]
@sadra74 I would suggest you to use the component, and modify it with css to look like a button.
