### ISSUE TITLE
needs some information

### ISSUE THREAD

**Issue by chetanupreti** [vlio20/angular-datepicker#454]
how can I change date picker control value from moment object to Date format like "YYYY-MM-DD". we have requirement to save date in this format so any configuration.
how to set formcontrol value that date which we select.

**Comment by vlio20** [comment]
Yiu have such example.in the demo page.

**Comment by chetanupreti** [comment]
can you give some code snippt...I didn't understand how to do this task.

**Comment by chetanupreti** [comment]
in demo here is configuration for date formate. but I want to change value in form control of this component

**Comment by chetanupreti** [comment]
setValue("mm,dd,yyyy") in this way

**Comment by chetanupreti** [comment]
we have template driven forms
