### ISSUE TITLE
Option to use unformatted date (ISO)?

### ISSUE THREAD

**Issue by calchuchesta** [vlio20/angular-datepicker#457]
Is there any way I can make the datepicker use the ISO format internally? I want my input field to be formatted, but the actual value to be an ISO date.

**Comment by calchuchesta** [comment]
Nevermind, I had an "eureka" moment and realized setting the `format` option to an empty string works like a charm.

**Comment by vlio20** [comment]
Unfortunately not, you can use a moment object and then format it to whatever type you need
