### ISSUE TITLE
I am unable to modify style using CSS only

### ISSUE THREAD

**Issue by danchaseCTS** [vlio20/angular-datepicker#461]
Hi Vlad,

I'm trying to follow your previous advice to modify the style, simply using CSS - but I could not find the current class names, even in the source - I went to every file searching, and finally found some in the meta data. I then went to Chrome DevTools, and highlighted a date and clicked, it had a blue background. I then modified that value within DevTools, and saw it turn red! Great! Now I have the correct class.. But then when I tried to paste it into the .css, It does not apply:

dp-day-calendar.dp-material.dp-selected{background:red !important;color:#fff}

I would not have thought I'd need to search node_modules/ng2-date-picker, then find them under "esm5", then day-calendar.component.js, then scroll all the way down to styles: [], to find the names, and I've tried using !important, and putting the new definition into styles.css, as well as my component.css. 

What am I doing wrong, I'm pulling my hair out?

Thank you,
Dan Chase

**Comment by vlio20** [comment]
Hi Dan,
Hope you still have some hare. Be sure the the component you are using (the one that wraps the date picker) has the right encapsulation. It would me much easier if you could share a stackblitz.

**Comment by vlio20** [comment]
Checkout https://stackblitz.com/edit/angular-59nhpp?file=src/styles.css. You need to change it in your main css file
