### ISSUE TITLE
Selected month class (.dp-selected) not set

### ISSUE THREAD

**Issue by pvds** [vlio20/angular-datepicker#462]
When inspecting the month calendar html, the `dp-selected` class is missing on the currently selected month (`.dp-calendar-month`).

## Reproduce
1. Go to https://vlio20.github.io/angular-datepicker/#
2. Select a date in the day or day time picker
3. Go to the month calendar
4. Currently selected month button is missing  the `dp-selected` class

### Rendered view (would expect november to have selected styling)**
![image](https://user-images.githubusercontent.com/1928947/67361048-d5dd5680-f567-11e9-950e-f92344fc7147.png)

### Rendered html
![image](https://user-images.githubusercontent.com/1928947/67361193-366c9380-f568-11e9-85de-75dcbb1dea3a.png)

  
---
  
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [x] Provide **screenshots** where appropriate
- [x] What's the **version** of Angular you're using?  
**8.2.10**
- [x] Does this occur on specific browser?  
**No, tested with chrome 77 and firefox 69**

**Comment by vlio20** [comment]
thanks, I will try to have a look on that later.

**Comment by vlio20** [comment]
fixed and will be available in version 8.0.0
