### ISSUE TITLE
Typos in filename of selection-event model and enum

### ISSUE THREAD

**Issue by kobL** [vlio20/angular-datepicker#489]
When I was looking through the code I noticed a missing "n" in "event" and point to much in those two filenames:

src/lib/common/types/selection-evet.enum..ts
src/lib/common/types/selection-evet.model.ts

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by vlio20** [comment]
will be resolved 8.1.0 (3cdbf96)

**Comment by vlio20** [comment]
thanks @kobL for the PR
