### ISSUE TITLE
Validation in form

### ISSUE THREAD

**Issue by Lysoun** [vlio20/angular-datepicker#490]
Hello,

I would like to use format validation in a datepicker inside a form. When the format is incorrect, the form should be invalid. The validation seems to be currently only on the date picker component and not in the input that is inside the date picker. I would like the input to become invalid when the format validation failed to apply correct css and form the parent form to become invalid too. Is that currently possible?

**Comment by Lysoun** [comment]
I have tried to make you an example of my problem on stackblitz: https://stackblitz.com/edit/angular-vh4yfe

**Comment by vlio20** [comment]
Hi @Lysoun, you can achieve this with form validations. Are you using reactive form?

**Comment by Lysoun** [comment]
I am using a template driven form. Should I use reactive forms for the date picker validation to make my whole form invalid when it fails?

**Comment by vlio20** [comment]
You better always use reactive forms. You can see an example in the demo page.
