### ISSUE TITLE
[Feature Request] Ability to select a month before choosing a day / day and hour

### ISSUE THREAD

**Issue by al-petrushin** [vlio20/angular-datepicker#491]
Hi! 

I propose to make feature that will allow the developer to ```customize the display of the calendar, that is, when choosing a date, enable the user to first select the month, and then the day```.
This will be useful only for day-calendar and daytime-calendar since the calendar by month/time is used only to select the month/time. In the case of day-calendar and daytime-calendar, it will now be possible to let the user select first the month and year, and then the day and time.

This can be useful, for example, when choosing a date of birth, since, to make it more convenient, we can immediately show the months and years in nav and let the user select it first.

@vlio20 We discussed this in #465

**Comment by al-petrushin** [comment]
@vlio20 If you do not mind, then I will do it

**Comment by vlio20** [comment]
@al-petrushin sure.
Few notes:
1. Fork from next branch.
2. I am working on a year calendar so your solution should be generic in terms of what is the order of the shown calendar types ([year, month, day] , [month, day] , [year, month] etc)
3. Don't forget to add documentation
4. unit tests
5. e2e tests

Let me know if you need any help

**Comment by al-petrushin** [comment]
@vlio20 Could you, please, inform me when the calendar for the years will be ready. Not necessarily completely, but so that I can realize the ability to display the calendar of the year before the calendar of the month

**Comment by vlio20** [comment]
@al-petrushin checkout the year branch - it's not ready yet.

**Comment by vlio20** [comment]
For keeping the simplicity of the library I will mark this as won't do for now
