### ISSUE TITLE
"disableKeyPress" doesn't work

### ISSUE THREAD

**Issue by lunaboona** [vlio20/angular-datepicker#492]
When using the dpDayPicker directive in an input bound to an ngModel, the disableKeyPress option doesn't work. Initially I thought this issue only happened on Angular Material inputs but it seems to happen on a regular input as well.

[Stackblitz example](https://angular-61y3wf.stackblitz.io) (Angular 8)

**Comment by vlio20** [comment]
Hi @lunaboona , in order to make the same behaviour that supplies disableKeyPress on a directive just add readonly attribute to your input. Let me know if it solved your issue. BTW the link you shared is not working.

**Comment by lunaboona** [comment]
> 
> 
> Hi @lunaboona , in order to make the same behaviour that supplies disableKeyPress on a directive just add readonly attribute to your input. Let me know if it solved your issue. BTW the link you shared is not working.

Odd, it was working for me. Either way, I think you should mention this somewhere so other people don't run into this issue in the future :)

**Comment by vlio20** [comment]
will do. 

@lunaboona I would appreciate your ⭐️
