### ISSUE TITLE
DP-date-picker, issue NullInjector in Production (LIVE)  

### ISSUE THREAD

**Issue by Saiprasad2020** [vlio20/angular-datepicker#498]
I followed the instruction what you mentioned in readme file. 

I installed the module and i place the module in app.module.ts under imports .

then i used the dp-date-picker it was working fine in local 
but when i make it **PRODUCTION(LIVE)** it showing the issue like 

StaticInjectorError(AppModule)[DayTimeCalendarComponent -> UtilsService]: 
  StaticInjectorError(Platform: core)[DayTimeCalendarComponent -> UtilsService]: 
    NullInjectorError: No provider for UtilsService!

Can you please help me out on this. 

![image](https://user-images.githubusercontent.com/59478792/80029019-c2557d00-8503-11ea-808d-305b5193c2a9.png)

**Comment by vlio20** [comment]
What version of the lib you are using and on what version of angular are you?

**Comment by thisisRinzin** [comment]
I used the date picker version 10.0.1 with angular 8.

**Comment by vlio20** [comment]
10.0.1 is suitable for angular 10 applications.
