### ISSUE TITLE
Add time picker option

### ISSUE THREAD

**Issue by vlio20** [vlio20/angular-datepicker#5]

**Comment by isaacplmann** [comment]
Do you have thoughts on how you'd want this to be done?  I'll need this eventually, and could pitch in to help when I get time.

**Comment by vlio20** [comment]
The only this that I am sure of that it should be present only for a single calendar (a.k.a `calendarsAmount  = 1`).

1. It should have an option to appear Under the input and above the calendar
2. It should have an option to appear Under the calendar
3. It should have an option for 24 hours and 12 (AM/PM) hours format
4. It should have a material theme and a basic theme (a simple one)
5. It should be work in stand alone mode (without a calendar).

Note: It should work correctly when the calendar is drops up and down.

It should support the min and max validation (form and disabled state).

Regarding the look and feel, I think a good and simple idea:
https://www.google.co.il/search?q=time+picker&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwju-8S22PnSAhXCXRQKHZXTDrQQ_AUIBigB&biw=1440&bih=776#imgrc=HJYKKU1Eg8XZPM:

@isaacplmann , what's going to be your use-case?

**Comment by isaacplmann** [comment]
I'll need to be able to pick a datetime, date only or time only.  (Also a time duration, but that's probably a different component.)

I like the timepicker design you linked to - that feels a lot more intuitive to me than the circle analog clock style.  Is the design you linked to for the material theme or the basic theme?

**Comment by isaacplmann** [comment]
I don't have a particular use-case for this, but it should probably be able to used inline just like the datepicker.

**Comment by vlio20** [comment]
so it sounds like it also should be a stand-alone component as well

**Comment by isaacplmann** [comment]
I'm starting by creating a `<dp-time-chooser>` analogous to `<dp-day-calendar>`.  Once that is working, I'll open a PR for feedback and start working on adding `'datetime'` and `'time'` as valid `CalendarType`s in `<dp-date-picker>`.

Should there be a separate `<dp-datetime-chooser>` component that handles using `<dp-day-calendar>` and `<dp-time-chooser>` together?  Or should `<dp-date-picker>` manage that interaction?

**Comment by vlio20** [comment]
cool, few notes regarding the inline component:
1. I would probably call the inline component: `dp-time-select`.
2. It has to have form validation (min, max) - are there others?
3. It should support the relevant items from the above 4 bullets.

Regarding your question:  new configuration will be available in the `dp-day-calendar` component (`enableTimeSelect`) which than will show the time select under the calendar.  Does this answers the question?

**Comment by isaacplmann** [comment]
`dp-day-calendar` would need to be able to handle `date`, `datetime` and `time` options.  A single boolean can't handle all those cases.  You already have a `currentCalendarType` enum property - why not add a couple new values to that enum?

**Comment by vlio20** [comment]
`dp-day-calendar` I don't this that should handle `time` it can and should handle only `date` and `datetime`. `dp-date-picker` should have another type that it can handle (with `day` and `month`) which is `time`, it will handle the same as it handles the `day` and `month` types.

**Comment by isaacplmann** [comment]
Ok, I'll set it up that way.

**Comment by vlio20** [comment]
It would be great if you will start from the inline component first.

**Comment by isaacplmann** [comment]
Yes, that's the plan.

**Comment by isaacplmann** [comment]
FYI, I'm not actively working on this right now.  Being pulled away to work on other things.  Still planning to come back to this eventually.

**Comment by vlio20** [comment]
thanks @isaacplmann, it was a great contribution.
It will be released in v2 of the component.
