### ISSUE TITLE
Projects using v9 complain about Deep Imports

### ISSUE THREAD

**Issue by IxquitilisSaid** [vlio20/angular-datepicker#500]
On build, the CLI will throw `Warning: Entry point 'ng2-date-picker' contains deep imports into '/Users/MY_USER/{PROJECT_PATH}/node_modules/moment/moment'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

I opened a PR with the "fix" (if you can call it that) here: [#499 ](https://github.com/vlio20/angular-datepicker/pull/499)

Just changed `import {Moment} from 'moment/moment';` to `import {Moment} from 'moment';`

**Comment by Manviel** [comment]
Duplicate https://github.com/vlio20/angular-datepicker/issues/493
