### ISSUE TITLE
Empty input after selecting values in day-time-picker

### ISSUE THREAD

**Issue by RonRofe** [vlio20/angular-datepicker#503]
I try to implement day-time picker in my angular app (I have also tried day picker).
I can open the picker, set different configurations and add directives as documented.
The problem is that when selecting a date / date + time - it doesn't show the result on the input.
What am I doing wrong?

**APP MODULE:**
```typescript
import { DpDatePickerModule } from 'ng2-date-picker';

  imports: [
   ...
   DpDatePickerModule,
   ...
]
```

**COMPONENT:**
```typescript
import { IDatePickerDirectiveConfig, ECalendarValue } from 'ng2-date-picker';

public datePicker: IDatePickerDirectiveConfig;

ngOnInit() {
    const oneYear: number = 1000 * 60 * 60 * 24 * 365;
    const yearFromNow: Date = new Date(Date.now() + oneYear);
    const yearAgo: Date = new Date(Date.now() - oneYear);

    // Initialize configuration of date picker
    this.datePicker = {
      disableKeypress: true,
      format: 'DD-MM-YYYY',
      allowMultiSelect: false,
      min: `${yearAgo.getDate()}-${yearAgo.getMonth()+1}-${yearAgo.getFullYear()}`,
      max: `${yearFromNow.getDate()}-${yearFromNow.getMonth()+1}-${yearFromNow.getFullYear()}`,
      showTwentyFourHours: true,
      returnedValueType: ECalendarValue.String,
    }
}
```

```html
<input
    [dpDayPicker]="datePicker"
    [mode]="'daytime'"
    class="date" />
```

**Angular version:** 9.1.0
I also tried uploading an example to stackblitz but without success...
https://stackblitz.com/edit/angular-ivy-ufd1gn

**Comment by vlio20** [comment]
Will try to give it a look

**Comment by vlio20** [comment]
@RonRofe you stackblitz link doesn't work.

**Comment by RonRofe** [comment]
> @RonRofe you stackblitz link doesn't work.

https://stackblitz.com/edit/angular-ivy-ufd1gn

**Comment by vlio20** [comment]
@RonRofe still see some errors there

**Comment by RonRofe** [comment]
> @RonRofe still see some errors there

The error occurs after installing the dependency without adding anything else... I do not know why.

**Comment by vlio20** [comment]
Try to add moment to the dependencies

**Comment by RonRofe** [comment]
> Try to add moment to the dependencies

Same..

**Comment by vlio20** [comment]
I will be able to check a bit later in the meantime I suggest you to try to check how it works in the demo page.

**Comment by vlio20** [comment]
@RonRofe can you create a small repo maybe? not sure what's the issue with stackblitz
