### ISSUE TITLE
Working with RTL

### ISSUE THREAD

**Issue by RonRofe** [vlio20/angular-datepicker#504]
Hi,

I am trying to work with RTL application and after putting the picker it looks very bad compared to the LTR one.
Is there any way to configure it appropriately?

![image](https://user-images.githubusercontent.com/30625668/81491437-4c893980-9297-11ea-8a90-8a80e9155be6.png)

**Comment by vlio20** [comment]
Not currently I guess. Will be happy to accept a PR.

**Comment by RonRofe** [comment]
> Not currently I guess. Will be happy to accept a PR.

Feaure request tag?

**Comment by vlio20** [comment]
I would say bug/enhancement

**Comment by vlio20** [comment]
the fix will be available in 13.1.0
