### ISSUE TITLE
Is it support in angular 5 version?

### ISSUE THREAD

**Issue by gmengi** [vlio20/angular-datepicker#507]

**Comment by vlio20** [comment]
What issues are you encountering?

**Comment by gmengi** [comment]
error TS1086: An accessor cannot be declared in an ambient context in date-picker.component.d.ts

**Comment by vlio20** [comment]
I would suggest you to pick an appropriate version: check the changelog: https://github.com/vlio20/angular-datepicker/blob/master/CHANGELOG.md

I would start with version 8.0.0 and go backwards with the versions.
