### ISSUE TITLE
Import moment

### ISSUE THREAD

**Issue by timrasche** [vlio20/angular-datepicker#514]
Warning: Entry point 'ng2-date-picker' contains deep imports into 'node_modules/moment/moment'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

compiling 'hangs' sometimes and i'm think this is the problem.

**Comment by vlio20** [comment]
@timrasche can you point where do you see this deep imports?

**Comment by timrasche** [comment]
Of course, first line of output by angular/cli with 

- ng serve
- ng build

**Comment by vlio20** [comment]
I think I found the reason - working on a fix

**Comment by timrasche** [comment]
you're the man! big thanks!

**Comment by vlio20** [comment]
resolved in abe1cfb

**Comment by vlio20** [comment]
@timrasche can you please update to 10.0.0-rc.1 and see if you still see the issue?

**Comment by timrasche** [comment]
> @timrasche can you please update to 10.0.0-rc.1 and see if you still see the issue?

The warning by the angular/cli is gone. Thank you very much for the fast fix

**Comment by vlio20** [comment]
Cool so it will be available later today in 10.0.0. 
Your ⭐  would be appreciated :)

**Comment by timrasche** [comment]
> Cool so it will be available later today in 10.0.0.
Nice!
> Your ⭐ would be appreciated :)
Sure ;-)
