### ISSUE TITLE
Selected Date value not given with local utc timezone.

### ISSUE THREAD

**Issue by TheMuyu** [vlio20/angular-datepicker#518]
Hello thanks for datepicker for angular.
When I use date picker it gives timezone with UTC+0
I set my local to "tr" and this works with months name. But still when I clicked a date the result is UTC+0 
I need to get my locale UTC+3. My computer timezone is also UTC+3

`<dp-date-picker placeholder="Seçiniz..." theme="dp-material" [config]="datePickerConfig" formControlName="baslangicTarihi"></dp-date-picker>`

```
    this.datePickerConfig = {
      format: 'DD.MM.YYYY',
      firstDayOfWeek: 'mo',
      locale: 'tr',
    }
```

Selected Date: 16.08.2020 (16 Aug 2020)
Value: "2020-08-15T21:00:00.000Z"

**Comment by vlio20** [comment]
Hi @TheMuyu the local is only working for the language not for the timezone. Currently there is support for configurable timezone.

**Comment by TheMuyu** [comment]
Thanks @vlio20 how can i set timezone. I looked at helper page and didnt see any options

**Comment by vlio20** [comment]
Unfortunately there is no such configuration in the component. You can do
the needed adjustments on your app side.
