### ISSUE TITLE
Compile with target es5 in Angular 9 for IE compatibility

### ISSUE THREAD

**Issue by anjopater** [vlio20/angular-datepicker#519]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [x] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

I setup in the `tsconfig.json` `"target": "es5"` for IE compatility

### Steps to reproduce
`npm i` and `npm start`

### What is expected?
Compile correctly in angular 9+

### What is actually happening?
When is compiling give the error ->

```
Compiling ng2-date-picker : module as esm5 
Error on worker #7: Error: getInternalNameOfClass() called on a non-ES5 class: expected DomHelper to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass...
```

**Comment by vlio20** [comment]
The lib is also targeting es5:
https://github.com/vlio20/angular-datepicker/blob/master/tsconfig.base.json#L4

**Comment by anjopater** [comment]
Well, that's the only package that is giving me problem in the compilation, any other idea?

**Comment by vlio20** [comment]
@anjopater not really, what version are you using of the lib?

**Comment by davoam** [comment]
We had this problem with version `10`, and after downgrading to version `8` the problem has gone

**Comment by AgentEnder** [comment]
I can't replicate this @anjopater , have you tried running ngcc?
