### ISSUE TITLE
Set maximum months selected

### ISSUE THREAD

**Issue by Koronag** [vlio20/angular-datepicker#522]
Hi there

We're using the datepicker in "month" mode to provide an interface for  a user where they can select up to 3 months. These 3 months does not necessarily need be in the same range (april, june, august for example). Is there any way to disable all other months when 3 are selected? I tried using the isMonthDisabledCallback callback, but there is nothing returned here when selecting months in the "month" mode.

Thanks

**Comment by vlio20** [comment]
Hi,
Can you please share a stackblitz?

**Comment by Koronag** [comment]
Hi

Thanks for the quick response.
Please see the following stackblitz:
https://stackblitz.com/edit/angular-ivy-nobqaf?file=src/app/app.component.ts

As you can see, the callback is not called when selecting/deselecting a month. Therefore no easy way as far as i see, to create functionality for checking maximum months selected.

**Comment by vlio20** [comment]
@Koronag, I think I found the issue. I will deploy a fix as soon as possible. Hopefully today.
Thanks for pointing this out.

**Comment by Koronag** [comment]
Thanks a lot @vlio20. Unfortunately I'm stuck on v. 2.x due to project being tied to Angular 6. Any chance the patch can be applied to older versions?

**Comment by vlio20** [comment]
ammm.... can't promise that. Will do my best

**Comment by Koronag** [comment]
Appreciate the effort nonetheless!

**Comment by vlio20** [comment]
Issue was resolved in 10.0.1.
@Koronag unfortunately I wasn't able the lib on my local machine. I have created a branch 2.10.3 (https://github.com/vlio20/angular-datepicker/compare/2.10.3?expand=1) please check it out. If you will be able to make it work there, please submit a PR and I will publish it.
