### ISSUE TITLE
Is angular-datepicker compatible with Angular Ivy?

### ISSUE THREAD

**Issue by gregbrant2** [vlio20/angular-datepicker#524]
I'm pretty new with Angular so please forgive my ignorance.

I'm using Angular 10.1.2

I've just installed angular-datepicker.

    > yarn add angluar-datepicker

Imported the module into my app

```
// ...
import {DpDatePickerModule} from 'ng2-date-picker';
// ...

@NgModule({
    declarations: [AppComponent],
    imports: [
        // ... 
        DpDatePickerModule
    ],
    providers: [
        // ...
    ],
    bootstrap: [AppComponent],
})
export class AppModule {}
```

When I run the project `yarn start` I get the following error:

> Time: 1304ms
> : Compiled successfully.
> 
>     ERROR in node_modules/ng2-date-picker/date-picker.module.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> 
>     This likely means that the library (ng2-date-picker) which declares DpDatePickerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 
>     7 export declare class DpDatePickerModule {
>                            ~~~~~~~~~~~~~~~~~~

Is angular-datepicker compatible with Angular Ivy or am I doing something wrong? Thank you for your time and effort!

**Comment by vlio20** [comment]
It should be. 
Can you please post a small repository so I can reproduce?

**Comment by gregbrant2** [comment]
hi @vlio20. the issue here was I was importing the `DpDatePickerModule` in my app module, and not the component module where I was using it.  

Thanks,
Greg

**Comment by vlio20** [comment]
Happy to hear! would appreciate your support by adding you  :star: to this repo :)
