### ISSUE TITLE
date picker popup not close after select date in android 8- (last android version)

### ISSUE THREAD

**Issue by chibat1125** [vlio20/angular-datepicker#528]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by vlio20** [comment]
@chibat1125 can you please provide more information, do you see any console error?
