### ISSUE TITLE
Move to DayJS

### ISSUE THREAD

**Issue by vlio20** [vlio20/angular-datepicker#530]
As moment announced that they are moving to a maintenance mode I think that it would be the best to switch to datejs which is much lighter and has a modern API.

**Comment by petterhoel** [comment]
Hi, is there any kind of timeline for this? 

I want to use _angular-datepicker_ for a current project, but I see a lot of Moment in your public api documentation and worry about breaking changes once you migrate. 

If migration is close or in the works I might just hold back on the datepicker parts in the meantime. Any guidance you can offer at this time is appreciated 😊

**Comment by vlio20** [comment]
Hi @petterhoel it will take a while. In any case I encourage you to create some wrapper around the moment object if it's possible.

**Comment by petterhoel** [comment]
Thanks for letting me know ☺️ A wrapper is a good idea. I was kinda hoping to avoid adding moment to my bundle too, but it will be managable for my use case I think.

**Comment by vlio20** [comment]
I am considering also avoiding any 3rd party lib and use plain Date object, but this will require a lot of work around localization.

**Comment by casper5822** [comment]
You can try with luxon that comes from moment and has a new way to handle timezone

**Comment by vlio20** [comment]
works started #571

**Comment by vlio20** [comment]
@petterhoel would you agree to test a beta version which works with Dayjs instead of Moement?

**Comment by petterhoel** [comment]
Sure, but it will be in January after the holidays 🎅🏻

**Comment by vlio20** [comment]
Happy new year!

**Comment by petterhoel** [comment]
@vlio20 I will have some time for testing at the end of the week. Is there anything specific you want me to explore or just do some use cases that would be typical for me?

**Comment by vlio20** [comment]
@petterhoel exactly. Please use version 13.1.0

**Comment by petterhoel** [comment]
I finally got around to doing some basic testing. My needs are often very limited. I want to use Norwegian locale, format date freely and be able to style the UI. 

So I forked your repo and did a tiny test app for this (much less than your demo). This was fairly straightforward. I found one issue using the nb locale. The datepicker output is 1 day before what was selected in the ui. Is this a bug, am I not setting my locale right (ctor in `app.component.ts`) or am I expected to deal with time zones offsets in some way?
Screenshot: 
![image](https://user-images.githubusercontent.com/1263775/148695248-1c21b2c5-47c3-484d-be3b-bf6a1c2ccd55.png)

Changing returnedValueType to ECalendarValue.String gives the correct date. 
Screenshot:
![image](https://user-images.githubusercontent.com/1263775/148695324-4e6dbce8-2367-40d7-950f-7259bdbcad24.png)
 
Secondly I'd love some general guidance on how to best supply my own styling working with the unstyled version of your lib. 

And explicitly:
- Can I expect no or very rare changes and use your css class names for my selectors?
- Is there any way I can provide one or more custom class names for the overlay? 

My fork with test app is here: https://github.com/petterhoel/angular-datepicker/tree/test13.1.0
App is at this path: https://github.com/petterhoel/angular-datepicker/tree/test13.1.0/projects/datepicker-test-app

`npm start` is set to spin up my test app if you want to run the code 😄

**Comment by vlio20** [comment]
how did you set the locale?
* Can I expect no or very rare changes and use your css class names for my selectors? - yes
* Is there any way I can provide one or more custom class names for the overlay? - you can provide a string splitted by blank space ' '

**Comment by vlio20** [comment]
The locale should work. maybe you can try to set it even earlier.
Regarding the styles, I think I got it wrong. Maybe you could explain your requirements? A good idea would be to open a dedicated issue for that.
