### ISSUE TITLE
How can show year picker on click header date

### ISSUE THREAD

**Issue by joshi-anshul** [vlio20/angular-datepicker#531]
Hi @vlio20 

**I'm using this datepicker and its good, but not able to found option to show years modal box same as month while click on header date
Could you please let me know how can I show year picker modal?
picker is working good, just need to know that how can add year modal while select date**

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- `public config = {
		showWeekNumbers: true,
		format: "MM-DD-YYYY"
	};

                        <dp-date-picker id="search-start_at" name="search-start_at" [placeholder]='"users.labelStartDate" | translate' (onChange)="selectStartEndDate()" [(ngModel)]="startDate" [config]="config" theme="dp-material" class="dp-material-custom"></dp-date-picker>`

- [ ] Provide **screenshots** where appropriate
![year-pick](https://user-images.githubusercontent.com/47311030/101488639-dd3b0b80-3985-11eb-8769-73ae5ff5a3ee.png)

- [ ] What's the **version** of Angular you're using?
Angular 10.1.3

- [ ] Does this occur on specific browser?
No, not able to dound any option to show years picker same as month while click on picker header date

Thanks

**Comment by vlio20** [comment]
No support for a year picker yet. There is already open request

**Comment by joshi-anshul** [comment]
Ok, that issue opened from last year Jan 2019.
So could you please let me know that are you updating package, or we need to use the other one?

Thanks

**Comment by vlio20** [comment]
Iam planning to add it in the future. Can't promise any timeline
