### ISSUE TITLE
Is it possible to set a default selection date without using a Momentjs object?

### ISSUE THREAD

**Issue by vibonacci** [vlio20/angular-datepicker#538]
Is it possible to set a default selection date without using a Momentjs object? Documentation says 'string' is allowed, but I tried to the set the ngModel var to:

- `'2021-04-04'`
- `new Date().toISOString()`
- `new Date().toUTCString()`

but none of these work. Only `moment()` works.

And of course, using a javascript Date object should be possible, but I know it's on the backlog.

**Comment by vlio20** [comment]
Hi @vibonacci , can you please share a stackblitz with your setup?
