### ISSUE TITLE
Write a date from keyboard, when select it nothing happens

### ISSUE THREAD

**Issue by CosteaMihai** [vlio20/angular-datepicker#540]
If I try to add a date from the keyboard and then I go to select it, nothing happens it erases what I typed from the keyboard. I think it's a package issue, I tried the same thing on the official stackblitz of the package and the same bug appears. Thank you

https://user-images.githubusercontent.com/57099450/116253759-6ad29880-a779-11eb-8443-9146d3aa9d61.mp4

**Comment by vlio20** [comment]
Looks like a bug. I will check it out. Thanks

**Comment by vlio20** [comment]
After some investigation, it seems that this is the expected behavior. Once you are putting a valid date in the input, the date will be automatically selected so the click that you are making afterward unselects the selected date.
