### ISSUE TITLE
I don't think the package is installing correctly

### ISSUE THREAD

**Issue by mgbee8** [vlio20/angular-datepicker#55]
The module import for index.ts is export * from './bin/app/index'; but there is no app folder created during the install and so typescript does not work correctly

**Comment by james-criscuolo** [comment]
I was just about to ask a similar question. In other angular2 packages I've seen, it looks like they already transpile and include all the js files in the release.

**Comment by vlio20** [comment]
investigating...

**Comment by vlio20** [comment]
I hope I will able to introduce a fix in the next hour or so. seems like something went wrong with the last release

**Comment by vlio20** [comment]
Issue was fixed in 1.0.2. Thanks for opening the issue. Nice to see that there are people using this lib.

@mgbee8, are you using it in prod?

**Comment by mgbee8** [comment]
no I was trying it out for a new development I am considering

**Comment by vlio20** [comment]
@mgbee8, let me know if there are some missing features
