### ISSUE TITLE
Module '"ng2-date-picker"' has no exported member 'DpDatePickerModule'.ts(2305)

### ISSUE THREAD

**Issue by ahmedselim** [vlio20/angular-datepicker#556]
Dears,

While importing library in new Angular 12 project. 
Error Module '"ng2-date-picker"' has no exported member 'DpDatePickerModule'.ts(2305)

Thanks in advance.

**Comment by vlio20** [comment]
thanks @ahmedselim . I am on it

**Comment by vlio20** [comment]
@ahmedselim could you please try to test 12.0.3-rc3 version?

**Comment by vlio20** [comment]
fixed in 12.0.3
