### ISSUE TITLE
Month picker button size changed

### ISSUE THREAD

**Issue by slickam** [vlio20/angular-datepicker#558]
I just updated my project from 9.0.0 to 12.0.3. Before the update, the month picker looked like the sample in README.md, with large circular buttons to select the month. After the update, the month picker looks the same as on the demo site, with small oval buttons and much less space between them.

I'm using the dp-material theme.

This looks the same in Chrome, Firefox, and Edge.

Was this an intentional change? Is there a change I can make in my config for the control to revert this?

**Comment by vlio20** [comment]
This is not intentional. Would you like to submit a PR with a fix?

**Comment by slickam** [comment]
I'm not familiar enough with LESS or git to do that. I'm mostly a COBOL programmer and CVS user.

**Comment by vlio20** [comment]
I will try to have a look. Thanks for notifying
