### ISSUE TITLE
Manual input crashes the application

### ISSUE THREAD

**Issue by jsprds** [vlio20/angular-datepicker#561]
When you clear the input field of the datepicker via the keyboard, the application crashes. The same happens if you enter a random string. (see screencast below)

- [x] Provide a **minimal code snippet**, please make sure it is well formatted.
N.A. --> Check "example application" (https://vlio20.github.io/angular-datepicker/daytimePicker)
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
N.A. --> Check "example application" (https://vlio20.github.io/angular-datepicker/daytimePicker)
- [x] Provide **screenshots** where appropriate
https://user-images.githubusercontent.com/2709418/138855800-760ff9bc-cab3-4892-b830-67bcaa5c0eeb.mov
- [X] What's the **version** of Angular you're using?
N.A. --> Check "example application" (https://vlio20.github.io/angular-datepicker/daytimePicker)
- [X] Does this occur on specific browser?
No --> Chrome, Firefox, Safari, ...

**Comment by vlio20** [comment]
will be available in 12.0.4. Thanks for your work @jsprds
