### ISSUE TITLE
Change options dynamically

### ISSUE THREAD

**Issue by spiderdab** [vlio20/angular-datepicker#566]
Hi, I really cannot find info on how to do that, so I'm asking here:
Is it possible to set an option after the creation of the date picker?
for example, I have in the IDatePickerConfig:
{
....
max: "2021-11-11",
....
}

after something happen I want to change this parameter. How can I do that?
Thanks.

**Comment by vlio20** [comment]
@spiderdab what did you try? Can you post a stacklitz with an example?

**Comment by vlio20** [comment]
closing for now
