### ISSUE TITLE
freeze on text input

### ISSUE THREAD

**Issue by nawaz2013** [vlio20/angular-datepicker#568]
dp-date-picker component completely freeze the application on text input. -nothing is printed on console while the application hangs (tested on Edge Chrome). The only possibility is to configure inside .ts file disablekeypress flag.

- Code snippet
<dp-date-picker #calendarStart [(ngModel)]="date.dataInizio" (ngModelChange)="changeDate($event)" [displayDate]="date.dataInizio" [config]="datePickerConfig" theme="dp-material" id="dataInizio"></dp-date-picker>

datePickerConfig = {
    locale: 'it',
    firstDayOfWeek: 'mo',
    min: moment().subtract(60, 'months'),
    max: moment().add(36,'months'),
    //disableKeypress: true,
  };

- Versions as in package.json
"@angular/core": "6.0.3",
 "ng2-date-picker": "^2.7.4",
       
- Browsers (Chrome, Edge)

**Comment by vlio20** [comment]
@nawaz2013 this bug was fixed in previous versions. Please upgrade your dependencie.
