### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by andlez** [vlio20/angular-datepicker#579]
Hi,

I am quite new to angular and node. My first try to include datepicker in angular app finished with weired error "ReferenceError: require is not defined" where error is pointed to line "dayjs.extend(require('dayjs/plugin/isSameOrAfter'));" in file "ng2-date-picker.mjs". Stackoverflow users propose resolution of similar errors but those solutions do not help me to solve issue. May be anyone could provide direction how to get rid of this error in client side angular application ?

![image](https://user-images.githubusercontent.com/50266332/147840490-a6c7755a-6b64-4d6c-99f7-b6d23c06ebee.png)

**Comment by vlio20** [comment]
Hi @andlez what version are you using?
Can you share a sample project or a link to a stackblitz?

**Comment by andlez** [comment]
Happy new year ! Thank you for replay. Please find attached test project (without node_modules). Error is that webpack does no understand node's 'require' function. Screenshot of error is in file 'ERROR_SCREENSHOT.PNG'. I use @angular/core @ "13.1.1", @angular/cli @ "13.1.2"
[datepicker-test.zip](https://github.com/vlio20/angular-datepicker/files/7797317/datepicker-test.zip)

**Comment by andlez** [comment]
I use latest version of datepicker 13.1.0-rc3

**Comment by vlio20** [comment]
@andlez please note that the 12.0.4 is an old version of the datepicker.

**Comment by vlio20** [comment]
I think that your issue, in the original project is that you didn't download dayjs. It is a peer dependency.

**Comment by vlio20** [comment]
Also, @andlez, it would be great if you could support my work by giving a ⭐  for this lib. Thanks!

**Comment by vlio20** [comment]
thanks for the donation @andlez, I really appreciate it!
