### ISSUE TITLE
displayDate doesn't works

### ISSUE THREAD

**Issue by txeto90** [vlio20/angular-datepicker#589]
Hello, I have a max that is before current day. Now when datepicker is opened it shows current day and month, and i'm trying to set a default selection with displayDate for shows this max date, and it doesn't works.

Someone can help me?
Thanks so much

**Comment by vlio20** [comment]
@txeto90 please create a demo. You can use stackblitz or just post a demo repo

**Comment by txeto90** [comment]
Hello @vlio20 I am going to give you a part of the code and if you know what happens it would be a great help. Otherwise, nothing happens, but create a demo takes too much time for me. 
Anyway thank you very much.

Angular HTML file
```
<div>
    <form [formGroup]="fg" >
        <div class="dates display__flex flex-wrap margin-top--1">
            <!-- DATE FROM -->
            <div>
                <div class="label weight-bold">From date</div>
                <input type="text" formControlName="fromDate" [dpDayPicker]="config" (open)="onChangeDates()" theme="dp-material">
            </div>
            <!-- DATE TO -->
            <div>
                <div class="label weight-bold">To date</div>
                <input type="text" formControlName="toDate" [dpDayPicker]="config" (open)="onChangeDates()" theme="dp-material">
            </div>
        </div>
    </form>
</div>
```

angular TS File:
```
ngOnInit(): void {
  config = {
	format: moment.localeData().longDateFormat('L'),
	min: moment(20211212),
	max: moment(20211212),
	displayDate: moment().subtract('5', 'month') 
  },
  fg = new FormGroup(
	{
	  fromDate: new FormControl({ value: data[0].id, disabled: false }, [Validators.required]),
	  toDate: new FormControl({ value: data[1].id, disabled: false }, [Validators.required]),
	}
  )
}
```

**Comment by vlio20** [comment]
hi @txeto90, you can use the stackblitz link https://stackblitz.com/edit/angular-8xjgx8?file=src%2Fapp%2Fapp.component.ts

Just out there you configuration. Note that the latest version doesn't support moment js as the lib moved to dayjs.

Also, the displayDate attribute is not setting the value of the calendar it just opens the view on the provided date.

**Comment by txeto90** [comment]
Hello @vlio20, so with what property can I open the calendar with specific date? For example, 5 month before today. I didnt'see a property that can do it.

Thanks so much for your time.

**Comment by vlio20** [comment]
@txeto90, you just need to set it as the value of the calendar. Let me know if it doesn't works for you
