### ISSUE TITLE
[Question] How to automatically open the datepicker on focus

### ISSUE THREAD

**Issue by Chuvisco88** [vlio20/angular-datepicker#59]
Well title says it already. I added the dp-day-picker element but I have no clue how to open the day picker when the input is focused.
Can you provide some hint?

**Comment by Chuvisco88** [comment]
Nevermind, the calendar widget was shown but way down the page lol

**Comment by vlio20** [comment]
Why was it there?

**Comment by Chuvisco88** [comment]
See #60
