### ISSUE TITLE
Remove string from selection model

### ISSUE THREAD

**Issue by Senadtm87** [vlio20/angular-datepicker#591]
Why does datepicker returns type DayJs | string?
You already have in configuration date format, could you just parse it using dayjs(value:string,format:string) ?
Current solution just gives user additional requirement of checking result type and parsing it.

**Comment by vlio20** [comment]
@Senadtm87 you can change the return value type by setting the following parameter: `returnedValueType`. You can find more information in the documentation.

Let me know if you have further questions.
