### ISSUE TITLE
upgrade to ng14

### ISSUE THREAD

**Issue by vlio20** [vlio20/angular-datepicker#597]

**Comment by kut** [comment]
Out of curiosity, do the tests pass with ng14/ng14 CDK, or are there impacts on the code? Thanks Vlad!

**Comment by vlio20** [comment]
I didn't check. Hope that I will be able to work on in on this weekend.

**Comment by vlio20** [comment]
You can follow the PR here: https://github.com/vlio20/angular-datepicker/pull/598

**Comment by vlio20** [comment]
available in 14.0.0
