### ISSUE TITLE
[Bug] Date picker inside relative element misplaces the widget

### ISSUE THREAD

**Issue by Chuvisco88** [vlio20/angular-datepicker#60]
dp-day-picker can not be placed inside a relative container as the top/left value are calculated from page top/left instead of the relative container.
This results in the widget being totally misplaced the further down the element is on the page.

**Comment by vlio20** [comment]
Will take a look. For now, try to add appendTo: body.  see if it helps.

**Comment by Chuvisco88** [comment]
That did help :)

**Comment by vlio20** [comment]
@Chuvisco88, this one is fixed (I hope). let me know if you find any issues with this fix. Thanks for the contribution.
