### ISSUE TITLE
Update broken url with active url for "learning to contribute" under "Your First Contribution" in CONTRIBUTING.md

### ISSUE THREAD

**Issue by HimanshuAgrahari07** [vlio20/angular-datepicker#605]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/edit/angular-8xjgx8?file=src%2Fapp%2Fapp.component.ts) example that reproduces the bug.
- [x] Provide **screenshots** where appropriate

On clicking below link
![image](https://user-images.githubusercontent.com/57482480/199774159-1f856fe4-b487-4d6c-ab0a-ffb8392086b5.png)

It takes me to a 404 link
![image](https://user-images.githubusercontent.com/57482480/199774305-6e6bf368-319e-4979-88de-95900669d9a0.png)

@vlio20 I would like to update this link with a correct one, can you please assign this to me?
https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github

- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by vlio20** [comment]
thanks @HimanshuAgrahari07
