### ISSUE TITLE
upgrade to ng 15

### ISSUE THREAD

**Issue by vlio20** [vlio20/angular-datepicker#610]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/edit/angular-8xjgx8?file=src%2Fapp%2Fapp.component.ts) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by HimanshuAgrahari07** [comment]
@vlio20 Is someone already working on this to upgrade the angular version?

![image](https://user-images.githubusercontent.com/57482480/203731192-82d55a60-9e84-40ab-8c5f-342a4b4384b8.png)

**Comment by HimanshuAgrahari07** [comment]
I can open a PR then

**Comment by vlio20** [comment]
I would appreciate that!

**Comment by HimanshuAgrahari07** [comment]
@vlio20 opened the PR

**Comment by vlio20** [comment]
thanks @HimanshuAgrahari07 version 15.0.0 released. Thanks
