### ISSUE TITLE
ng-deep doesn't affect the calendar modal

### ISSUE THREAD

**Issue by jamesdanielspassle** [vlio20/angular-datepicker#624]
https://stackblitz.com/edit/angular-qefwh7?file=src/global_styles.css

I'm trying to update our datepicker to the latest version (15.0.1). It seems that the calendar that pops up when the input is clicked no longer sits within the `dp-date-picker` component within the DOM. This means that the classes we were applying, using `:host::ng-deep`, are no longer applying.

I've seen an old issue explaining that we can use the global css file to apply styles, but we have a large project and we're trying to keep our styles nicely separated. Is this still possible or will we need to use the global styles file?

**Comment by vlio20** [comment]
Hi @jamesdanielspassle, from what version did you do the upgrade?
You won't be able to use :host::ng-deep any longer because, as you have noted, the popup is no longer attached to its parent

**Comment by jamesdanielspassle** [comment]
From version 11. It should be fine, we'll just had to compromise a bit on our sacred filing system. :-)
