### ISSUE TITLE
Will version be updated through any script or there is no need?

### ISSUE THREAD

**Issue by pavandixit93** [vlio20/angular-datepicker#625]
https://github.com/vlio20/angular-datepicker/blob/master/package.json

Here I see that version is `0.0.0`, earlier it used to be some valid numbers. Will this be updated by running any script or there is no need.
I know inside `projects\ng2-date-picker\package.json`, the version is set to valid number but was curious about root level package version.
Cc: @vlio20

**Comment by pavandixit93** [comment]
When I ran `yarn pack` command on latest codebase I got below output, Ideally it should have been some valid version number.
```
$ yarn pack
yarn pack v1.22.5
success Wrote tarball to "D:\\project\\angular-datepicker-temp\\ng2-date-picker-demo-v0.0.0-version.tgz".
Done in 0.43s.
```

Earlier upto V12.0.0, It used to be something like below.
```
$ yarn pack
yarn pack v1.22.5
success Wrote tarball to "D:\\project\\angular-datepicker-temp\\ng2-date-picker-v12.0.0-version.tgz".
Done in 0.43s.
```

**Comment by vlio20** [comment]
Hi @pavandixit93 , this package is just for the demo website. The package's version is available in the following file:
https://github.com/vlio20/angular-datepicker/blob/master/projects/ng2-date-picker/package.json

**Comment by pavandixit93** [comment]
Hi @vlio20 Thanks for the confirmation.
