### ISSUE TITLE
Does angular-datepicker support Ivy view engine

### ISSUE THREAD

**Issue by Yawarzy** [vlio20/angular-datepicker#631]
Hi, 
We want to upgrade our project to the Angular 16, so we need to confirm whether the libraries we are using are ivy compatible or not, so we would like to confirm whether this library is compatible with the Ivy or not ?
Thanks

**Comment by vlio20** [comment]
The library was just recently updated to ng16. So it should be supported.

**Comment by Yawarzy** [comment]
@vlio20 Alright thank you !!
