### ISSUE TITLE
IDatePickerDirectiveConfig property returnedValueType has no effect for [dpDayPicker] FormControl value

### ISSUE THREAD

**Issue by matrixengine** [vlio20/angular-datepicker#635]
Version 15.0.1

When using the `[dpDayPicker]` directive on an input attached to a FormControl with `IDatePickerDirectiveConfig` `returnedValueType` set to `ECalendarValue.Dayjs`, the FormControl value is a string, not a Dayjs object

**Template:**

	<div [formGroup]="form">

		<mat-form-field appearance="fill" class="w-100">
			<input type="text"
			   matInput
			   formControlName="date"

			   [dpDayPicker]="config"
			   [mode]="'daytime'"
			   [theme]="'dp-material'"

			   autocomplete="off"
			   readonly
			/>
			<mat-label>Date</mat-label>
		</mat-form-field>

		<button type="button" (click)="save()">Save</button>

	</div>

**Form:**

	this.form = new FormGroup<DateForm>({
		date: new FormControl<Dayjs|null>(null)
	});

	save() { console.log(this.form.controls['date'].value) } //This is a string, not a Dayjs object??

When using a selector e.g. dp-date-picker with a config `IDatePickerConfig` `returnedValueType` set to `ECalendarValue.Dayjs`, the FormControl value does return Dayjs object.

I could use the onChange or onSelect events to update the input but the issue with this is that the `format` property of `IDatePickerDirectiveConfig` is not adhered to on either and so setting the FormControl value with the parameters of either of these functions means you loose the original formatting.

**Comment by vlio20** [comment]
Sorry for the late reply, can you please post a stackblitz with reproduction of your issu?

**Comment by thencke** [comment]
Hey @vlio20 

I just made an example:
[https://stackblitz.com/edit/stackblitz-starters-qq2d4h?file=src%2Fmain.ts](https://stackblitz.com/edit/stackblitz-starters-qq2d4h?file=src%2Fmain.ts)

When using the directive, the form control value becomes a string instead of a dayjs object.

**Comment by vlio20** [comment]
Another strange thing is that when focusin in the directive the compontnet's datepicker popup is show....
I will need to investigate.

**Comment by vlio20** [comment]
@thencke this is actually a lmitiation that I don't think that we can do anything about. There is no way (at least I don't have an idea how) we can break the connection between the form control representation in the input element and the "progrematic" representation of the value of the controller. 

I will update the docs accordingly.
