### ISSUE TITLE
dp-time-select` does not respect 24-hour format despite setting `hours24Format: 'HH'

### ISSUE THREAD

**Issue by Emmanuel97460** [vlio20/angular-datepicker#637]
### Description:

I'm trying to use `ng2-date-picker` to allow users to select a date and time. I would like to use the 24-hour format for the time picker, but despite setting `hours24Format: 'HH'`, the time picker still displays the time in AM/PM format.

#### ng2-date-picker version:
10.0.0
####Angular
13.3.1

#### Code:
```typescript
public config: IDatePickerConfig = {
  openOnFocus: false,
  firstDayOfWeek: 'mo',
  unSelectOnClick: false,
  closeOnSelect: true,
  closeOnSelectDelay: 0,
  min: this.minDate,
  max: this.maxDate,
  locale: 'fr',
  format: 'DD/MM/YYYY - HH:mm',
  hours24Format: 'HH',
};
```

#### Expected Behavior:
The time picker should display the time in a 24-hour format (from 00 to 23).

#### Current Behavior:
The time picker displays the time in AM/PM format.

#### Steps to Reproduce:
1. Create an Angular component with ng2-date-picker and the above configuration.
2. Open the date picker and switch to the time picker.

**Comment by Emmanuel97460** [comment]
Its ok but how to disable meridiemFormat AM/PM ?

**Comment by vlio20** [comment]
Hi, can you please share a simple stackblitz?

**Comment by vlio20** [comment]
Closing for now
