### ISSUE TITLE
The month calendar component don't config monthFormatter.

### ISSUE THREAD

**Issue by x269147836** [vlio20/angular-datepicker#65]
Path: angular-datepicker/src/app/month-calendar/month-calendar.component.html

Code: 

`{{month.date.format('MMM')}}`

**Comment by vlio20** [comment]
@x269147836, the `monthFormatter` is the formatter of the day-calendar label:  
![Imgur](http://i.imgur.com/crUGq61.png)

There is another task #36 for the formatting of a single day/month. It will be available in the next couple of days.

**Comment by vlio20** [comment]
@x269147836, this is no available in version 1.2.0. Let me know if you having any issues.

**Comment by x269147836** [comment]
@vlio20  Sorry, I did not make it clear that I knew that the head content could be formatted by `monthFormatter`
I am referring to the month of the selector panel can not be formatted:

![qq 20170420145812](https://cloud.githubusercontent.com/assets/3904501/25217575/04b4abee-25da-11e7-8914-e33c7c650b61.png)
![qq 20170420145522](https://cloud.githubusercontent.com/assets/3904501/25217577/077707a0-25da-11e7-9f0b-3d50dcc323e8.png)

**Comment by vlio20** [comment]
@x269147836, I don't think I understand. You are using `monthFormatter` and it doesn't changes the calendar header? If so please post you formatter method.
