### ISSUE TITLE
Multiple months in the picker (calendarsAmount)

### ISSUE THREAD

**Issue by isaacplmann** [vlio20/angular-datepicker#68]
Do you plan to add back in the `calendarsAmount` feature?

It seems to have disappeared in version 1.x.

**Comment by vlio20** [comment]
It causes a lot of problems and edge cases. I am not sure for what purpose it is needed. Can you tell how will you use this feature?

**Comment by isaacplmann** [comment]
I have a list of dates that need to be quickly added/removed.  If a user can see 6-12 months at once, they can easily select all the company holidays in a year for example.

**Comment by isaacplmann** [comment]
I'd be using it in inline mode and with multiSelect enabled.

**Comment by vlio20** [comment]
why not just run `*ngFor` for the inline component `<dp-day-calendar>` with the same configuration and the bind it to the same model, something like this:  
```
<dp-day-calendar 
                 *ngFor="let calendar in [1,2,3,4,5,6]"
                 [config]="config"
                 [(ngModel)]="selected">
</dp-day-calendar>
```

**Comment by isaacplmann** [comment]
That would work mostly, but the previousMonth/nextMonth buttons wouldn't stay in sync.

**Comment by isaacplmann** [comment]
And all the calendars would display the same month to start with.

**Comment by vlio20** [comment]
right. I will move it back in. How would the `enableMonthSelector` work with this feature (in previous version it the month selector was opened only in the first and last calendars)?

**Comment by isaacplmann** [comment]
I'm not sure - I'll have to look at `enableMonthSelector`

**Comment by vlio20** [comment]
It is enabled by default, you can check it out in the demo.

**Comment by isaacplmann** [comment]
I'm ok with the month selector only being enabled on the first calendar.

If you do enable it for other calendars, the month you choose should become the month for that calendar and the other calendars should update accordingly.

**Comment by vlio20** [comment]
The configuration (`enableMonthSelector `) will be applied to all calendars in the picker. I think the simplest thing to do is to enable it for all the calendars and update the rest.

**Comment by vlio20** [comment]
I will introduce a new component for this feature - `dp-calendars-container`.

**Comment by isaacplmann** [comment]
Sounds good to me.

**Comment by vlio20** [comment]
This seems to be a very hard feature witch will cause headache in extending this library. 
I will drop the development of this feature as I can't think of an easy/scalable/maintainable way to implement it.
