### ISSUE TITLE
Feature Request: Attach dp-popup to any component

### ISSUE THREAD

**Issue by isaacplmann** [vlio20/angular-datepicker#69]
I use material2 inputs for all my text inputs.  It would be nice to be able to attach a dp-popup somehow to a material2 input and have the dp-popup update the value of that component.

I realize this would require a fair amount of refactoring.  I'm happy to help with that if this is a direction you want to go.

**Comment by vlio20** [comment]
As I understand there are 2 things to this feature:  
1. Put the popup below/above the "attachTo".
2. The value should be bounded to the same model (Am I missing something?).

The first is a bit tricky because there is already `appendTo` configuration  - maybe there can be some extra configuration.

**Comment by isaacplmann** [comment]
We can add a new directive `dpDayPickerTriggerFor` (like [`mdMenuTriggerFor`](https://github.com/angular/material2/blob/94320c4e68a8e6a2093b704157900cd6cd8388e2/src/lib/menu/menu-trigger.ts)) that can only be applied to a component with an `ngModel` attribute.  (selector is `[dpDayPickerTriggerFor][ngModel]`)

Then, `dpDayPickerTriggerFor` updates `dp-day-picker` in the following ways:
1. Set `hideInputContainer` to true, use `*ngIf` to not render the `.dp-input-container`
2. Set `this.inputElementContainer` to the host component of the directive
3. Wire up value changes to the directive's `ngModel`

```html
<md-input-container>
  <input mdInput dpDayPickerTriggerFor="myPicker" [(ngModel)]="someDate" />
</md-input-container>
<dp-day-picker #myPicker [config]="someConfig"></dp-day-picker>
```

**Comment by vlio20** [comment]
so how will it affect the date picker component? what changes should be made?

**Comment by isaacplmann** [comment]
the `dp-day-picker` would need to 
(1) Create a new `@Input() hideInputContainer: boolean` that defaults to false and will be set by `dpDayPickerTriggerFor`
(2) Expose the existing `inputElementContainer` as an `@Input` and not overwrite it if it is defined

I think everything else can be handled in the `dpDayPickerTriggerFor` directive.

**Comment by vlio20** [comment]
1. I think that it is better to set it as a configuration rather than `@input` (`hideInputContainer `).
2. ok.

**Comment by isaacplmann** [comment]
-OR- Another possible approach would look like this:

```html
<md-input-container>
  <input mdInput dpDayPicker="someConfig" [(ngModel)]="someDate" />
</md-input-container>
```

And the `dpDayPicker` would insert a `<dp-day-picker>` component using the host component's `ViewContainerRef`, passing in `someConfig` as the `config` property.  I like this syntax better if I can make it work.

**Comment by isaacplmann** [comment]
I'm planning to work on this today.  I think I'll have time to work on this and the timepicker this week.

**Comment by vlio20** [comment]
I like this approach as well.
Regarding the time picker, lets talk about it in the relevant thread - I think it is a good idea to start with the inline version.

**Comment by isaacplmann** [comment]
Note: I don't see a clean way of implementing the `showGoToCurrent` button.

(Yes, I'll comment on the timepicker issue, when I'm getting ready to start on that piece.)

**Comment by isaacplmann** [comment]
Perhaps we could add `goToCurrent()` as part of the api and people could write their own `goToCurrent` button if they want to.

**Comment by vlio20** [comment]
resolved in #70. Thanks @isaacplmann.

**Comment by isaacplmann** [comment]
When do you think you'll publish to npm?

**Comment by vlio20** [comment]
I hope tomorrow.
