### ISSUE TITLE
New version with support for material as show in demo app

### ISSUE THREAD

**Issue by carlososiel** [vlio20/angular-datepicker#76]
Exist any changes that you publish new version for integrate with material as show the demo in master branch using DatePickerDirective?, actually i used the last version published in npm 1.3.0.
Thanks.

**Comment by vlio20** [comment]
In order to have a material theme you will have to do as follows:  
```
<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig" theme="material"></dp-date-picker>
```

it is present in the documentation: 
`https://github.com/vlio20/angular-datepicker#user-content-attributes`

Please close this ticket if it helped you.

@carlososiel. there is a new version just released (1.4.0).

**Comment by carlososiel** [comment]
I update to version 1.4.0 and I try 2 methods:

1. I use the component:
`<dp-date-picker formControlName="startDate" config="datePickerConfig" theme="dp-material"></dp-date-picker>`
That's work for me, but I do not have the same styles that my application. I try so with method 2
2. I use the directive as say in Readme and is showed in the demo application in demo.component.html in line 130:
```
<md-input-container>
            <input mdInput [dpDayPicker]="datePickerConfig" #dateDirectivePicker="dpDayPicker" formControlName="startDate" theme="dp-material" />
</md-input-container>
```
These raise a error:
`There is no directive with "exportAs" set to "dpDayPicker"`

I have a partial resolution, but the primary topic of these issue is about the second method.

**Comment by vlio20** [comment]
I will give it a look in the next couple of hours

**Comment by vlio20** [comment]
Can you add a screenshot of how does it looks in your implementation?

**Comment by isaacplmann** [comment]
I think I'm running into a related problem.  The `[dpDayPicker]` requires an `[ngModel]` on the host component.  It doesn't take into account using `formControlName` instead.  I'm working on fixing that now.

**Comment by isaacplmann** [comment]
FYI, this is where I figured out what was happening: https://github.com/angular/angular/issues/9363#issuecomment-227878238

**Comment by vlio20** [comment]
@isaacplmann, do you have the same issue with the styling?

**Comment by isaacplmann** [comment]
When I use a plain `ngModel` (from `FormsModule`), the styling appears fine.  When I use a `FormControl` (from `ReactiveFormsModule`) there is some hidden error (that is, it doesn't appear in the console) that happens and styling is broken on several components in my app, including the `[dpDayPicker]`.

**Comment by vlio20** [comment]
@isaacplmann, can you tell what causes this issue?

**Comment by isaacplmann** [comment]
Basically, the `formControlName` or `formControl` directive has `ngModel` as an attribute.  So if they are present, there is no plain `ngModel` directive on the component.  So I need to figure out how to interact with the `formControl` directive instead of the `ngModel` directive, whenever it is present.

**Comment by vlio20** [comment]
So it also means that the `dp-date-picker` component is broken as well - right?

**Comment by carlososiel** [comment]
@vlio20 [The screenshoot](http://prntscr.com/f1jocm)

**Comment by vlio20** [comment]
@carlososiel, it is not broken - this the default theme. You can see it in the demo when you disabling the material theme.

**Comment by carlososiel** [comment]
@vlio20 The problem was with the theme I have material and not dp-material, I change it and look better, the problem is that can not use the component inside a md-input-container and then I need reproduce the same syle of elements of material. This issue can be closed. Thanks

**Comment by vlio20** [comment]
@carlososiel, is it looks the same as in the demo?  
You can use the directive and put it on your input inside the `md-input-container `. let me know if you need help with that.

**Comment by carlososiel** [comment]
@vlio20 With the directive show the same error that explained above.

**Comment by isaacplmann** [comment]
I'm close to a PR that should fix the issues with the directive.
