### ISSUE TITLE
Navigation buttons missing type attribute

### ISSUE THREAD

**Issue by eeroki** [vlio20/angular-datepicker#81]
Navigation buttons in datepicker seem to be missing type="button", default value is submit for most browsers. 
This submits form if datepicker is used inside a form which propably is not what you want.

**Comment by vlio20** [comment]
@eeroki, do you want to submit a PR? if not I will handle this myself as part of v2 milestone.

**Comment by eeroki** [comment]
@vlio20, since lennu is already on it I'll leave it to you two.

**Comment by vlio20** [comment]
this fix is available in 1.4.2 version. @lennu thanks for the quick PR!
