### ISSUE TITLE
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost/ng2-date-picker

### ISSUE THREAD

**Issue by bandersen22000** [vlio20/angular-datepicker#84]
Hi    
"ng2-date-picker": "^1.4.2" to my package.json and added the imports to the datepicker in my app.module.ts file.

I have the datepicker files in  the folder "node_modules\ng2-date-picker" but when I run the app, i get the following error ?
`
(index):24 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost/ng2-date-picker
	Error: XHR error (404 Not Found) loading http://localhost/ng2-date-picker
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost/node_modules/zone.js/dist/zone.js:1032:39)
	    at ZoneDelegate.invokeTask (http://localhost/node_modules/zone.js/dist/zone.js:414:31)
	    at Zone.runTask (http://localhost/node_modules/zone.js/dist/zone.js:181:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost/node_modules/zone.js/dist/zone.js:476:38)
	Error loading http://localhost/ng2-date-picker as "ng2-date-picker" from http://localhost/app/app.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost/node_modules/zone.js/dist/zone.js:1032:39)
	    at ZoneDelegate.invokeTask (http://localhost/node_modules/zone.js/dist/zone.js:414:31)
	    at Zone.runTask (http://localhost/node_modules/zone.js/dist/zone.js:181:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost/node_modules/zone.js/dist/zone.js:476:38)
	Error loading http://localhost/ng2-date-picker as "ng2-date-picker" from http://localhost/app/app.module.js`

**Comment by vlio20** [comment]
are you using systemjs in your project?

**Comment by bandersen22000** [comment]
Yes I use my own systemjs. I have attached it.

[systemjs.config.txt](https://github.com/vlio20/angular-datepicker/files/1000997/systemjs.config.txt)

**Comment by vlio20** [comment]
you will have to add it as you added other 3rd party libs I guess.

**Comment by vlio20** [comment]
@bandersen22000 , did you manage to sole this issue?

**Comment by bandersen22000** [comment]
No sorry, i tried different things, but I did not solve the problem. I ended up using jqueryUI datepicker. But I would like to use ng2-date-picker instead. Do you have any other suggestions to what the problem could be ?

**Comment by bandersen22000** [comment]
My solution I based on the angular-visual studio startup solution: https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html

**Comment by vlio20** [comment]
did you try to do the following:
```
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      'app': 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
      'ng2-date-picker': 'npm:ng2-date-picker'  // <------------------- this line
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        defaultExtension: 'js',
        meta: {
          './*.js': {
            loader: 'systemjs-angular-loader.js'
          }
        }
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
  });
})(this);

```

**Comment by vlio20** [comment]
closing....

**Comment by bandersen22000** [comment]
Sorry for the late response, it worked. I added a star :)

**Comment by vlio20** [comment]
@bandersen22000 , thanks!!!
