### ISSUE TITLE
Internationalization option for month names

### ISSUE THREAD

**Issue by rodrigofns** [vlio20/angular-datepicker#86]
I see there's a `weekdayNames` option to internationalize weekdays, but I can't see a `monthNames`. Is it on the roadmap?

**Comment by vlio20** [comment]
you can use the `monthFormatter `. What exactly you want to Internationalize?

**Comment by rodrigofns** [comment]
The name of the month currently displayed. For example, I'm using this to translate the weekdays to Brazilian Portuguese:

`weekdayNames: { su:'D', mo:'S', tu:'T', we:'Q', th:'Q', fr:'S', sa:'S' }`

Then I thought there would be something like:

`monthNames: { jan:'Janeiro', feb:'Fevereiro', mar:'Março', ... }`

I actually haven't noticed `monthFormatter`, I'll check it out, thanks.

**Comment by vlio20** [comment]
glad it helped.
Please let me know if you have other issues.
