### ISSUE TITLE
Month navigation doesn't work with Material

### ISSUE THREAD

**Issue by rodrigofns** [vlio20/angular-datepicker#87]
I'm using the component as a directive, and everything works fine. However, when using the [Material](https://material.angular.io/) `mdInput` directive, the month currently displayed on the calendar won't change when clicking on `<` and `>`, and also when clicking the month granularity selector.

Taking the example from the demo, this works:
```
<input
  [dpDayPicker]="config"
  name="datePicker"
  #dateDirectivePicker="dpDayPicker"
  #dateDirectivePickerModel="ngModel"
  theme="dp-material"
  [(ngModel)]="date"
  [placeholder]="placeholder"
  [disabled]="disabled"
  [required]="required"
  (ngModelChange)="log($event)"/>
```

But this makes the month navigation stop:
```
<md-input-container>  <------- surrounding tags
  <input
    mdInput  <------- notice this
    [dpDayPicker]="config"
    name="datePicker"
    #dateDirectivePicker="dpDayPicker"
    #dateDirectivePickerModel="ngModel"
    theme="dp-material"
    [(ngModel)]="date"
    [placeholder]="placeholder"
    [disabled]="disabled"
    [required]="required"
    (ngModelChange)="log($event)"/>
</md-input-container>
```

I'm not using Material's own datepicker because this one is much richer.

**Comment by vlio20** [comment]
Can you please create a simple project to show the issue? @isaacplmann, can you reproduce this issue?

**Comment by isaacplmann** [comment]
Month navigation is working for me using `mdInput`.  I'm using the `formControl` directive instead of `ngModel`, but that shouldn't make a difference.  A demo repo would help a lot.

**Comment by rodrigofns** [comment]
There you go, I uploaded the whole testing project [right here](https://github.com/rodrigofns/datepicker-example). Just run `npm install` and `npm start`. Specifically, the datepicker [is here](https://github.com/rodrigofns/datepicker-example/tree/master/src/app/outro). I hope you can reproduce it, thanks in advance.

**Comment by isaacplmann** [comment]
@vlio20 
After running `npm start` you'll need to navigate to `localhost:8080/outro`.  It appears that the `dp-day-picker` component is re-focusing the input on every click which triggers the calendar to go to the currently selected day.  I don't have time to look at it today.  I'll try to take a look in the next few days if you haven't solved it by then.

**Comment by vlio20** [comment]
thanks @isaacplmann, I will give it a look as well

**Comment by vlio20** [comment]
@rodrigofns, seems like the `md-input-container` is listening to clicks on it child elements and it what causes the "re-focusing". As a workaround I would suggest you to use `appendTo: body` in the config object you pass to the component. Here is a full example as seen in your code:  
``` javascript
private dtpConfig: any = {
		format: 'DD/MM/YYYY',
		allowMultiSelect: false,
		disableKeypress: true,
		weekdayNames: { su:'D', mo:'S', tu:'T', we:'Q', th:'Q', fr:'S', sa:'S' },
		monthFormatter: (m: Moment): string => {
			return [ 'jan', 'fev', 'mar', 'abr', 'mai', 'jun',
				'jul', 'ago', 'set', 'out', 'nov', 'dez' ][m.month()] +
				', ' + m.year();
		},
		appendTo: 'body'  // <-------------- this line
	};
```

Let me know if you have further issues.
