### ISSUE TITLE
No change Event

### ISSUE THREAD

**Issue by egandro** [vlio20/angular-datepicker#88]
Hi,

this is a nice component I'd like to add to my projects.

However I'd like to have a (change) event e.g. like we get it in other default HTML Form elements (checkbox, texts, etc.)

I need this because I'd like to wrap the datepicker in some highlevel components that will be used in forms.

Can you please add a change() event?

Very simple:

@Output() change = new EventEmitter();

and emit it

this.change.emit(value);

**Comment by vlio20** [comment]
@egandro, please take a look at https://github.com/vlio20/angular-datepicker/issues/77. Let me know if it solves your issue.

**Comment by egandro** [comment]
Thx! it works :)

**Comment by vlio20** [comment]
cool. closing! ⭐️ will be much appreciated :)
