### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by rohitsodhia** [vlio20/angular-datepicker#89]
Sorry if I'm missing it, but is there a means of setting a default theme? For example, right now, I'd like to use dp-material as the theme for all the datepickers, but I'd have to set it as an attribute on each one. I don't see anything in the config object in the docs.

**Comment by vlio20** [comment]
Yea there is no "global" configuration for the theme. You will have to add it to every instance of the component.

**Comment by rohitsodhia** [comment]
Thanks for the response. Not sure if you take requests and if you do, how to put that in, but if possible, this would be a great feature in the future.

**Comment by vlio20** [comment]
sure I am taking request! And this might be a nice feature. Currently I don't have time to develop it, but if you like to submit a PR it would be great!!!

**Comment by rohitsodhia** [comment]
Sure! I'm newer to Angular, but I'll give it a shot.

**Comment by vlio20** [comment]
Shouldn't be to complicated. Let's discus here how do you think this should be implemented. I will reopen this issue.

**Comment by vlio20** [comment]
will close for now
