### ISSUE TITLE
dpDayPicker min date issue

### ISSUE THREAD

**Issue by francarmona** [vlio20/angular-datepicker#90]
If I set a min date user can not select a previous day to moment() in the calendar, that is correct. However user can type a previous day in the input box and calendar set that day, so that is wrong.

    datePickerConfig: IDatePickerConfig = {
        firstDayOfWeek: 'mo',
        format: 'DD-MM-YYYY',
        **min: moment()**
    };
    <input name="fechaModificacion" [(ngModel)]="fechaModificacion" [dpDayPicker]="datePickerConfig"   class="form-control" id="fechaModificacion" placeholder="Fecha modificación" [theme]="'dp-material'">

**Comment by vlio20** [comment]
hi @francarmona, you are right seems like a bug.
However I wonder what should be the user experience in this case? Do you have any suggestion or example?

**Comment by francarmona** [comment]
Hi @vlio20. I suggest you to mark the form field as invalid and show a red border in the input to the user. Thank you very much!

**Comment by vlio20** [comment]
This already cab be achived by using the min property as one of the
attributes of the element.

There should be some blocking experience.

**Comment by francarmona** [comment]
It doesn´t work, in order to get working min property I should add type="date" to the input and it shows the html5 calendar control by default instead of yours.

**Comment by vlio20** [comment]
mmm... I will take a look. Meanwhile, do you have to use the directive? maybe you can you use the component instead?

**Comment by vlio20** [comment]
@isaacplmann, I have made some changes to the directive though I am not feeling comfortable with them and it would be great if you could consult a bit here. 

Here are my points of concern:
1. I feel that what I am doing in the directive is a bit hacky, as I am accessing the validation function manually.
2. I am not sure how to do a `required` validation after my fix.

Your help would be much appreciated.

**Comment by isaacplmann** [comment]
1. The only other way I could think of to register the datepicker validation on the input's `FormControl` is to do this:
```ts
    this.datePicker.registerOnChange((value) => {
      this.formControl.control.setValue(this.datePicker.inputElementValue);
      this.formControl.control.markAsDirty();
      this.formControl.control.setValidators(this.datePicker.validate.bind(this.datePicker));
    });
```
My method has the drawback of overwriting any validators that the consumer may have added to that input.

2. You can add a required validator like this:
```ts
this.formControl.control.setValidators([this.datePicker.validate.bind(this.datePicker), Validators.required]);
```

**Comment by vlio20** [comment]
Regarding the required validation, seems like my method of applying min and max validation breaks the required validation when it is set as an attribute. You can see it in the demo page of the min-directive brunchm

**Comment by vlio20** [comment]
Seems like I found the solution for the required validation.

**Comment by vlio20** [comment]
@francarmona, I will soon push a fix for the validation issue of the directive. Still I am trying to think of a way to prevent a user of typing invalid date.

**Comment by vlio20** [comment]
you will find the validations working on 1.4.3

**Comment by francarmona** [comment]
Great. Thank you very much for the quick fix @vlio20

**Comment by vlio20** [comment]
@francarmona your ⭐️ would be much appreciated :)
