### ISSUE TITLE
[Bug] Extra week of next month in the calendar

### ISSUE THREAD

**Issue by maiyaporn** [vlio20/angular-datepicker#91]
The last week in the calendar is next month week. The calendar for the month of May should end at 3rd June.

<img width="228" alt="screen shot 2017-05-26 at 2 39 14 pm" src="https://cloud.githubusercontent.com/assets/5413088/26510593/a9184de8-4223-11e7-9d2e-8474d0c97ab8.png">

**Comment by vlio20** [comment]
The calendar is designed to always show 6 weeks. So this is not a bug. You can always switch off the visibility of near month days.
