### ISSUE TITLE
Directive not working with reactive forms

### ISSUE THREAD

**Issue by rohitsodhia** [vlio20/angular-datepicker#93]
I'm using Angular 4.0.0, so not sure if it's a version issue, but I was able to get the directive working with template forms, but once I switched to a reactive form, it no longer opens up the picker. I saw there was a merge about a month back to get reactive forms working, so not sure if it's me. As nothing shows up in the console, I also don't know how to debug this, nor what kind of information I should provide to help narrow down the problem.

**Comment by vlio20** [comment]
Hi, Can you please make a demo repo which shows how you are trying to use it with a reactive form?

**Comment by rohitsodhia** [comment]
https://github.com/rohitsodhia/datepicker_example

It's likely I'm missing something, but I'm not sure what...

**Comment by vlio20** [comment]
@rohitsodhia, I suggest you to take a look at the implementation in the demo page of the component. There is a special example for reactive forms - here is a link to the page: https://github.com/vlio20/angular-datepicker/blob/master/src/app/demo/demo/demo.component.ts

Let me know if it helps.

**Comment by rohitsodhia** [comment]
I did review that page prior to asking my question, but I'm not sure what I'm missing that is on that page.

**Comment by vlio20** [comment]
@isaacplmann, I am not familiar enough with reactive forms, maybe you can help @rohitsodhia ?

**Comment by trobinpl** [comment]
@rohitsodhia I just resolved similar problem except I wasn't using reactive forms. In your repository I noticed, that you're attaching datepicker to `input` with `type` property e.g. `<input type="text" formControlName="start" name="start" [dpDayPicker]="dpConfig" theme="dp-material">`. Try loosing `type="text"` - that was exactly my issue.

**Comment by vlio20** [comment]
closing for now...
