### ISSUE TITLE
month change issue

### ISSUE THREAD

**Issue by pklaparda** [vlio20/angular-datepicker#96]
hi, I'm trying to implement the datepicker with material, using the [dpDayPicker] directive. I get to see the calendar openining, even choosing the date and loading in a component attr, but I cannot change the month, the arrows dont work, and the enableMonthSelector lets me pick another month.. but I end up in the same month the calendar started (now it's may 30.. so I´m stuck in may).

any idea whats going on?
html:
`<md-input-container>
<input mdInput #fechaNac placeholder="Fecha de Nacimiento" required [dpDayPicker]='dateConfig' theme="dp-material" attachTo=".mat-input-wrapper" [(ngModel)]="birthday" name="birthday">
</md-input-container>`
on the component:
`dateConfig: IDatePickerDirectiveConfig
    = {
      format: 'MM/DD/YYYY',
      weekdayNames: {su: 'D', mo: 'L', tu: 'M', we: 'M', th: 'J', fr: 'V', sa: 'S'},
      enableMonthSelector: true,
      showNearMonthDays: false
    };`

It´d also be great to have the chance of changing the months names (to spanish for ex..)
hope to get the feedback soon, thanks a lot.

**Comment by vlio20** [comment]
yes, please check this https://github.com/vlio20/angular-datepicker/issues/87

you need to append to add 'appendTo: body' property to your configuration object.

let me know if it helped.

**Comment by pklaparda** [comment]
thank you man so much!
sorry I ddn't check out closed issues :{

**Comment by vlio20** [comment]
glad it helped you. your ⭐️ will be appreciated
