### ISSUE TITLE
Misleading usage example for the inline calendar in the NPM docs

### ISSUE THREAD

**Issue by exial** [vlio20/angular-datepicker#97]
Should be `<dp-day-calendar>`/`<dp-month-calendar>` instead of `<dp-calendar>`.

**Comment by vlio20** [comment]
You are right. Will fix it. Or even better, do you want to PR?

**Comment by vlio20** [comment]
@exial, I can't find any `<dp-calendar>` in the readme file. can you please point out the line?

**Comment by vlio20** [comment]
will close for now
