### ISSUE TITLE
minDate not working

### ISSUE THREAD

**Issue by MarcinWirkus** [vlio20/angular-datepicker#99]
I'm trying to set "minDate" in component configuration, unfortunately, it does not work. 
`<dp-date-picker [(ngModel)]="modelED" #dataEnd theme="dp-material" name="dataEnd" minDate="{{prevDay}}"></dp-date-picker>`

In the code is date:
`ng-reflect-min-date="Sun Jun 11 2017 13:13:33 GMT+0"`
 but not displayed in "data-picker".

**Comment by vlio20** [comment]
@MarcinWirkus, what are you trying to achieve? disable the selection of dates prior to minDate or get a validation error when user selects a date prior the minDate?

**Comment by MarcinWirkus** [comment]
@vlio20 - disable the selection of dates prior to minDate ;)

**Comment by vlio20** [comment]
Please see the min option in the config. You will find it in the Readme file

**Comment by MarcinWirkus** [comment]
Thanks! I work in my first project in Angular4 and I not found in the documentation how add settings with "config"? Please, add this section in the readme file

**Comment by vlio20** [comment]
you will find it here https://github.com/vlio20/angular-datepicker#configuration (`min`).

**Comment by viniciushvc** [comment]
@vlio20 i trying to set a min date, but when i do, the back button disappear
